# Reasoning & Rationale Word-Stem Frequencies

Builds a single CSV of word-stem frequencies from two text corpora:

1. **Reasoning** — assistant `reasoning` + `text` parts in `replay/*/*.json`
2. **Rationale** — `replayRationale` column across all `replay/nuke-*-results.csv`

Output: `reasoning_rationale_stems.csv` with columns `stem, reasoning_count, rationale_count, total_count`, sorted by `total_count` desc. Ground-truth for a later pass that picks ethical-sounding stems and correlates them with `replay_use_nuke_delta`.

Corpus extraction lives in `nuke/utils/text_corpus.py`.

In [1]:
import sys
sys.path.insert(0, '..')

from collections import Counter

import pandas as pd
from tqdm.auto import tqdm

import nltk
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords

try:
    _ = stopwords.words('english')
except LookupError:
    nltk.download('stopwords')

try:
    import orjson as _json_mod
    def _load_json(path):
        return _json_mod.loads(path.read_bytes())
except ImportError:
    import json as _json_mod
    def _load_json(path):
        with path.open("r", encoding="utf-8") as f:
            return _json_mod.load(f)

from shared.plot_utilities import setup_notebook_display
from nuke.utils.text_corpus import (
    list_reasoning_json_paths,
    extract_rationale_texts,
    make_stem_fn,
)

setup_notebook_display()

STEMMER = SnowballStemmer('english')
STOP = set(stopwords.words('english'))
STOP.add("morale")  # exclude — different word from "moral" (ethics)
stem_fn = make_stem_fn(STEMMER, stopwords=STOP)

C:\Users\John Chen\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Reasoning corpus from replay JSONs

In [2]:
import re as _re
from nuke.utils.load_replay_data import _FILENAME_CONDITIONS, canonical_condition_name

_FNAME_RE = _re.compile(r"(?P<game_id>[0-9a-f-]+)-p(?P<player_id>\d+)-t(?P<turn>\d+)-.+-(?P<repetition>\d+)\.json$")
_CONDITIONS_LONGEST_FIRST = sorted(_FILENAME_CONDITIONS, key=len, reverse=True)
_REASONING_TYPES = ("reasoning", "text")

def _parent_to_condition_model(dirname: str) -> tuple[str | None, str | None]:
    stripped = dirname.removeprefix("nuke-")
    for c in _CONDITIONS_LONGEST_FIRST:
        prefix = c + "-"
        if stripped.startswith(prefix):
            return canonical_condition_name(c), stripped.removeprefix(prefix)
    return None, None

paths = list_reasoning_json_paths()
print(f'Found {len(paths):,} replay JSON files')

reasoning_counter = Counter()
reasoning_rows = []
nuke_check_rows = []
n_ok = 0
n_skipped = 0

for path in tqdm(paths):
    try:
        data = _load_json(path)
    except (ValueError, OSError):
        n_skipped += 1
        continue

    messages = data.get("replay", {}).get("messages") or []
    if not messages:
        n_skipped += 1
        continue
    content = messages[0].get("content")
    if not isinstance(content, list):
        n_skipped += 1
        continue

    pieces = []
    json_use_nuke = None
    for part in content:
        if not isinstance(part, dict):
            continue
        ptype = part.get("type")
        if ptype in _REASONING_TYPES:
            txt = part.get("text")
            if isinstance(txt, str) and txt:
                pieces.append(txt)
        elif ptype == "tool-call" and json_use_nuke is None:
            flavors = part.get("input", {}).get("Flavors")
            if isinstance(flavors, dict) and "UseNuke" in flavors:
                json_use_nuke = flavors["UseNuke"]

    if not pieces:
        n_skipped += 1
        continue

    text = "\n".join(pieces)
    stems = stem_fn(text)
    reasoning_counter.update(stems)
    n_ok += 1

    m = _FNAME_RE.search(path.name)
    cond, model = _parent_to_condition_model(path.parent.name)
    if m and cond is not None:
        reasoning_rows.append({
            "game_id": m["game_id"],
            "player_id": int(m["player_id"]),
            "turn": int(m["turn"]),
            "condition": cond,
            "repetition": int(m["repetition"]),
            "replay_model": model,
            "text": text,
            "stem_set": frozenset(stems),
        })
        nuke_check_rows.append({
            "game_id": m["game_id"],
            "player_id": int(m["player_id"]),
            "turn": int(m["turn"]),
            "condition": cond,
            "repetition": int(m["repetition"]),
            "replay_model": model,
            "json_use_nuke": json_use_nuke,
        })

print(f'Parsed OK       : {n_ok:,}')
print(f'Skipped         : {n_skipped:,}')
print(f'Unique stems    : {len(reasoning_counter):,}')
print(f'Total tokens    : {sum(reasoning_counter.values()):,}')
print(f'Rows cached     : {len(reasoning_rows):,}')
print(f'Nuke check rows : {len(nuke_check_rows):,}')

Found 37,084 replay JSON files

  0%|          | 0/37084 [00:00<?, ?it/s]

  0%|          | 35/37084 [00:00<01:51, 333.56it/s]

  0%|          | 69/37084 [00:00<01:57, 316.36it/s]

  0%|          | 101/37084 [00:00<01:58, 311.04it/s]

  0%|          | 135/37084 [00:00<01:55, 320.12it/s]

  0%|          | 168/37084 [00:00<01:58, 312.52it/s]

  1%|          | 200/37084 [00:00<02:01, 304.58it/s]

  1%|          | 231/37084 [00:00<02:03, 297.22it/s]

  1%|          | 261/37084 [00:00<02:04, 294.80it/s]

  1%|          | 297/37084 [00:00<01:58, 311.42it/s]

  1%|          | 329/37084 [00:01<01:57, 313.79it/s]

  1%|          | 361/37084 [00:01<01:56, 315.49it/s]

  1%|          | 393/37084 [00:01<01:57, 311.75it/s]

  1%|          | 425/37084 [00:01<02:10, 280.40it/s]

  1%|          | 454/37084 [00:01<02:20, 260.07it/s]

  1%|▏         | 481/37084 [00:01<02:39, 229.28it/s]

  1%|▏         | 505/37084 [00:01<02:46, 219.06it/s]

  1%|▏         | 528/37084 [00:01<02:52, 211.47it/s]

  1%|▏         | 550/37084 [00:02<02:53, 210.67it/s]

  2%|▏         | 574/37084 [00:02<02:47, 217.67it/s]

  2%|▏         | 598/37084 [00:02<02:43, 222.52it/s]

  2%|▏         | 621/37084 [00:02<02:43, 222.54it/s]

  2%|▏         | 644/37084 [00:02<02:42, 223.67it/s]

  2%|▏         | 667/37084 [00:02<02:49, 215.12it/s]

  2%|▏         | 689/37084 [00:02<02:48, 216.49it/s]

  2%|▏         | 711/37084 [00:02<02:50, 213.81it/s]

  2%|▏         | 733/37084 [00:02<02:53, 209.15it/s]

  2%|▏         | 755/37084 [00:02<02:53, 209.13it/s]

  2%|▏         | 777/37084 [00:03<02:53, 209.44it/s]

  2%|▏         | 817/37084 [00:03<02:17, 263.10it/s]

  2%|▏         | 867/37084 [00:03<01:49, 331.17it/s]

  2%|▏         | 914/37084 [00:03<01:39, 364.98it/s]

  3%|▎         | 967/37084 [00:03<01:28, 409.13it/s]

  3%|▎         | 1016/37084 [00:03<01:23, 432.31it/s]

  3%|▎         | 1066/37084 [00:03<01:19, 452.12it/s]

  3%|▎         | 1123/37084 [00:03<01:15, 479.41it/s]

  3%|▎         | 1175/37084 [00:03<01:14, 482.71it/s]

  3%|▎         | 1224/37084 [00:04<01:18, 455.56it/s]

  3%|▎         | 1270/37084 [00:04<01:26, 411.99it/s]

  4%|▎         | 1313/37084 [00:04<01:29, 401.19it/s]

  4%|▎         | 1354/37084 [00:04<01:31, 389.33it/s]

  4%|▍         | 1394/37084 [00:04<01:36, 370.36it/s]

  4%|▍         | 1434/37084 [00:04<01:34, 375.83it/s]

  4%|▍         | 1477/37084 [00:04<01:32, 386.54it/s]

  4%|▍         | 1516/37084 [00:04<01:36, 370.20it/s]

  4%|▍         | 1554/37084 [00:04<01:41, 350.57it/s]

  4%|▍         | 1590/37084 [00:05<02:24, 246.23it/s]

  4%|▍         | 1619/37084 [00:05<02:43, 216.92it/s]

  4%|▍         | 1644/37084 [00:05<03:14, 182.59it/s]

  4%|▍         | 1666/37084 [00:05<03:46, 156.10it/s]

  5%|▍         | 1684/37084 [00:05<04:00, 147.04it/s]

  5%|▍         | 1701/37084 [00:06<04:46, 123.46it/s]

  5%|▍         | 1715/37084 [00:06<04:39, 126.45it/s]

  5%|▍         | 1729/37084 [00:06<05:04, 115.99it/s]

  5%|▍         | 1746/37084 [00:06<04:37, 127.27it/s]

  5%|▍         | 1762/37084 [00:06<04:23, 134.29it/s]

  5%|▍         | 1777/37084 [00:06<04:32, 129.33it/s]

  5%|▍         | 1795/37084 [00:06<04:12, 139.90it/s]

  5%|▍         | 1810/37084 [00:07<04:30, 130.24it/s]

  5%|▍         | 1824/37084 [00:07<04:41, 125.46it/s]

  5%|▍         | 1838/37084 [00:07<04:41, 125.21it/s]

  5%|▍         | 1851/37084 [00:07<04:56, 118.66it/s]

  5%|▌         | 1866/37084 [00:07<04:39, 126.21it/s]

  5%|▌         | 1880/37084 [00:07<04:31, 129.79it/s]

  5%|▌         | 1894/37084 [00:07<04:33, 128.56it/s]

  5%|▌         | 1913/37084 [00:07<04:01, 145.34it/s]

  5%|▌         | 1928/37084 [00:07<04:33, 128.73it/s]

  5%|▌         | 1942/37084 [00:08<05:02, 116.31it/s]

  5%|▌         | 1973/37084 [00:08<03:33, 164.41it/s]

  5%|▌         | 2016/37084 [00:08<02:31, 231.21it/s]

  6%|▌         | 2057/37084 [00:08<02:05, 279.00it/s]

  6%|▌         | 2101/37084 [00:08<01:49, 318.49it/s]

  6%|▌         | 2141/37084 [00:08<01:42, 341.35it/s]

  6%|▌         | 2182/37084 [00:08<01:36, 360.98it/s]

  6%|▌         | 2224/37084 [00:08<01:32, 376.95it/s]

  6%|▌         | 2268/37084 [00:08<01:29, 390.54it/s]

  6%|▌         | 2312/37084 [00:09<01:26, 402.66it/s]

  6%|▋         | 2353/37084 [00:09<01:33, 370.49it/s]

  6%|▋         | 2391/37084 [00:09<01:56, 298.11it/s]

  7%|▋         | 2424/37084 [00:09<02:18, 250.18it/s]

  7%|▋         | 2452/37084 [00:09<02:26, 236.60it/s]

  7%|▋         | 2478/37084 [00:09<02:25, 237.11it/s]

  7%|▋         | 2507/37084 [00:09<02:19, 248.29it/s]

  7%|▋         | 2535/37084 [00:09<02:14, 256.25it/s]

  7%|▋         | 2562/37084 [00:10<02:26, 235.71it/s]

  7%|▋         | 2589/37084 [00:10<02:21, 244.36it/s]

  7%|▋         | 2615/37084 [00:10<02:20, 245.39it/s]

  7%|▋         | 2641/37084 [00:10<02:18, 248.38it/s]

  7%|▋         | 2667/37084 [00:10<02:20, 244.44it/s]

  7%|▋         | 2696/37084 [00:10<02:15, 253.78it/s]

  7%|▋         | 2722/37084 [00:10<02:22, 241.31it/s]

  7%|▋         | 2747/37084 [00:11<04:14, 134.97it/s]

  7%|▋         | 2766/37084 [00:11<05:03, 113.14it/s]

  8%|▊         | 2782/37084 [00:11<05:49, 98.27it/s]

  8%|▊         | 2795/37084 [00:11<06:22, 89.59it/s]

  8%|▊         | 2807/37084 [00:12<07:02, 81.10it/s]

  8%|▊         | 2817/37084 [00:12<07:39, 74.57it/s]

  8%|▊         | 2826/37084 [00:12<07:58, 71.61it/s]

  8%|▊         | 2834/37084 [00:12<08:07, 70.26it/s]

  8%|▊         | 2842/37084 [00:12<08:32, 66.80it/s]

  8%|▊         | 2849/37084 [00:12<08:38, 66.02it/s]

  8%|▊         | 2856/37084 [00:12<08:58, 63.57it/s]

  8%|▊         | 2863/37084 [00:13<09:55, 57.51it/s]

  8%|▊         | 2869/37084 [00:13<10:01, 56.85it/s]

  8%|▊         | 2875/37084 [00:13<10:03, 56.64it/s]

  8%|▊         | 2882/37084 [00:13<09:46, 58.31it/s]

  8%|▊         | 2889/37084 [00:13<09:54, 57.53it/s]

  8%|▊         | 2895/37084 [00:13<10:15, 55.52it/s]

  8%|▊         | 2905/37084 [00:13<08:37, 66.06it/s]

  8%|▊         | 2912/37084 [00:13<08:34, 66.45it/s]

  8%|▊         | 2919/37084 [00:13<08:28, 67.15it/s]

  8%|▊         | 2927/37084 [00:14<08:18, 68.53it/s]

  8%|▊         | 2934/37084 [00:14<08:25, 67.57it/s]

  8%|▊         | 2941/37084 [00:14<08:34, 66.42it/s]

  8%|▊         | 2948/37084 [00:14<08:43, 65.20it/s]

  8%|▊         | 2957/37084 [00:14<08:03, 70.53it/s]

  8%|▊         | 2965/37084 [00:14<08:10, 69.60it/s]

  8%|▊         | 2972/37084 [00:14<09:09, 62.07it/s]

  8%|▊         | 2980/37084 [00:14<08:31, 66.72it/s]

  8%|▊         | 2987/37084 [00:14<08:54, 63.80it/s]

  8%|▊         | 2994/37084 [00:15<08:55, 63.72it/s]

  8%|▊         | 3004/37084 [00:15<08:04, 70.36it/s]

  8%|▊         | 3012/37084 [00:15<08:16, 68.61it/s]

  8%|▊         | 3020/37084 [00:15<07:56, 71.46it/s]

  8%|▊         | 3028/37084 [00:15<08:01, 70.78it/s]

  8%|▊         | 3036/37084 [00:15<07:56, 71.41it/s]

  8%|▊         | 3044/37084 [00:15<07:56, 71.37it/s]

  8%|▊         | 3052/37084 [00:15<07:49, 72.50it/s]

  8%|▊         | 3060/37084 [00:15<07:49, 72.47it/s]

  8%|▊         | 3068/37084 [00:16<07:58, 71.16it/s]

  8%|▊         | 3076/37084 [00:16<08:02, 70.52it/s]

  8%|▊         | 3084/37084 [00:16<09:05, 62.30it/s]

  8%|▊         | 3091/37084 [00:16<09:38, 58.76it/s]

  8%|▊         | 3098/37084 [00:16<09:57, 56.84it/s]

  8%|▊         | 3104/37084 [00:16<10:57, 51.64it/s]

  8%|▊         | 3110/37084 [00:16<10:55, 51.83it/s]

  9%|▊         | 3157/37084 [00:16<03:40, 153.77it/s]

  9%|▊         | 3208/37084 [00:17<02:17, 246.11it/s]

  9%|▉         | 3249/37084 [00:17<01:56, 290.41it/s]

  9%|▉         | 3304/37084 [00:17<01:33, 362.58it/s]

  9%|▉         | 3366/37084 [00:17<01:17, 435.64it/s]

  9%|▉         | 3428/37084 [00:17<01:09, 482.11it/s]

  9%|▉         | 3482/37084 [00:17<01:07, 498.61it/s]

 10%|▉         | 3533/37084 [00:17<01:08, 489.38it/s]

 10%|▉         | 3586/37084 [00:17<01:07, 499.54it/s]

 10%|▉         | 3638/37084 [00:17<01:06, 499.41it/s]

 10%|▉         | 3689/37084 [00:18<01:08, 489.10it/s]

 10%|█         | 3741/37084 [00:18<01:06, 497.99it/s]

 10%|█         | 3800/37084 [00:18<01:03, 524.04it/s]

 10%|█         | 3853/37084 [00:18<01:04, 518.64it/s]

 11%|█         | 3906/37084 [00:18<01:05, 505.38it/s]

 11%|█         | 3957/37084 [00:18<01:20, 412.79it/s]

 11%|█         | 4002/37084 [00:18<01:31, 361.08it/s]

 11%|█         | 4041/37084 [00:18<01:36, 341.84it/s]

 11%|█         | 4078/37084 [00:19<01:44, 315.69it/s]

 11%|█         | 4111/37084 [00:19<01:48, 302.60it/s]

 11%|█         | 4143/37084 [00:19<01:52, 293.43it/s]

 11%|█▏        | 4174/37084 [00:19<01:51, 294.40it/s]

 11%|█▏        | 4204/37084 [00:19<01:54, 288.13it/s]

 11%|█▏        | 4234/37084 [00:19<01:55, 283.57it/s]

 11%|█▏        | 4264/37084 [00:19<01:55, 284.08it/s]

 12%|█▏        | 4293/37084 [00:19<02:03, 264.75it/s]

 12%|█▏        | 4320/37084 [00:19<02:05, 261.67it/s]

 12%|█▏        | 4347/37084 [00:20<02:07, 256.68it/s]

 12%|█▏        | 4373/37084 [00:20<02:12, 246.27it/s]

 12%|█▏        | 4398/37084 [00:20<02:14, 243.14it/s]

 12%|█▏        | 4423/37084 [00:20<02:21, 230.05it/s]

 12%|█▏        | 4447/37084 [00:20<02:22, 229.06it/s]

 12%|█▏        | 4473/37084 [00:20<02:18, 235.83it/s]

 12%|█▏        | 4497/37084 [00:20<02:20, 232.62it/s]

 12%|█▏        | 4522/37084 [00:20<02:17, 237.53it/s]

 12%|█▏        | 4547/37084 [00:20<02:16, 237.62it/s]

 12%|█▏        | 4571/37084 [00:21<02:18, 235.01it/s]

 12%|█▏        | 4596/37084 [00:21<02:16, 238.38it/s]

 12%|█▏        | 4620/37084 [00:21<02:19, 233.52it/s]

 13%|█▎        | 4644/37084 [00:21<02:25, 222.83it/s]

 13%|█▎        | 4667/37084 [00:21<02:27, 220.48it/s]

 13%|█▎        | 4709/37084 [00:21<01:57, 276.19it/s]

 13%|█▎        | 4755/37084 [00:21<01:39, 325.61it/s]

 13%|█▎        | 4807/37084 [00:21<01:24, 381.57it/s]

 13%|█▎        | 4856/37084 [00:21<01:19, 407.41it/s]

 13%|█▎        | 4905/37084 [00:21<01:14, 430.72it/s]

 13%|█▎        | 4953/37084 [00:22<01:12, 441.79it/s]

 13%|█▎        | 4999/37084 [00:22<01:12, 443.82it/s]

 14%|█▎        | 5047/37084 [00:22<01:10, 453.20it/s]

 14%|█▎        | 5093/37084 [00:22<01:14, 431.74it/s]

 14%|█▍        | 5137/37084 [00:22<01:16, 417.51it/s]

 14%|█▍        | 5180/37084 [00:22<01:23, 380.29it/s]

 14%|█▍        | 5219/37084 [00:22<01:26, 366.79it/s]

 14%|█▍        | 5257/37084 [00:22<01:29, 357.42it/s]

 14%|█▍        | 5294/37084 [00:23<01:30, 350.73it/s]

 14%|█▍        | 5330/37084 [00:23<01:36, 328.05it/s]

 14%|█▍        | 5368/37084 [00:23<01:33, 337.51it/s]

 15%|█▍        | 5403/37084 [00:23<01:34, 336.06it/s]

 15%|█▍        | 5437/37084 [00:23<01:35, 330.85it/s]

 15%|█▍        | 5471/37084 [00:23<01:48, 292.67it/s]

 15%|█▍        | 5502/37084 [00:23<02:03, 255.78it/s]

 15%|█▍        | 5529/37084 [00:23<02:16, 231.57it/s]

 15%|█▍        | 5554/37084 [00:24<02:34, 204.38it/s]

 15%|█▌        | 5576/37084 [00:24<02:56, 178.26it/s]

 15%|█▌        | 5595/37084 [00:24<03:00, 174.61it/s]

 15%|█▌        | 5614/37084 [00:24<02:56, 178.12it/s]

 15%|█▌        | 5633/37084 [00:24<03:03, 171.79it/s]

 15%|█▌        | 5651/37084 [00:24<03:06, 168.81it/s]

 15%|█▌        | 5669/37084 [00:24<03:04, 170.21it/s]

 15%|█▌        | 5689/37084 [00:24<02:59, 175.11it/s]

 15%|█▌        | 5707/37084 [00:25<02:58, 175.54it/s]

 15%|█▌        | 5725/37084 [00:25<03:00, 173.38it/s]

 15%|█▌        | 5744/37084 [00:25<02:58, 175.64it/s]

 16%|█▌        | 5762/37084 [00:25<02:59, 174.58it/s]

 16%|█▌        | 5782/37084 [00:25<02:52, 181.84it/s]

 16%|█▌        | 5801/37084 [00:25<03:01, 172.55it/s]

 16%|█▌        | 5819/37084 [00:25<03:18, 157.37it/s]

 16%|█▌        | 5836/37084 [00:25<03:27, 150.94it/s]

 16%|█▌        | 5874/37084 [00:25<02:28, 209.92it/s]

 16%|█▌        | 5914/37084 [00:26<02:00, 258.07it/s]

 16%|█▌        | 5956/37084 [00:26<01:43, 301.76it/s]

 16%|█▌        | 6000/37084 [00:26<01:32, 335.97it/s]

 16%|█▋        | 6039/37084 [00:26<01:28, 351.28it/s]

 16%|█▋        | 6075/37084 [00:26<01:30, 343.33it/s]

 16%|█▋        | 6114/37084 [00:26<01:28, 351.63it/s]

 17%|█▋        | 6155/37084 [00:26<01:24, 367.95it/s]

 17%|█▋        | 6193/37084 [00:26<01:23, 369.76it/s]

 17%|█▋        | 6231/37084 [00:26<01:23, 367.84it/s]

 17%|█▋        | 6268/37084 [00:27<01:38, 313.41it/s]

 17%|█▋        | 6301/37084 [00:27<02:25, 212.21it/s]

 17%|█▋        | 6328/37084 [00:27<02:28, 207.27it/s]

 17%|█▋        | 6353/37084 [00:27<02:48, 182.41it/s]

 17%|█▋        | 6374/37084 [00:27<02:43, 187.60it/s]

 17%|█▋        | 6395/37084 [00:27<02:44, 186.61it/s]

 17%|█▋        | 6416/37084 [00:27<02:39, 191.97it/s]

 17%|█▋        | 6440/37084 [00:28<02:30, 204.04it/s]

 17%|█▋        | 6469/37084 [00:28<02:15, 226.14it/s]

 18%|█▊        | 6493/37084 [00:28<02:16, 223.60it/s]

 18%|█▊        | 6517/37084 [00:28<02:16, 223.92it/s]

 18%|█▊        | 6540/37084 [00:28<02:17, 222.03it/s]

 18%|█▊        | 6566/37084 [00:28<02:12, 229.79it/s]

 18%|█▊        | 6590/37084 [00:28<02:13, 228.64it/s]

 18%|█▊        | 6614/37084 [00:28<02:14, 226.95it/s]

 18%|█▊        | 6637/37084 [00:29<03:20, 151.73it/s]

 18%|█▊        | 6656/37084 [00:29<04:11, 121.07it/s]

 18%|█▊        | 6672/37084 [00:29<04:41, 108.11it/s]

 18%|█▊        | 6686/37084 [00:29<05:12, 97.16it/s]

 18%|█▊        | 6698/37084 [00:29<05:45, 87.94it/s]

 18%|█▊        | 6708/37084 [00:30<05:43, 88.31it/s]

 18%|█▊        | 6718/37084 [00:30<06:17, 80.52it/s]

 18%|█▊        | 6727/37084 [00:30<06:39, 76.07it/s]

 18%|█▊        | 6735/37084 [00:30<06:38, 76.09it/s]

 18%|█▊        | 6746/37084 [00:30<06:05, 83.11it/s]

 18%|█▊        | 6755/37084 [00:30<06:06, 82.65it/s]

 18%|█▊        | 6764/37084 [00:30<06:59, 72.33it/s]

 18%|█▊        | 6772/37084 [00:30<07:05, 71.19it/s]

 18%|█▊        | 6780/37084 [00:31<07:13, 69.88it/s]

 18%|█▊        | 6788/37084 [00:31<08:16, 60.99it/s]

 18%|█▊        | 6797/37084 [00:31<07:32, 66.92it/s]

 18%|█▊        | 6806/37084 [00:31<07:04, 71.27it/s]

 18%|█▊        | 6814/37084 [00:31<06:56, 72.71it/s]

 18%|█▊        | 6823/37084 [00:31<06:41, 75.32it/s]

 18%|█▊        | 6831/37084 [00:31<06:42, 75.17it/s]

 18%|█▊        | 6839/37084 [00:31<06:47, 74.24it/s]

 18%|█▊        | 6848/37084 [00:31<06:42, 75.13it/s]

 18%|█▊        | 6856/37084 [00:32<06:53, 73.08it/s]

 19%|█▊        | 6865/37084 [00:32<06:42, 75.11it/s]

 19%|█▊        | 6873/37084 [00:32<06:45, 74.58it/s]

 19%|█▊        | 6881/37084 [00:32<06:46, 74.24it/s]

 19%|█▊        | 6890/37084 [00:32<06:32, 76.96it/s]

 19%|█▊        | 6899/37084 [00:32<06:14, 80.61it/s]

 19%|█▊        | 6908/37084 [00:32<06:24, 78.58it/s]

 19%|█▊        | 6916/37084 [00:32<06:47, 74.00it/s]

 19%|█▊        | 6924/37084 [00:32<06:46, 74.18it/s]

 19%|█▊        | 6932/37084 [00:33<06:41, 75.15it/s]

 19%|█▊        | 6940/37084 [00:33<06:34, 76.51it/s]

 19%|█▊        | 6948/37084 [00:33<06:59, 71.78it/s]

 19%|█▉        | 6956/37084 [00:33<07:24, 67.72it/s]

 19%|█▉        | 6964/37084 [00:33<07:04, 70.95it/s]

 19%|█▉        | 6972/37084 [00:33<07:08, 70.24it/s]

 19%|█▉        | 6980/37084 [00:33<07:26, 67.38it/s]

 19%|█▉        | 6987/37084 [00:33<07:32, 66.50it/s]

 19%|█▉        | 6996/37084 [00:33<07:00, 71.63it/s]

 19%|█▉        | 7004/37084 [00:34<07:05, 70.73it/s]

 19%|█▉        | 7045/37084 [00:34<03:03, 163.30it/s]

 19%|█▉        | 7104/37084 [00:34<01:46, 282.82it/s]

 19%|█▉        | 7165/37084 [00:34<01:19, 375.69it/s]

 19%|█▉        | 7220/37084 [00:34<01:10, 421.00it/s]

 20%|█▉        | 7275/37084 [00:34<01:05, 457.69it/s]

 20%|█▉        | 7332/37084 [00:34<01:01, 483.97it/s]

 20%|█▉        | 7391/37084 [00:34<00:57, 513.50it/s]

 20%|██        | 7443/37084 [00:34<00:58, 506.85it/s]

 20%|██        | 7495/37084 [00:35<01:00, 486.91it/s]

 20%|██        | 7548/37084 [00:35<00:59, 499.16it/s]

 20%|██        | 7599/37084 [00:35<01:00, 487.32it/s]

 21%|██        | 7653/37084 [00:35<00:58, 501.60it/s]

 21%|██        | 7704/37084 [00:35<00:59, 495.86it/s]

 21%|██        | 7754/37084 [00:35<01:01, 480.04it/s]

 21%|██        | 7810/37084 [00:35<00:58, 502.81it/s]

 21%|██        | 7869/37084 [00:35<00:55, 526.99it/s]

 21%|██▏       | 7922/37084 [00:35<00:56, 518.47it/s]

 22%|██▏       | 7975/37084 [00:36<00:58, 500.38it/s]

 22%|██▏       | 8028/37084 [00:36<00:57, 503.38it/s]

 22%|██▏       | 8084/37084 [00:36<00:56, 517.41it/s]

 22%|██▏       | 8136/37084 [00:36<00:58, 491.80it/s]

 22%|██▏       | 8197/37084 [00:36<00:55, 523.33it/s]

 22%|██▏       | 8261/37084 [00:36<00:52, 554.15it/s]

 22%|██▏       | 8321/37084 [00:36<00:50, 566.82it/s]

 23%|██▎       | 8384/37084 [00:36<00:49, 578.76it/s]

 23%|██▎       | 8447/37084 [00:36<00:48, 589.43it/s]

 23%|██▎       | 8507/37084 [00:36<00:48, 592.34it/s]

 23%|██▎       | 8567/37084 [00:37<00:48, 582.69it/s]

 23%|██▎       | 8633/37084 [00:37<00:47, 599.61it/s]

 23%|██▎       | 8694/37084 [00:37<00:50, 562.28it/s]

 24%|██▎       | 8751/37084 [00:37<01:00, 465.40it/s]

 24%|██▍       | 8810/37084 [00:37<00:56, 496.19it/s]

 24%|██▍       | 8863/37084 [00:37<01:02, 451.89it/s]

 24%|██▍       | 8918/37084 [00:37<00:59, 475.59it/s]

 24%|██▍       | 8981/37084 [00:37<00:55, 510.44it/s]

 24%|██▍       | 9034/37084 [00:38<00:56, 494.88it/s]

 24%|██▍       | 9085/37084 [00:38<00:58, 475.73it/s]

 25%|██▍       | 9134/37084 [00:38<00:59, 471.20it/s]

 25%|██▍       | 9192/37084 [00:38<00:56, 495.15it/s]

 25%|██▍       | 9244/37084 [00:38<00:55, 501.74it/s]

 25%|██▌       | 9297/37084 [00:38<00:54, 509.52it/s]

 25%|██▌       | 9349/37084 [00:38<00:55, 495.59it/s]

 25%|██▌       | 9399/37084 [00:38<01:03, 436.04it/s]

 25%|██▌       | 9444/37084 [00:38<01:08, 404.54it/s]

 26%|██▌       | 9486/37084 [00:39<01:13, 376.58it/s]

 26%|██▌       | 9525/37084 [00:39<01:39, 276.80it/s]

 26%|██▌       | 9561/37084 [00:39<01:33, 294.02it/s]

 26%|██▌       | 9600/37084 [00:39<01:27, 315.73it/s]

 26%|██▌       | 9635/37084 [00:39<01:26, 316.68it/s]

 26%|██▌       | 9669/37084 [00:39<01:24, 322.60it/s]

 26%|██▌       | 9703/37084 [00:39<01:24, 323.92it/s]

 26%|██▋       | 9737/37084 [00:39<01:25, 321.61it/s]

 26%|██▋       | 9770/37084 [00:40<01:39, 273.28it/s]

 26%|██▋       | 9800/37084 [00:40<01:47, 252.94it/s]

 26%|██▋       | 9827/37084 [00:40<02:02, 222.29it/s]

 27%|██▋       | 9851/37084 [00:40<02:07, 213.15it/s]

 27%|██▋       | 9874/37084 [00:40<02:15, 201.06it/s]

 27%|██▋       | 9895/37084 [00:40<02:14, 202.84it/s]

 27%|██▋       | 9918/37084 [00:40<02:10, 208.37it/s]

 27%|██▋       | 9941/37084 [00:40<02:08, 210.97it/s]

 27%|██▋       | 9963/37084 [00:41<02:09, 209.84it/s]

 27%|██▋       | 9987/37084 [00:41<02:05, 215.43it/s]

 27%|██▋       | 10009/37084 [00:41<02:07, 212.02it/s]

 27%|██▋       | 10034/37084 [00:41<02:03, 218.43it/s]

 27%|██▋       | 10056/37084 [00:41<02:05, 215.88it/s]

 27%|██▋       | 10078/37084 [00:41<02:05, 214.59it/s]

 27%|██▋       | 10100/37084 [00:41<02:08, 210.18it/s]

 27%|██▋       | 10122/37084 [00:41<02:07, 211.88it/s]

 27%|██▋       | 10172/37084 [00:41<01:31, 294.75it/s]

 28%|██▊       | 10216/37084 [00:42<01:20, 332.23it/s]

 28%|██▊       | 10263/37084 [00:42<01:12, 371.93it/s]

 28%|██▊       | 10312/37084 [00:42<01:05, 406.54it/s]

 28%|██▊       | 10362/37084 [00:42<01:02, 428.67it/s]

 28%|██▊       | 10410/37084 [00:42<01:00, 442.32it/s]

 28%|██▊       | 10455/37084 [00:42<01:00, 443.49it/s]

 28%|██▊       | 10500/37084 [00:42<00:59, 445.31it/s]

 28%|██▊       | 10545/37084 [00:42<01:04, 412.84it/s]

 29%|██▊       | 10587/37084 [00:42<01:09, 379.13it/s]

 29%|██▊       | 10626/37084 [00:43<01:10, 375.86it/s]

 29%|██▉       | 10665/37084 [00:43<01:13, 358.69it/s]

 29%|██▉       | 10703/37084 [00:43<01:12, 362.12it/s]

 29%|██▉       | 10740/37084 [00:43<01:15, 350.56it/s]

 29%|██▉       | 10779/37084 [00:43<01:13, 358.91it/s]

 29%|██▉       | 10816/37084 [00:43<01:15, 345.79it/s]

 29%|██▉       | 10858/37084 [00:43<01:12, 363.49it/s]

 29%|██▉       | 10895/37084 [00:43<01:11, 365.14it/s]

 29%|██▉       | 10932/37084 [00:44<01:40, 260.31it/s]

 30%|██▉       | 10963/37084 [00:44<01:55, 226.32it/s]

 30%|██▉       | 10990/37084 [00:44<02:21, 184.23it/s]

 30%|██▉       | 11012/37084 [00:44<02:43, 159.90it/s]

 30%|██▉       | 11031/37084 [00:44<02:58, 145.62it/s]

 30%|██▉       | 11048/37084 [00:44<03:13, 134.39it/s]

 30%|██▉       | 11064/37084 [00:45<03:07, 139.06it/s]

 30%|██▉       | 11079/37084 [00:45<03:19, 130.55it/s]

 30%|██▉       | 11096/37084 [00:45<03:07, 138.82it/s]

 30%|██▉       | 11111/37084 [00:45<03:06, 139.59it/s]

 30%|███       | 11126/37084 [00:45<03:07, 138.32it/s]

 30%|███       | 11144/37084 [00:45<02:56, 147.21it/s]

 30%|███       | 11160/37084 [00:45<03:10, 136.35it/s]

 30%|███       | 11174/37084 [00:45<03:27, 124.93it/s]

 30%|███       | 11189/37084 [00:46<03:17, 130.99it/s]

 30%|███       | 11203/37084 [00:46<03:27, 124.46it/s]

 30%|███       | 11219/37084 [00:46<03:16, 131.47it/s]

 30%|███       | 11237/37084 [00:46<02:58, 144.42it/s]

 30%|███       | 11256/37084 [00:46<02:46, 154.96it/s]

 30%|███       | 11272/37084 [00:46<03:00, 142.96it/s]

 30%|███       | 11288/37084 [00:46<03:02, 141.16it/s]

 31%|███       | 11320/37084 [00:46<02:16, 188.73it/s]

 31%|███       | 11365/37084 [00:46<01:39, 257.73it/s]

 31%|███       | 11409/37084 [00:47<01:23, 307.35it/s]

 31%|███       | 11452/37084 [00:47<01:15, 341.50it/s]

 31%|███       | 11488/37084 [00:47<01:13, 345.99it/s]

 31%|███       | 11524/37084 [00:47<01:13, 348.18it/s]

 31%|███       | 11560/37084 [00:47<01:13, 348.79it/s]

 31%|███▏      | 11602/37084 [00:47<01:09, 367.62it/s]

 31%|███▏      | 11642/37084 [00:47<01:07, 374.84it/s]

 31%|███▏      | 11680/37084 [00:47<01:08, 370.94it/s]

 32%|███▏      | 11718/37084 [00:47<01:25, 295.88it/s]

 32%|███▏      | 11751/37084 [00:48<01:34, 268.54it/s]

 32%|███▏      | 11780/37084 [00:48<01:47, 235.18it/s]

 32%|███▏      | 11806/37084 [00:48<01:56, 216.25it/s]

 32%|███▏      | 11829/37084 [00:48<01:57, 214.53it/s]

 32%|███▏      | 11856/37084 [00:48<01:52, 223.79it/s]

 32%|███▏      | 11880/37084 [00:48<01:55, 217.99it/s]

 32%|███▏      | 11903/37084 [00:48<01:58, 213.13it/s]

 32%|███▏      | 11925/37084 [00:48<01:57, 214.67it/s]

 32%|███▏      | 11947/37084 [00:49<01:57, 213.34it/s]

 32%|███▏      | 11969/37084 [00:49<01:58, 212.51it/s]

 32%|███▏      | 11991/37084 [00:49<02:02, 204.60it/s]

 32%|███▏      | 12013/37084 [00:49<02:00, 208.13it/s]

 32%|███▏      | 12035/37084 [00:49<01:58, 211.41it/s]

 33%|███▎      | 12057/37084 [00:49<02:00, 207.64it/s]

 33%|███▎      | 12078/37084 [00:49<02:40, 155.80it/s]

 33%|███▎      | 12096/37084 [00:50<03:38, 114.24it/s]

 33%|███▎      | 12111/37084 [00:50<04:05, 101.66it/s]

 33%|███▎      | 12124/37084 [00:50<04:29, 92.55it/s]

 33%|███▎      | 12135/37084 [00:50<04:55, 84.47it/s]

 33%|███▎      | 12145/37084 [00:50<05:05, 81.54it/s]

 33%|███▎      | 12154/37084 [00:50<05:54, 70.38it/s]

 33%|███▎      | 12162/37084 [00:51<06:07, 67.78it/s]

 33%|███▎      | 12170/37084 [00:51<06:43, 61.72it/s]

 33%|███▎      | 12177/37084 [00:51<06:36, 62.79it/s]

 33%|███▎      | 12184/37084 [00:51<06:49, 60.85it/s]

 33%|███▎      | 12191/37084 [00:51<06:47, 61.02it/s]

 33%|███▎      | 12198/37084 [00:51<06:38, 62.44it/s]

 33%|███▎      | 12205/37084 [00:51<07:04, 58.58it/s]

 33%|███▎      | 12211/37084 [00:51<07:26, 55.70it/s]

 33%|███▎      | 12218/37084 [00:52<07:04, 58.52it/s]

 33%|███▎      | 12224/37084 [00:52<07:07, 58.15it/s]

 33%|███▎      | 12232/37084 [00:52<06:47, 60.98it/s]

 33%|███▎      | 12239/37084 [00:52<07:17, 56.85it/s]

 33%|███▎      | 12247/37084 [00:52<06:47, 60.95it/s]

 33%|███▎      | 12255/37084 [00:52<06:16, 65.94it/s]

 33%|███▎      | 12262/37084 [00:52<06:11, 66.90it/s]

 33%|███▎      | 12270/37084 [00:52<05:55, 69.89it/s]

 33%|███▎      | 12278/37084 [00:53<06:36, 62.58it/s]

 33%|███▎      | 12286/37084 [00:53<06:21, 65.00it/s]

 33%|███▎      | 12293/37084 [00:53<06:33, 62.99it/s]

 33%|███▎      | 12301/37084 [00:53<06:12, 66.62it/s]

 33%|███▎      | 12308/37084 [00:53<06:18, 65.46it/s]

 33%|███▎      | 12315/37084 [00:53<06:23, 64.59it/s]

 33%|███▎      | 12323/37084 [00:53<06:04, 67.92it/s]

 33%|███▎      | 12330/37084 [00:53<06:02, 68.36it/s]

 33%|███▎      | 12338/37084 [00:53<05:51, 70.50it/s]

 33%|███▎      | 12346/37084 [00:53<05:43, 72.09it/s]

 33%|███▎      | 12355/37084 [00:54<05:29, 75.08it/s]

 33%|███▎      | 12363/37084 [00:54<05:29, 75.02it/s]

 33%|███▎      | 12371/37084 [00:54<05:53, 69.85it/s]

 33%|███▎      | 12379/37084 [00:54<05:48, 70.80it/s]

 33%|███▎      | 12387/37084 [00:54<05:45, 71.46it/s]

 33%|███▎      | 12396/37084 [00:54<05:24, 76.15it/s]

 33%|███▎      | 12404/37084 [00:54<05:22, 76.53it/s]

 33%|███▎      | 12412/37084 [00:54<05:33, 74.03it/s]

 33%|███▎      | 12420/37084 [00:54<05:33, 74.03it/s]

 34%|███▎      | 12428/37084 [00:55<05:42, 72.00it/s]

 34%|███▎      | 12436/37084 [00:55<06:21, 64.56it/s]

 34%|███▎      | 12443/37084 [00:55<06:37, 61.99it/s]

 34%|███▎      | 12450/37084 [00:55<07:20, 55.96it/s]

 34%|███▎      | 12457/37084 [00:55<06:57, 59.05it/s]

 34%|███▎      | 12508/37084 [00:55<02:21, 173.84it/s]

 34%|███▍      | 12564/37084 [00:55<01:28, 275.70it/s]

 34%|███▍      | 12620/37084 [00:55<01:09, 353.84it/s]

 34%|███▍      | 12674/37084 [00:56<01:00, 405.45it/s]

 34%|███▍      | 12731/37084 [00:56<00:53, 450.99it/s]

 34%|███▍      | 12790/37084 [00:56<00:49, 486.52it/s]

 35%|███▍      | 12840/37084 [00:56<01:21, 297.02it/s]

 35%|███▍      | 12887/37084 [00:56<01:13, 330.09it/s]

 35%|███▍      | 12929/37084 [00:56<01:14, 326.38it/s]

 35%|███▍      | 12972/37084 [00:56<01:08, 349.49it/s]

 35%|███▌      | 13021/37084 [00:57<01:03, 379.51it/s]

 35%|███▌      | 13063/37084 [00:57<01:02, 383.49it/s]

 35%|███▌      | 13106/37084 [00:57<01:00, 393.09it/s]

 35%|███▌      | 13154/37084 [00:57<00:57, 414.15it/s]

 36%|███▌      | 13198/37084 [00:57<00:56, 420.75it/s]

 36%|███▌      | 13250/37084 [00:57<00:53, 442.46it/s]

 36%|███▌      | 13296/37084 [00:57<00:54, 439.13it/s]

 36%|███▌      | 13353/37084 [00:57<00:50, 469.60it/s]

 36%|███▌      | 13423/37084 [00:57<00:44, 528.65it/s]

 36%|███▋      | 13477/37084 [00:57<00:45, 514.52it/s]

 37%|███▋      | 13542/37084 [00:58<00:43, 544.74it/s]

 37%|███▋      | 13603/37084 [00:58<00:41, 562.56it/s]

 37%|███▋      | 13660/37084 [00:58<00:43, 535.94it/s]

 37%|███▋      | 13714/37084 [00:58<00:48, 482.33it/s]

 37%|███▋      | 13764/37084 [00:58<00:53, 439.76it/s]

 37%|███▋      | 13810/37084 [00:58<00:54, 429.74it/s]

 37%|███▋      | 13854/37084 [00:58<00:54, 423.59it/s]

 37%|███▋      | 13900/37084 [00:58<00:53, 431.58it/s]

 38%|███▊      | 13944/37084 [00:59<00:56, 409.14it/s]

 38%|███▊      | 13989/37084 [00:59<00:55, 412.70it/s]

 38%|███▊      | 14031/37084 [00:59<00:58, 396.95it/s]

 38%|███▊      | 14071/37084 [00:59<01:05, 349.02it/s]

 38%|███▊      | 14107/37084 [00:59<01:12, 318.13it/s]

 38%|███▊      | 14140/37084 [00:59<01:15, 303.80it/s]

 38%|███▊      | 14171/37084 [00:59<01:17, 296.40it/s]

 38%|███▊      | 14201/37084 [00:59<01:23, 273.96it/s]

 38%|███▊      | 14229/37084 [01:00<01:32, 247.97it/s]

 38%|███▊      | 14260/37084 [01:00<01:26, 262.47it/s]

 39%|███▊      | 14292/37084 [01:00<01:22, 277.09it/s]

 39%|███▊      | 14323/37084 [01:00<01:19, 285.84it/s]

 39%|███▊      | 14353/37084 [01:00<01:22, 277.15it/s]

 39%|███▉      | 14382/37084 [01:00<01:24, 268.16it/s]

 39%|███▉      | 14410/37084 [01:00<01:25, 264.09it/s]

 39%|███▉      | 14437/37084 [01:00<01:28, 255.00it/s]

 39%|███▉      | 14464/37084 [01:00<01:27, 257.21it/s]

 39%|███▉      | 14490/37084 [01:01<01:33, 242.04it/s]

 39%|███▉      | 14515/37084 [01:01<01:36, 234.35it/s]

 39%|███▉      | 14540/37084 [01:01<01:35, 235.68it/s]

 39%|███▉      | 14564/37084 [01:01<01:36, 233.19it/s]

 39%|███▉      | 14588/37084 [01:01<01:38, 227.96it/s]

 39%|███▉      | 14615/37084 [01:01<01:33, 239.44it/s]

 39%|███▉      | 14640/37084 [01:01<01:40, 224.40it/s]

 40%|███▉      | 14663/37084 [01:01<01:40, 223.19it/s]

 40%|███▉      | 14688/37084 [01:01<01:37, 230.12it/s]

 40%|███▉      | 14713/37084 [01:01<01:34, 235.77it/s]

 40%|███▉      | 14737/37084 [01:02<01:34, 236.93it/s]

 40%|███▉      | 14761/37084 [01:02<01:41, 220.82it/s]

 40%|███▉      | 14784/37084 [01:02<01:39, 223.36it/s]

 40%|███▉      | 14816/37084 [01:02<01:29, 248.71it/s]

 40%|████      | 14863/37084 [01:02<01:11, 312.16it/s]

 40%|████      | 14909/37084 [01:02<01:02, 354.61it/s]

 40%|████      | 14959/37084 [01:02<00:55, 395.57it/s]

 40%|████      | 15010/37084 [01:02<00:51, 427.20it/s]

 41%|████      | 15059/37084 [01:02<00:49, 445.32it/s]

 41%|████      | 15109/37084 [01:03<00:47, 461.11it/s]

 41%|████      | 15160/37084 [01:03<00:46, 475.51it/s]

 41%|████      | 15208/37084 [01:03<00:48, 454.89it/s]

 41%|████      | 15254/37084 [01:03<00:51, 427.30it/s]

 41%|████▏     | 15298/37084 [01:03<00:52, 412.04it/s]

 41%|████▏     | 15340/37084 [01:03<00:54, 400.92it/s]

 41%|████▏     | 15381/37084 [01:03<00:54, 399.87it/s]

 42%|████▏     | 15422/37084 [01:03<00:57, 377.91it/s]

 42%|████▏     | 15461/37084 [01:03<01:01, 353.91it/s]

 42%|████▏     | 15499/37084 [01:04<01:00, 359.70it/s]

 42%|████▏     | 15537/37084 [01:04<00:59, 361.01it/s]

 42%|████▏     | 15574/37084 [01:04<01:01, 352.07it/s]

 42%|████▏     | 15610/37084 [01:04<01:17, 276.93it/s]

 42%|████▏     | 15641/37084 [01:04<01:27, 246.00it/s]

 42%|████▏     | 15668/37084 [01:04<01:36, 222.55it/s]

 42%|████▏     | 15692/37084 [01:04<01:50, 193.48it/s]

 42%|████▏     | 15713/37084 [01:05<01:58, 180.14it/s]

 42%|████▏     | 15732/37084 [01:05<01:58, 179.91it/s]

 42%|████▏     | 15751/37084 [01:05<02:05, 169.58it/s]

 43%|████▎     | 15769/37084 [01:05<02:05, 169.35it/s]

 43%|████▎     | 15787/37084 [01:05<02:05, 169.87it/s]

 43%|████▎     | 15811/37084 [01:05<01:53, 188.04it/s]

 43%|████▎     | 15831/37084 [01:05<01:51, 190.94it/s]

 43%|████▎     | 15851/37084 [01:05<01:53, 186.51it/s]

 43%|████▎     | 15870/37084 [01:05<01:55, 183.93it/s]

 43%|████▎     | 15892/37084 [01:06<01:49, 193.59it/s]

 43%|████▎     | 15912/37084 [01:06<01:51, 190.71it/s]

 43%|████▎     | 15932/37084 [01:06<01:57, 180.00it/s]

 43%|████▎     | 15951/37084 [01:06<02:07, 165.91it/s]

 43%|████▎     | 15975/37084 [01:06<01:54, 185.09it/s]

 43%|████▎     | 16013/37084 [01:06<01:28, 238.14it/s]

 43%|████▎     | 16056/37084 [01:06<01:12, 290.55it/s]

 43%|████▎     | 16100/37084 [01:06<01:03, 328.58it/s]

 44%|████▎     | 16140/37084 [01:06<01:00, 348.58it/s]

 44%|████▎     | 16178/37084 [01:07<00:58, 356.46it/s]

 44%|████▎     | 16218/37084 [01:07<00:56, 369.17it/s]

 44%|████▍     | 16260/37084 [01:07<00:54, 384.06it/s]

 44%|████▍     | 16303/37084 [01:07<00:52, 394.89it/s]

 44%|████▍     | 16344/37084 [01:07<00:52, 397.72it/s]

 44%|████▍     | 16384/37084 [01:07<01:04, 320.05it/s]

 44%|████▍     | 16419/37084 [01:07<01:11, 288.94it/s]

 44%|████▍     | 16451/37084 [01:07<01:18, 261.77it/s]

 44%|████▍     | 16479/37084 [01:08<01:22, 249.75it/s]

 45%|████▍     | 16506/37084 [01:08<01:24, 244.75it/s]

 45%|████▍     | 16532/37084 [01:08<01:22, 248.45it/s]

 45%|████▍     | 16558/37084 [01:08<01:25, 240.80it/s]

 45%|████▍     | 16586/37084 [01:08<01:22, 248.01it/s]

 45%|████▍     | 16612/37084 [01:08<01:25, 240.52it/s]

 45%|████▍     | 16637/37084 [01:08<01:26, 236.01it/s]

 45%|████▍     | 16661/37084 [01:08<01:31, 223.27it/s]

 45%|████▌     | 16689/37084 [01:08<01:26, 236.73it/s]

 45%|████▌     | 16714/37084 [01:09<01:26, 235.66it/s]

 45%|████▌     | 16738/37084 [01:09<01:26, 234.91it/s]

 45%|████▌     | 16762/37084 [01:09<02:30, 135.01it/s]

 45%|████▌     | 16781/37084 [01:09<02:59, 112.88it/s]

 45%|████▌     | 16797/37084 [01:10<03:20, 101.36it/s]

 45%|████▌     | 16810/37084 [01:10<03:34, 94.43it/s]

 45%|████▌     | 16822/37084 [01:10<04:05, 82.57it/s]

 45%|████▌     | 16832/37084 [01:10<04:10, 80.89it/s]

 45%|████▌     | 16841/37084 [01:10<04:22, 76.98it/s]

 45%|████▌     | 16850/37084 [01:10<04:40, 72.25it/s]

 45%|████▌     | 16858/37084 [01:10<04:39, 72.46it/s]

 45%|████▌     | 16866/37084 [01:11<04:53, 68.89it/s]

 46%|████▌     | 16874/37084 [01:11<05:02, 66.83it/s]

 46%|████▌     | 16881/37084 [01:11<05:14, 64.27it/s]

 46%|████▌     | 16888/37084 [01:11<05:11, 64.74it/s]

 46%|████▌     | 16896/37084 [01:11<05:06, 65.89it/s]

 46%|████▌     | 16903/37084 [01:11<05:14, 64.18it/s]

 46%|████▌     | 16910/37084 [01:11<05:43, 58.79it/s]

 46%|████▌     | 16920/37084 [01:11<04:55, 68.23it/s]

 46%|████▌     | 16929/37084 [01:12<04:42, 71.31it/s]

 46%|████▌     | 16937/37084 [01:12<04:40, 71.71it/s]

 46%|████▌     | 16945/37084 [01:12<04:39, 72.14it/s]

 46%|████▌     | 16953/37084 [01:12<04:43, 71.02it/s]

 46%|████▌     | 16961/37084 [01:12<04:49, 69.46it/s]

 46%|████▌     | 16970/37084 [01:12<04:32, 73.84it/s]

 46%|████▌     | 16978/37084 [01:12<04:27, 75.27it/s]

 46%|████▌     | 16986/37084 [01:12<04:33, 73.53it/s]

 46%|████▌     | 16994/37084 [01:12<04:40, 71.62it/s]

 46%|████▌     | 17002/37084 [01:13<04:32, 73.81it/s]

 46%|████▌     | 17010/37084 [01:13<04:49, 69.35it/s]

 46%|████▌     | 17019/37084 [01:13<04:35, 72.70it/s]

 46%|████▌     | 17027/37084 [01:13<04:38, 72.02it/s]

 46%|████▌     | 17035/37084 [01:13<04:41, 71.32it/s]

 46%|████▌     | 17043/37084 [01:13<04:32, 73.58it/s]

 46%|████▌     | 17054/37084 [01:13<04:05, 81.50it/s]

 46%|████▌     | 17064/37084 [01:13<03:55, 85.14it/s]

 46%|████▌     | 17073/37084 [01:13<04:39, 71.60it/s]

 46%|████▌     | 17082/37084 [01:14<04:25, 75.34it/s]

 46%|████▌     | 17090/37084 [01:14<04:28, 74.55it/s]

 46%|████▌     | 17098/37084 [01:14<04:34, 72.77it/s]

 46%|████▌     | 17106/37084 [01:14<05:00, 66.38it/s]

 46%|████▌     | 17115/37084 [01:14<04:44, 70.27it/s]

 46%|████▌     | 17123/37084 [01:14<05:15, 63.25it/s]

 46%|████▌     | 17145/37084 [01:14<03:17, 101.05it/s]

 46%|████▋     | 17202/37084 [01:14<01:29, 221.68it/s]

 47%|████▋     | 17257/37084 [01:15<01:04, 307.11it/s]

 47%|████▋     | 17314/37084 [01:15<00:52, 378.20it/s]

 47%|████▋     | 17368/37084 [01:15<00:46, 423.63it/s]

 47%|████▋     | 17423/37084 [01:15<00:44, 437.52it/s]

 47%|████▋     | 17484/37084 [01:15<00:40, 480.81it/s]

 47%|████▋     | 17534/37084 [01:15<01:30, 216.49it/s]

 47%|████▋     | 17589/37084 [01:16<01:12, 267.44it/s]

 48%|████▊     | 17648/37084 [01:16<01:00, 322.61it/s]

 48%|████▊     | 17707/37084 [01:16<00:51, 375.99it/s]

 48%|████▊     | 17766/37084 [01:16<00:45, 422.97it/s]

 48%|████▊     | 17820/37084 [01:16<00:43, 446.20it/s]

 48%|████▊     | 17873/37084 [01:16<00:42, 454.96it/s]

 48%|████▊     | 17932/37084 [01:16<00:39, 489.21it/s]

 49%|████▊     | 17986/37084 [01:16<00:47, 400.87it/s]

 49%|████▊     | 18032/37084 [01:17<00:52, 362.05it/s]

 49%|████▊     | 18076/37084 [01:17<00:52, 362.78it/s]

 49%|████▉     | 18129/37084 [01:17<00:47, 401.79it/s]

 49%|████▉     | 18187/37084 [01:17<00:42, 446.33it/s]

 49%|████▉     | 18236/37084 [01:17<00:41, 457.74it/s]

 49%|████▉     | 18285/37084 [01:17<00:48, 385.48it/s]

 49%|████▉     | 18351/37084 [01:17<00:41, 451.46it/s]

 50%|████▉     | 18412/37084 [01:17<00:37, 491.42it/s]

 50%|████▉     | 18468/37084 [01:17<00:36, 507.17it/s]

 50%|████▉     | 18535/37084 [01:18<00:33, 549.69it/s]

 50%|█████     | 18597/37084 [01:18<00:32, 567.19it/s]

 50%|█████     | 18656/37084 [01:18<00:32, 572.86it/s]

 50%|█████     | 18715/37084 [01:18<00:34, 536.31it/s]

 51%|█████     | 18770/37084 [01:18<00:42, 429.64it/s]

 51%|█████     | 18817/37084 [01:18<00:48, 378.81it/s]

 51%|█████     | 18859/37084 [01:18<00:48, 376.06it/s]

 51%|█████     | 18899/37084 [01:19<00:50, 361.82it/s]

 51%|█████     | 18937/37084 [01:19<00:50, 361.69it/s]

 51%|█████     | 18975/37084 [01:19<00:50, 361.35it/s]

 51%|█████▏    | 19012/37084 [01:19<00:50, 357.45it/s]

 51%|█████▏    | 19049/37084 [01:19<00:51, 351.94it/s]

 51%|█████▏    | 19085/37084 [01:19<00:54, 327.83it/s]

 52%|█████▏    | 19119/37084 [01:19<01:02, 288.58it/s]

 52%|█████▏    | 19149/37084 [01:19<01:05, 275.78it/s]

 52%|█████▏    | 19178/37084 [01:19<01:13, 245.19it/s]

 52%|█████▏    | 19204/37084 [01:20<01:18, 227.81it/s]

 52%|█████▏    | 19228/37084 [01:20<01:18, 226.92it/s]

 52%|█████▏    | 19252/37084 [01:20<01:19, 224.50it/s]

 52%|█████▏    | 19279/37084 [01:20<01:16, 233.43it/s]

 52%|█████▏    | 19303/37084 [01:20<01:15, 234.22it/s]

 52%|█████▏    | 19327/37084 [01:20<01:15, 235.56it/s]

 52%|█████▏    | 19351/37084 [01:20<01:18, 225.58it/s]

 52%|█████▏    | 19374/37084 [01:20<01:18, 224.22it/s]

 52%|█████▏    | 19397/37084 [01:20<01:18, 225.74it/s]

 52%|█████▏    | 19420/37084 [01:21<01:18, 223.95it/s]

 52%|█████▏    | 19443/37084 [01:21<01:18, 225.55it/s]

 52%|█████▏    | 19466/37084 [01:21<01:20, 218.91it/s]

 53%|█████▎    | 19515/37084 [01:21<00:59, 293.17it/s]

 53%|█████▎    | 19558/37084 [01:21<00:52, 332.15it/s]

 53%|█████▎    | 19608/37084 [01:21<00:46, 378.28it/s]

 53%|█████▎    | 19664/37084 [01:21<00:40, 427.93it/s]

 53%|█████▎    | 19714/37084 [01:21<00:38, 446.95it/s]

 53%|█████▎    | 19765/37084 [01:21<00:37, 459.30it/s]

 53%|█████▎    | 19814/37084 [01:22<00:36, 468.26it/s]

 54%|█████▎    | 19861/37084 [01:22<00:37, 461.15it/s]

 54%|█████▎    | 19908/37084 [01:22<00:41, 410.23it/s]

 54%|█████▍    | 19951/37084 [01:22<00:42, 399.25it/s]

 54%|█████▍    | 19992/37084 [01:22<00:45, 371.69it/s]

 54%|█████▍    | 20030/37084 [01:22<00:47, 358.11it/s]

 54%|█████▍    | 20071/37084 [01:22<00:46, 367.18it/s]

 54%|█████▍    | 20109/37084 [01:22<00:46, 365.60it/s]

 54%|█████▍    | 20146/37084 [01:22<00:47, 353.37it/s]

 54%|█████▍    | 20182/37084 [01:23<00:48, 346.09it/s]

 55%|█████▍    | 20217/37084 [01:23<00:49, 337.72it/s]

 55%|█████▍    | 20251/37084 [01:23<00:54, 306.68it/s]

 55%|█████▍    | 20283/37084 [01:23<01:12, 232.90it/s]

 55%|█████▍    | 20310/37084 [01:23<01:23, 201.62it/s]

 55%|█████▍    | 20333/37084 [01:23<01:41, 165.15it/s]

 55%|█████▍    | 20352/37084 [01:24<01:52, 148.46it/s]

 55%|█████▍    | 20369/37084 [01:24<01:53, 147.23it/s]

 55%|█████▍    | 20385/37084 [01:24<02:14, 124.02it/s]

 55%|█████▌    | 20399/37084 [01:24<02:15, 123.01it/s]

 55%|█████▌    | 20413/37084 [01:24<02:21, 118.13it/s]

 55%|█████▌    | 20429/37084 [01:24<02:12, 125.31it/s]

 55%|█████▌    | 20445/37084 [01:24<02:05, 132.33it/s]

 55%|█████▌    | 20459/37084 [01:24<02:04, 133.21it/s]

 55%|█████▌    | 20475/37084 [01:25<01:59, 139.48it/s]

 55%|█████▌    | 20490/37084 [01:25<02:09, 128.54it/s]

 55%|█████▌    | 20504/37084 [01:25<02:09, 128.11it/s]

 55%|█████▌    | 20518/37084 [01:25<02:11, 125.63it/s]

 55%|█████▌    | 20535/37084 [01:25<02:05, 131.68it/s]

 55%|█████▌    | 20549/37084 [01:25<02:08, 128.47it/s]

 55%|█████▌    | 20562/37084 [01:25<02:08, 128.18it/s]

 55%|█████▌    | 20576/37084 [01:25<02:07, 129.92it/s]

 56%|█████▌    | 20590/37084 [01:26<02:04, 132.25it/s]

 56%|█████▌    | 20605/37084 [01:26<02:05, 130.96it/s]

 56%|█████▌    | 20619/37084 [01:26<02:10, 125.78it/s]

 56%|█████▌    | 20632/37084 [01:26<02:10, 125.75it/s]

 56%|█████▌    | 20677/37084 [01:26<01:16, 215.29it/s]

 56%|█████▌    | 20724/37084 [01:26<00:57, 283.60it/s]

 56%|█████▌    | 20771/37084 [01:26<00:48, 335.63it/s]

 56%|█████▌    | 20815/37084 [01:26<00:44, 364.72it/s]

 56%|█████▋    | 20860/37084 [01:26<00:42, 384.70it/s]

 56%|█████▋    | 20906/37084 [01:26<00:40, 400.80it/s]

 56%|█████▋    | 20948/37084 [01:27<00:39, 406.21it/s]

 57%|█████▋    | 20990/37084 [01:27<00:39, 410.05it/s]

 57%|█████▋    | 21032/37084 [01:27<00:44, 361.51it/s]

 57%|█████▋    | 21070/37084 [01:27<00:51, 311.99it/s]

 57%|█████▋    | 21104/37084 [01:27<00:55, 289.60it/s]

 57%|█████▋    | 21135/37084 [01:27<01:00, 264.90it/s]

 57%|█████▋    | 21163/37084 [01:27<01:04, 247.52it/s]

 57%|█████▋    | 21189/37084 [01:28<01:04, 246.70it/s]

 57%|█████▋    | 21215/37084 [01:28<01:03, 249.28it/s]

 57%|█████▋    | 21241/37084 [01:28<01:06, 237.38it/s]

 57%|█████▋    | 21269/37084 [01:28<01:04, 244.53it/s]

 57%|█████▋    | 21294/37084 [01:28<01:07, 232.26it/s]

 57%|█████▋    | 21320/37084 [01:28<01:05, 239.46it/s]

 58%|█████▊    | 21345/37084 [01:28<01:04, 242.25it/s]

 58%|█████▊    | 21370/37084 [01:28<01:04, 244.35it/s]

 58%|█████▊    | 21395/37084 [01:28<01:07, 234.03it/s]

 58%|█████▊    | 21419/37084 [01:29<01:23, 186.54it/s]

 58%|█████▊    | 21440/37084 [01:29<02:00, 130.04it/s]

 58%|█████▊    | 21457/37084 [01:29<02:16, 114.25it/s]

 58%|█████▊    | 21471/37084 [01:29<02:46, 93.50it/s]

 58%|█████▊    | 21483/37084 [01:30<03:01, 85.80it/s]

 58%|█████▊    | 21493/37084 [01:30<03:22, 77.01it/s]

 58%|█████▊    | 21502/37084 [01:30<03:39, 70.83it/s]

 58%|█████▊    | 21510/37084 [01:30<03:56, 65.81it/s]

 58%|█████▊    | 21517/37084 [01:30<04:03, 63.91it/s]

 58%|█████▊    | 21524/37084 [01:30<04:16, 60.75it/s]

 58%|█████▊    | 21531/37084 [01:30<04:10, 62.05it/s]

 58%|█████▊    | 21538/37084 [01:30<04:11, 61.82it/s]

 58%|█████▊    | 21545/37084 [01:31<04:07, 62.66it/s]

 58%|█████▊    | 21552/37084 [01:31<04:25, 58.60it/s]

 58%|█████▊    | 21559/37084 [01:31<04:16, 60.63it/s]

 58%|█████▊    | 21566/37084 [01:31<04:09, 62.20it/s]

 58%|█████▊    | 21573/37084 [01:31<04:05, 63.25it/s]

 58%|█████▊    | 21580/37084 [01:31<04:48, 53.80it/s]

 58%|█████▊    | 21589/37084 [01:31<04:07, 62.57it/s]

 58%|█████▊    | 21597/37084 [01:31<03:54, 66.01it/s]

 58%|█████▊    | 21604/37084 [01:32<03:57, 65.24it/s]

 58%|█████▊    | 21611/37084 [01:32<04:03, 63.64it/s]

 58%|█████▊    | 21618/37084 [01:32<04:09, 61.91it/s]

 58%|█████▊    | 21625/37084 [01:32<04:09, 61.96it/s]

 58%|█████▊    | 21632/37084 [01:32<04:19, 59.58it/s]

 58%|█████▊    | 21641/37084 [01:32<03:58, 64.74it/s]

 58%|█████▊    | 21648/37084 [01:32<04:07, 62.45it/s]

 58%|█████▊    | 21655/37084 [01:32<04:06, 62.65it/s]

 58%|█████▊    | 21662/37084 [01:32<03:59, 64.30it/s]

 58%|█████▊    | 21670/37084 [01:33<03:52, 66.25it/s]

 58%|█████▊    | 21677/37084 [01:33<04:04, 63.11it/s]

 58%|█████▊    | 21685/37084 [01:33<03:51, 66.54it/s]

 58%|█████▊    | 21693/37084 [01:33<03:49, 67.08it/s]

 59%|█████▊    | 21701/37084 [01:33<03:43, 68.93it/s]

 59%|█████▊    | 21708/37084 [01:33<03:45, 68.23it/s]

 59%|█████▊    | 21716/37084 [01:33<03:36, 70.93it/s]

 59%|█████▊    | 21724/37084 [01:33<03:37, 70.76it/s]

 59%|█████▊    | 21732/37084 [01:33<03:30, 72.87it/s]

 59%|█████▊    | 21740/37084 [01:34<03:36, 70.83it/s]

 59%|█████▊    | 21748/37084 [01:34<03:39, 69.80it/s]

 59%|█████▊    | 21756/37084 [01:34<03:40, 69.41it/s]

 59%|█████▊    | 21764/37084 [01:34<03:32, 71.93it/s]

 59%|█████▊    | 21772/37084 [01:34<03:47, 67.25it/s]

 59%|█████▊    | 21779/37084 [01:34<03:54, 65.14it/s]

 59%|█████▊    | 21786/37084 [01:34<04:02, 63.09it/s]

 59%|█████▉    | 21793/37084 [01:34<04:14, 60.11it/s]

 59%|█████▉    | 21805/37084 [01:35<03:21, 75.66it/s]

 59%|█████▉    | 21858/37084 [01:35<01:16, 198.41it/s]

 59%|█████▉    | 21913/37084 [01:35<00:51, 295.58it/s]

 59%|█████▉    | 21966/37084 [01:35<00:41, 361.28it/s]

 59%|█████▉    | 22017/37084 [01:35<00:37, 401.98it/s]

 60%|█████▉    | 22068/37084 [01:35<00:34, 433.00it/s]

 60%|█████▉    | 22123/37084 [01:35<00:32, 465.83it/s]

 60%|█████▉    | 22184/37084 [01:35<00:29, 505.83it/s]

 60%|█████▉    | 22238/37084 [01:35<00:29, 511.05it/s]

 60%|██████    | 22292/37084 [01:35<00:28, 517.01it/s]

 60%|██████    | 22346/37084 [01:36<00:28, 523.43it/s]

 60%|██████    | 22399/37084 [01:36<00:28, 517.76it/s]

 61%|██████    | 22454/37084 [01:36<00:27, 524.17it/s]

 61%|██████    | 22507/37084 [01:36<00:27, 524.67it/s]

 61%|██████    | 22561/37084 [01:36<00:27, 524.69it/s]

 61%|██████    | 22614/37084 [01:36<00:31, 457.56it/s]

 61%|██████    | 22667/37084 [01:36<00:30, 476.93it/s]

 61%|██████▏   | 22717/37084 [01:36<00:33, 427.37it/s]

 61%|██████▏   | 22774/37084 [01:36<00:30, 462.27it/s]

 62%|██████▏   | 22827/37084 [01:37<00:29, 479.05it/s]

 62%|██████▏   | 22885/37084 [01:37<00:28, 506.67it/s]

 62%|██████▏   | 22940/37084 [01:37<00:28, 504.15it/s]

 62%|██████▏   | 22999/37084 [01:37<00:26, 527.05it/s]

 62%|██████▏   | 23053/37084 [01:37<00:28, 485.72it/s]

 62%|██████▏   | 23104/37084 [01:37<00:28, 491.35it/s]

 62%|██████▏   | 23176/37084 [01:37<00:25, 548.91it/s]

 63%|██████▎   | 23242/37084 [01:37<00:23, 577.26it/s]

 63%|██████▎   | 23301/37084 [01:37<00:24, 572.49it/s]

 63%|██████▎   | 23359/37084 [01:38<00:25, 531.83it/s]

 63%|██████▎   | 23414/37084 [01:38<00:29, 459.96it/s]

 63%|██████▎   | 23463/37084 [01:38<00:31, 431.19it/s]

 63%|██████▎   | 23508/37084 [01:38<00:34, 396.46it/s]

 64%|██████▎   | 23549/37084 [01:38<00:35, 379.58it/s]

 64%|██████▎   | 23588/37084 [01:38<00:36, 371.30it/s]

 64%|██████▎   | 23626/37084 [01:38<00:36, 368.63it/s]

 64%|██████▍   | 23664/37084 [01:38<00:36, 367.23it/s]

 64%|██████▍   | 23702/37084 [01:39<00:36, 370.30it/s]

 64%|██████▍   | 23740/37084 [01:39<00:38, 350.10it/s]

 64%|██████▍   | 23776/37084 [01:39<00:43, 302.59it/s]

 64%|██████▍   | 23808/37084 [01:39<00:47, 280.43it/s]

 64%|██████▍   | 23837/37084 [01:39<00:54, 241.97it/s]

 64%|██████▍   | 23863/37084 [01:39<00:57, 228.25it/s]

 64%|██████▍   | 23887/37084 [01:39<01:00, 217.69it/s]

 64%|██████▍   | 23910/37084 [01:39<01:00, 217.22it/s]

 65%|██████▍   | 23934/37084 [01:40<00:58, 222.92it/s]

 65%|██████▍   | 23958/37084 [01:40<00:57, 227.44it/s]

 65%|██████▍   | 23982/37084 [01:40<00:59, 219.32it/s]

 65%|██████▍   | 24005/37084 [01:40<01:00, 216.70it/s]

 65%|██████▍   | 24027/37084 [01:40<01:01, 211.56it/s]

 65%|██████▍   | 24049/37084 [01:40<01:01, 211.15it/s]

 65%|██████▍   | 24071/37084 [01:40<01:02, 206.67it/s]

 65%|██████▍   | 24092/37084 [01:40<01:03, 205.16it/s]

 65%|██████▌   | 24113/37084 [01:40<01:03, 203.25it/s]

 65%|██████▌   | 24135/37084 [01:41<01:03, 204.18it/s]

 65%|██████▌   | 24180/37084 [01:41<00:47, 274.00it/s]

 65%|██████▌   | 24225/37084 [01:41<00:39, 323.74it/s]

 65%|██████▌   | 24271/37084 [01:41<00:35, 363.26it/s]

 66%|██████▌   | 24320/37084 [01:41<00:32, 396.62it/s]

 66%|██████▌   | 24368/37084 [01:41<00:30, 420.82it/s]

 66%|██████▌   | 24415/37084 [01:41<00:29, 434.95it/s]

 66%|██████▌   | 24464/37084 [01:41<00:28, 444.96it/s]

 66%|██████▌   | 24515/37084 [01:41<00:27, 462.18it/s]

 66%|██████▌   | 24562/37084 [01:41<00:28, 436.49it/s]

 66%|██████▋   | 24606/37084 [01:42<00:29, 423.43it/s]

 66%|██████▋   | 24649/37084 [01:42<00:30, 406.14it/s]

 67%|██████▋   | 24690/37084 [01:42<00:32, 383.97it/s]

 67%|██████▋   | 24731/37084 [01:42<00:32, 385.98it/s]

 67%|██████▋   | 24770/37084 [01:42<00:32, 374.31it/s]

 67%|██████▋   | 24808/37084 [01:42<00:33, 362.07it/s]

 67%|██████▋   | 24849/37084 [01:42<00:32, 372.68it/s]

 67%|██████▋   | 24887/37084 [01:42<00:34, 357.48it/s]

 67%|██████▋   | 24923/37084 [01:43<00:42, 287.76it/s]

 67%|██████▋   | 24954/37084 [01:43<00:53, 226.45it/s]

 67%|██████▋   | 24980/37084 [01:43<01:01, 197.17it/s]

 67%|██████▋   | 25003/37084 [01:43<01:12, 167.45it/s]

 67%|██████▋   | 25022/37084 [01:43<01:25, 141.43it/s]

 68%|██████▊   | 25038/37084 [01:44<01:29, 135.30it/s]

 68%|██████▊   | 25053/37084 [01:44<01:34, 127.31it/s]

 68%|██████▊   | 25067/37084 [01:44<01:35, 125.96it/s]

 68%|██████▊   | 25080/37084 [01:44<01:35, 126.28it/s]

 68%|██████▊   | 25093/37084 [01:44<01:34, 126.94it/s]

 68%|██████▊   | 25107/37084 [01:44<01:32, 130.18it/s]

 68%|██████▊   | 25121/37084 [01:44<01:32, 128.77it/s]

 68%|██████▊   | 25135/37084 [01:44<01:34, 126.62it/s]

 68%|██████▊   | 25151/37084 [01:44<01:28, 135.49it/s]

 68%|██████▊   | 25165/37084 [01:45<01:33, 127.74it/s]

 68%|██████▊   | 25178/37084 [01:45<01:36, 123.44it/s]

 68%|██████▊   | 25192/37084 [01:45<01:33, 127.25it/s]

 68%|██████▊   | 25207/37084 [01:45<01:31, 130.18it/s]

 68%|██████▊   | 25221/37084 [01:45<01:30, 130.96it/s]

 68%|██████▊   | 25236/37084 [01:45<01:27, 135.95it/s]

 68%|██████▊   | 25250/37084 [01:45<01:28, 133.12it/s]

 68%|██████▊   | 25267/37084 [01:45<01:22, 143.27it/s]

 68%|██████▊   | 25282/37084 [01:45<01:32, 127.12it/s]

 68%|██████▊   | 25297/37084 [01:46<01:28, 133.18it/s]

 68%|██████▊   | 25326/37084 [01:46<01:06, 176.25it/s]

 68%|██████▊   | 25367/37084 [01:46<00:48, 242.07it/s]

 69%|██████▊   | 25412/37084 [01:46<00:38, 301.73it/s]

 69%|██████▊   | 25455/37084 [01:46<00:34, 338.98it/s]

 69%|██████▉   | 25497/37084 [01:46<00:31, 362.67it/s]

 69%|██████▉   | 25537/37084 [01:46<00:30, 373.65it/s]

 69%|██████▉   | 25575/37084 [01:46<00:30, 374.72it/s]

 69%|██████▉   | 25620/37084 [01:46<00:29, 391.73it/s]

 69%|██████▉   | 25662/37084 [01:46<00:28, 396.59it/s]

 69%|██████▉   | 25702/37084 [01:47<00:28, 394.94it/s]

 69%|██████▉   | 25742/37084 [01:47<00:35, 318.41it/s]

 70%|██████▉   | 25777/37084 [01:47<00:41, 275.34it/s]

 70%|██████▉   | 25808/37084 [01:47<00:49, 227.37it/s]

 70%|██████▉   | 25834/37084 [01:47<00:51, 216.43it/s]

 70%|██████▉   | 25858/37084 [01:47<00:51, 218.85it/s]

 70%|██████▉   | 25882/37084 [01:47<00:50, 222.86it/s]

 70%|██████▉   | 25911/37084 [01:48<00:47, 237.67it/s]

 70%|██████▉   | 25936/37084 [01:48<00:47, 234.66it/s]

 70%|███████   | 25961/37084 [01:48<00:51, 218.05it/s]

 70%|███████   | 25985/37084 [01:48<00:49, 223.25it/s]

 70%|███████   | 26008/37084 [01:48<00:51, 213.20it/s]

 70%|███████   | 26033/37084 [01:48<00:50, 220.15it/s]

 70%|███████   | 26056/37084 [01:48<00:49, 222.68it/s]

 70%|███████   | 26079/37084 [01:48<00:50, 217.83it/s]

 70%|███████   | 26101/37084 [01:49<01:27, 126.05it/s]

 70%|███████   | 26119/37084 [01:49<01:41, 108.03it/s]

 70%|███████   | 26134/37084 [01:49<01:59, 91.34it/s]

 71%|███████   | 26146/37084 [01:49<02:13, 81.87it/s]

 71%|███████   | 26157/37084 [01:50<02:26, 74.78it/s]

 71%|███████   | 26166/37084 [01:50<02:32, 71.77it/s]

 71%|███████   | 26174/37084 [01:50<02:44, 66.29it/s]

 71%|███████   | 26182/37084 [01:50<02:51, 63.61it/s]

 71%|███████   | 26189/37084 [01:50<02:59, 60.83it/s]

 71%|███████   | 26196/37084 [01:50<03:09, 57.41it/s]

 71%|███████   | 26203/37084 [01:50<03:05, 58.68it/s]

 71%|███████   | 26209/37084 [01:51<03:05, 58.73it/s]

 71%|███████   | 26215/37084 [01:51<03:08, 57.64it/s]

 71%|███████   | 26221/37084 [01:51<03:18, 54.64it/s]

 71%|███████   | 26227/37084 [01:51<03:15, 55.55it/s]

 71%|███████   | 26234/37084 [01:51<03:04, 58.71it/s]

 71%|███████   | 26240/37084 [01:51<03:03, 59.06it/s]

 71%|███████   | 26246/37084 [01:51<03:05, 58.56it/s]

 71%|███████   | 26252/37084 [01:51<03:06, 58.10it/s]

 71%|███████   | 26260/37084 [01:51<02:49, 63.83it/s]

 71%|███████   | 26268/37084 [01:52<02:42, 66.70it/s]

 71%|███████   | 26275/37084 [01:52<02:41, 67.08it/s]

 71%|███████   | 26282/37084 [01:52<02:40, 67.31it/s]

 71%|███████   | 26289/37084 [01:52<03:02, 59.25it/s]

 71%|███████   | 26296/37084 [01:52<03:05, 58.04it/s]

 71%|███████   | 26302/37084 [01:52<03:14, 55.58it/s]

 71%|███████   | 26308/37084 [01:52<03:10, 56.71it/s]

 71%|███████   | 26316/37084 [01:52<02:54, 61.65it/s]

 71%|███████   | 26323/37084 [01:52<02:58, 60.44it/s]

 71%|███████   | 26330/37084 [01:53<02:50, 62.99it/s]

 71%|███████   | 26338/37084 [01:53<02:40, 66.81it/s]

 71%|███████   | 26345/37084 [01:53<02:51, 62.64it/s]

 71%|███████   | 26352/37084 [01:53<02:55, 61.14it/s]

 71%|███████   | 26359/37084 [01:53<02:52, 62.35it/s]

 71%|███████   | 26366/37084 [01:53<02:48, 63.54it/s]

 71%|███████   | 26374/37084 [01:53<02:44, 65.10it/s]

 71%|███████   | 26381/37084 [01:53<02:46, 64.39it/s]

 71%|███████   | 26389/37084 [01:53<02:40, 66.82it/s]

 71%|███████   | 26396/37084 [01:54<02:52, 61.96it/s]

 71%|███████   | 26405/37084 [01:54<02:47, 63.80it/s]

 71%|███████   | 26412/37084 [01:54<02:58, 59.62it/s]

 71%|███████   | 26419/37084 [01:54<03:05, 57.34it/s]

 71%|███████▏  | 26426/37084 [01:54<02:59, 59.46it/s]

 71%|███████▏  | 26433/37084 [01:54<02:53, 61.32it/s]

 71%|███████▏  | 26440/37084 [01:54<02:57, 59.91it/s]

 71%|███████▏  | 26447/37084 [01:54<03:08, 56.58it/s]

 71%|███████▏  | 26454/37084 [01:55<03:01, 58.50it/s]

 71%|███████▏  | 26460/37084 [01:55<03:02, 58.15it/s]

 71%|███████▏  | 26467/37084 [01:55<02:54, 60.81it/s]

 71%|███████▏  | 26501/37084 [01:55<01:16, 137.89it/s]

 72%|███████▏  | 26558/37084 [01:55<00:40, 258.98it/s]

 72%|███████▏  | 26608/37084 [01:55<00:31, 328.02it/s]

 72%|███████▏  | 26666/37084 [01:55<00:26, 395.60it/s]

 72%|███████▏  | 26726/37084 [01:55<00:22, 454.04it/s]

 72%|███████▏  | 26782/37084 [01:55<00:21, 483.60it/s]

 72%|███████▏  | 26841/37084 [01:55<00:20, 506.85it/s]

 73%|███████▎  | 26893/37084 [01:56<00:21, 480.11it/s]

 73%|███████▎  | 26942/37084 [01:56<00:21, 461.25it/s]

 73%|███████▎  | 26989/37084 [01:56<00:23, 435.81it/s]

 73%|███████▎  | 27039/37084 [01:56<00:22, 452.82it/s]

 73%|███████▎  | 27085/37084 [01:56<00:22, 437.23it/s]

 73%|███████▎  | 27130/37084 [01:56<00:22, 440.55it/s]

 73%|███████▎  | 27175/37084 [01:56<00:25, 390.54it/s]

 73%|███████▎  | 27216/37084 [01:56<00:24, 395.55it/s]

 74%|███████▎  | 27257/37084 [01:57<00:24, 398.03it/s]

 74%|███████▎  | 27298/37084 [01:57<00:28, 343.35it/s]

 74%|███████▎  | 27334/37084 [01:57<00:29, 326.10it/s]

 74%|███████▍  | 27368/37084 [01:57<00:30, 317.02it/s]

 74%|███████▍  | 27401/37084 [01:57<00:30, 315.52it/s]

 74%|███████▍  | 27434/37084 [01:57<00:31, 308.93it/s]

 74%|███████▍  | 27466/37084 [01:57<00:32, 292.55it/s]

 74%|███████▍  | 27497/37084 [01:57<00:32, 295.61it/s]

 74%|███████▍  | 27528/37084 [01:57<00:31, 299.21it/s]

 74%|███████▍  | 27562/37084 [01:58<00:30, 310.61it/s]

 74%|███████▍  | 27594/37084 [01:58<00:31, 304.85it/s]

 74%|███████▍  | 27625/37084 [01:58<00:33, 282.40it/s]

 75%|███████▍  | 27654/37084 [01:58<00:36, 260.65it/s]

 75%|███████▍  | 27681/37084 [01:58<00:37, 253.14it/s]

 75%|███████▍  | 27707/37084 [01:58<00:37, 248.22it/s]

 75%|███████▍  | 27733/37084 [01:58<00:39, 236.53it/s]

 75%|███████▍  | 27757/37084 [01:58<00:40, 230.24it/s]

 75%|███████▍  | 27781/37084 [01:59<00:42, 219.07it/s]

 75%|███████▍  | 27804/37084 [01:59<00:41, 221.45it/s]

 75%|███████▌  | 27828/37084 [01:59<00:41, 223.65it/s]

 75%|███████▌  | 27851/37084 [01:59<00:41, 220.11it/s]

 75%|███████▌  | 27875/37084 [01:59<00:40, 225.00it/s]

 75%|███████▌  | 27898/37084 [01:59<00:40, 225.23it/s]

 75%|███████▌  | 27921/37084 [01:59<00:41, 223.25it/s]

 75%|███████▌  | 27946/37084 [01:59<00:39, 230.93it/s]

 75%|███████▌  | 27970/37084 [01:59<00:39, 230.24it/s]

 75%|███████▌  | 27994/37084 [01:59<00:40, 222.36it/s]

 76%|███████▌  | 28017/37084 [02:00<00:41, 216.13it/s]

 76%|███████▌  | 28042/37084 [02:00<00:40, 223.92it/s]

 76%|███████▌  | 28070/37084 [02:00<00:37, 239.59it/s]

 76%|███████▌  | 28103/37084 [02:00<00:34, 262.92it/s]

 76%|███████▌  | 28130/37084 [02:00<00:34, 262.91it/s]

 76%|███████▌  | 28159/37084 [02:00<00:33, 268.03it/s]

 76%|███████▌  | 28186/37084 [02:00<00:33, 267.14it/s]

 76%|███████▌  | 28214/37084 [02:00<00:32, 270.71it/s]

 76%|███████▌  | 28245/37084 [02:00<00:31, 279.20it/s]

 76%|███████▋  | 28279/37084 [02:01<00:29, 294.40it/s]

 76%|███████▋  | 28312/37084 [02:01<00:28, 304.84it/s]

 76%|███████▋  | 28345/37084 [02:01<00:28, 311.27it/s]

 77%|███████▋  | 28377/37084 [02:01<00:28, 304.22it/s]

 77%|███████▋  | 28408/37084 [02:01<00:29, 293.21it/s]

 77%|███████▋  | 28438/37084 [02:01<00:32, 266.23it/s]

 77%|███████▋  | 28466/37084 [02:01<00:34, 250.88it/s]

 77%|███████▋  | 28492/37084 [02:01<00:34, 249.66it/s]

 77%|███████▋  | 28518/37084 [02:01<00:37, 231.32it/s]

 77%|███████▋  | 28542/37084 [02:02<00:37, 227.15it/s]

 77%|███████▋  | 28565/37084 [02:02<00:38, 221.03it/s]

 77%|███████▋  | 28588/37084 [02:02<00:40, 211.39it/s]

 77%|███████▋  | 28614/37084 [02:02<00:37, 223.75it/s]

 77%|███████▋  | 28637/37084 [02:02<00:40, 206.46it/s]

 77%|███████▋  | 28663/37084 [02:02<00:38, 220.60it/s]

 77%|███████▋  | 28688/37084 [02:02<00:37, 225.62it/s]

 77%|███████▋  | 28712/37084 [02:02<00:36, 228.88it/s]

 77%|███████▋  | 28736/37084 [02:02<00:36, 228.45it/s]

 78%|███████▊  | 28760/37084 [02:03<00:37, 224.26it/s]

 78%|███████▊  | 28784/37084 [02:03<00:36, 225.60it/s]

 78%|███████▊  | 28807/37084 [02:03<00:37, 220.29it/s]

 78%|███████▊  | 28852/37084 [02:03<00:28, 284.16it/s]

 78%|███████▊  | 28896/37084 [02:03<00:25, 325.80it/s]

 78%|███████▊  | 28942/37084 [02:03<00:22, 362.59it/s]

 78%|███████▊  | 28987/37084 [02:03<00:21, 382.85it/s]

 78%|███████▊  | 29032/37084 [02:03<00:20, 402.28it/s]

 78%|███████▊  | 29075/37084 [02:03<00:19, 409.56it/s]

 79%|███████▊  | 29120/37084 [02:03<00:19, 417.27it/s]

 79%|███████▊  | 29167/37084 [02:04<00:18, 430.65it/s]

 79%|███████▉  | 29211/37084 [02:04<00:19, 413.58it/s]

 79%|███████▉  | 29253/37084 [02:04<00:19, 396.87it/s]

 79%|███████▉  | 29293/37084 [02:04<00:21, 363.31it/s]

 79%|███████▉  | 29330/37084 [02:04<00:22, 349.27it/s]

 79%|███████▉  | 29366/37084 [02:04<00:22, 339.74it/s]

 79%|███████▉  | 29403/37084 [02:04<00:22, 346.67it/s]

 79%|███████▉  | 29440/37084 [02:04<00:21, 349.43it/s]

 79%|███████▉  | 29476/37084 [02:04<00:22, 336.58it/s]

 80%|███████▉  | 29516/37084 [02:05<00:21, 349.55it/s]

 80%|███████▉  | 29552/37084 [02:05<00:21, 347.39it/s]

 80%|███████▉  | 29587/37084 [02:05<00:23, 312.98it/s]

 80%|███████▉  | 29619/37084 [02:05<00:29, 249.25it/s]

 80%|███████▉  | 29647/37084 [02:05<00:32, 230.74it/s]

 80%|████████  | 29672/37084 [02:05<00:37, 198.45it/s]

 80%|████████  | 29694/37084 [02:06<00:42, 173.63it/s]

 80%|████████  | 29713/37084 [02:06<00:44, 165.44it/s]

 80%|████████  | 29731/37084 [02:06<00:47, 155.64it/s]

 80%|████████  | 29748/37084 [02:06<00:46, 158.52it/s]

 80%|████████  | 29766/37084 [02:06<00:44, 163.35it/s]

 80%|████████  | 29786/37084 [02:06<00:42, 170.97it/s]

 80%|████████  | 29804/37084 [02:06<00:44, 163.48it/s]

 80%|████████  | 29821/37084 [02:06<00:43, 165.18it/s]

 80%|████████  | 29840/37084 [02:06<00:42, 170.36it/s]

 81%|████████  | 29858/37084 [02:07<00:44, 164.07it/s]

 81%|████████  | 29878/37084 [02:07<00:41, 171.92it/s]

 81%|████████  | 29896/37084 [02:07<00:41, 172.25it/s]

 81%|████████  | 29914/37084 [02:07<00:41, 172.89it/s]

 81%|████████  | 29932/37084 [02:07<00:43, 164.04it/s]

 81%|████████  | 29949/37084 [02:07<00:46, 152.49it/s]

 81%|████████  | 29965/37084 [02:07<00:51, 139.39it/s]

 81%|████████  | 29981/37084 [02:07<00:49, 144.65it/s]

 81%|████████  | 30010/37084 [02:07<00:38, 182.09it/s]

 81%|████████  | 30039/37084 [02:08<00:33, 210.79it/s]

 81%|████████  | 30071/37084 [02:08<00:29, 238.24it/s]

 81%|████████  | 30102/37084 [02:08<00:27, 257.72it/s]

 81%|████████▏ | 30143/37084 [02:08<00:23, 298.23it/s]

 81%|████████▏ | 30180/37084 [02:08<00:22, 313.08it/s]

 81%|████████▏ | 30215/37084 [02:08<00:21, 323.35it/s]

 82%|████████▏ | 30253/37084 [02:08<00:20, 335.25it/s]

 82%|████████▏ | 30291/37084 [02:08<00:19, 348.09it/s]

 82%|████████▏ | 30330/37084 [02:08<00:19, 355.22it/s]

 82%|████████▏ | 30366/37084 [02:09<00:19, 343.27it/s]

 82%|████████▏ | 30401/37084 [02:09<00:22, 294.30it/s]

 82%|████████▏ | 30432/37084 [02:09<00:24, 276.96it/s]

 82%|████████▏ | 30461/37084 [02:09<00:27, 241.24it/s]

 82%|████████▏ | 30487/37084 [02:09<00:29, 224.07it/s]

 82%|████████▏ | 30511/37084 [02:09<00:29, 220.17it/s]

 82%|████████▏ | 30534/37084 [02:09<00:30, 217.73it/s]

 82%|████████▏ | 30557/37084 [02:09<00:30, 215.65it/s]

 82%|████████▏ | 30579/37084 [02:10<00:32, 201.40it/s]

 83%|████████▎ | 30602/37084 [02:10<00:31, 206.01it/s]

 83%|████████▎ | 30623/37084 [02:10<00:32, 201.83it/s]

 83%|████████▎ | 30645/37084 [02:10<00:31, 203.31it/s]

 83%|████████▎ | 30666/37084 [02:10<00:31, 202.12it/s]

 83%|████████▎ | 30694/37084 [02:10<00:28, 220.95it/s]

 83%|████████▎ | 30717/37084 [02:10<00:29, 213.24it/s]

 83%|████████▎ | 30740/37084 [02:10<00:29, 217.81it/s]

 83%|████████▎ | 30762/37084 [02:11<00:39, 160.18it/s]

 83%|████████▎ | 30781/37084 [02:11<00:53, 117.46it/s]

 83%|████████▎ | 30796/37084 [02:11<00:59, 105.91it/s]

 83%|████████▎ | 30809/37084 [02:11<01:06, 94.14it/s]

 83%|████████▎ | 30820/37084 [02:11<01:09, 89.62it/s]

 83%|████████▎ | 30830/37084 [02:12<01:13, 84.90it/s]

 83%|████████▎ | 30840/37084 [02:12<01:21, 76.59it/s]

 83%|████████▎ | 30849/37084 [02:12<01:26, 72.06it/s]

 83%|████████▎ | 30857/37084 [02:12<01:31, 68.25it/s]

 83%|████████▎ | 30864/37084 [02:12<01:31, 67.62it/s]

 83%|████████▎ | 30873/37084 [02:12<01:27, 70.97it/s]

 83%|████████▎ | 30881/37084 [02:12<01:27, 70.66it/s]

 83%|████████▎ | 30889/37084 [02:12<01:27, 70.84it/s]

 83%|████████▎ | 30897/37084 [02:13<01:39, 62.21it/s]

 83%|████████▎ | 30905/37084 [02:13<01:35, 64.86it/s]

 83%|████████▎ | 30912/37084 [02:13<01:34, 65.65it/s]

 83%|████████▎ | 30919/37084 [02:13<01:43, 59.45it/s]

 83%|████████▎ | 30927/37084 [02:13<01:36, 63.72it/s]

 83%|████████▎ | 30935/37084 [02:13<01:33, 66.01it/s]

 83%|████████▎ | 30942/37084 [02:13<01:34, 64.96it/s]

 83%|████████▎ | 30954/37084 [02:13<01:21, 75.41it/s]

 83%|████████▎ | 30962/37084 [02:14<01:23, 73.39it/s]

 84%|████████▎ | 30971/37084 [02:14<01:21, 75.01it/s]

 84%|████████▎ | 30979/37084 [02:14<01:20, 75.72it/s]

 84%|████████▎ | 30987/37084 [02:14<01:21, 74.59it/s]

 84%|████████▎ | 30995/37084 [02:14<01:21, 75.04it/s]

 84%|████████▎ | 31003/37084 [02:14<01:19, 76.32it/s]

 84%|████████▎ | 31012/37084 [02:14<01:16, 79.07it/s]

 84%|████████▎ | 31020/37084 [02:14<01:19, 76.60it/s]

 84%|████████▎ | 31028/37084 [02:14<01:20, 75.26it/s]

 84%|████████▎ | 31038/37084 [02:14<01:14, 81.11it/s]

 84%|████████▎ | 31047/37084 [02:15<01:22, 73.52it/s]

 84%|████████▎ | 31056/37084 [02:15<01:18, 76.75it/s]

 84%|████████▍ | 31066/37084 [02:15<01:13, 81.33it/s]

 84%|████████▍ | 31075/37084 [02:15<01:15, 80.03it/s]

 84%|████████▍ | 31084/37084 [02:15<01:19, 75.85it/s]

 84%|████████▍ | 31092/37084 [02:15<01:17, 76.93it/s]

 84%|████████▍ | 31100/37084 [02:15<01:18, 76.35it/s]

 84%|████████▍ | 31108/37084 [02:15<01:17, 76.62it/s]

 84%|████████▍ | 31116/37084 [02:16<01:22, 72.42it/s]

 84%|████████▍ | 31124/37084 [02:16<01:26, 68.56it/s]

 84%|████████▍ | 31131/37084 [02:16<01:27, 68.07it/s]

 84%|████████▍ | 31138/37084 [02:16<01:26, 68.54it/s]

 84%|████████▍ | 31187/37084 [02:16<00:32, 183.63it/s]

 84%|████████▍ | 31246/37084 [02:16<00:19, 295.68it/s]

 84%|████████▍ | 31303/37084 [02:16<00:15, 370.70it/s]

 85%|████████▍ | 31357/37084 [02:16<00:13, 419.40it/s]

 85%|████████▍ | 31409/37084 [02:16<00:13, 429.33it/s]

 85%|████████▍ | 31463/37084 [02:16<00:12, 458.65it/s]

 85%|████████▌ | 31522/37084 [02:17<00:11, 496.41it/s]

 85%|████████▌ | 31573/37084 [02:17<00:11, 486.30it/s]

 85%|████████▌ | 31622/37084 [02:17<00:12, 437.20it/s]

 85%|████████▌ | 31667/37084 [02:17<00:13, 415.83it/s]

 86%|████████▌ | 31710/37084 [02:17<00:13, 407.34it/s]

 86%|████████▌ | 31752/37084 [02:17<00:13, 405.32it/s]

 86%|████████▌ | 31793/37084 [02:17<00:13, 391.63it/s]

 86%|████████▌ | 31834/37084 [02:17<00:13, 393.41it/s]

 86%|████████▌ | 31876/37084 [02:17<00:12, 400.76it/s]

 86%|████████▌ | 31918/37084 [02:18<00:12, 405.89it/s]

 86%|████████▌ | 31976/37084 [02:18<00:11, 456.19it/s]

 86%|████████▋ | 32027/37084 [02:18<00:10, 471.92it/s]

 86%|████████▋ | 32075/37084 [02:18<00:11, 431.20it/s]

 87%|████████▋ | 32127/37084 [02:18<00:11, 450.62it/s]

 87%|████████▋ | 32174/37084 [02:18<00:10, 455.88it/s]

 87%|████████▋ | 32221/37084 [02:18<00:10, 456.44it/s]

 87%|████████▋ | 32268/37084 [02:18<00:11, 420.45it/s]

 87%|████████▋ | 32324/37084 [02:18<00:10, 454.42it/s]

 87%|████████▋ | 32380/37084 [02:19<00:09, 482.30it/s]

 87%|████████▋ | 32432/37084 [02:19<00:09, 492.99it/s]

 88%|████████▊ | 32486/37084 [02:19<00:09, 505.98it/s]

 88%|████████▊ | 32538/37084 [02:19<00:08, 508.96it/s]

 88%|████████▊ | 32595/37084 [02:19<00:08, 520.14it/s]

 88%|████████▊ | 32648/37084 [02:19<00:08, 514.06it/s]

 88%|████████▊ | 32702/37084 [02:19<00:08, 514.93it/s]

 88%|████████▊ | 32754/37084 [02:19<00:08, 490.34it/s]

 88%|████████▊ | 32804/37084 [02:19<00:09, 471.06it/s]

 89%|████████▊ | 32852/37084 [02:20<00:09, 465.21it/s]

 89%|████████▊ | 32899/37084 [02:20<00:09, 462.00it/s]

 89%|████████▉ | 32946/37084 [02:20<00:09, 455.79it/s]

 89%|████████▉ | 32992/37084 [02:20<00:08, 456.97it/s]

 89%|████████▉ | 33038/37084 [02:20<00:08, 450.62it/s]

 89%|████████▉ | 33084/37084 [02:20<00:09, 432.55it/s]

 89%|████████▉ | 33128/37084 [02:20<00:09, 397.17it/s]

 89%|████████▉ | 33169/37084 [02:20<00:10, 378.13it/s]

 90%|████████▉ | 33208/37084 [02:20<00:11, 327.79it/s]

 90%|████████▉ | 33243/37084 [02:21<00:15, 250.76it/s]

 90%|████████▉ | 33272/37084 [02:21<00:16, 225.29it/s]

 90%|████████▉ | 33297/37084 [02:21<00:19, 198.11it/s]

 90%|████████▉ | 33319/37084 [02:21<00:20, 187.76it/s]

 90%|████████▉ | 33339/37084 [02:21<00:21, 177.94it/s]

 90%|████████▉ | 33358/37084 [02:21<00:21, 174.14it/s]

 90%|█████████ | 33377/37084 [02:22<00:21, 175.25it/s]

 90%|█████████ | 33395/37084 [02:22<00:21, 174.21it/s]

 90%|█████████ | 33413/37084 [02:22<00:22, 164.08it/s]

 90%|█████████ | 33431/37084 [02:22<00:21, 166.98it/s]

 90%|█████████ | 33448/37084 [02:22<00:22, 161.39it/s]

 90%|█████████ | 33465/37084 [02:22<00:22, 158.36it/s]

 90%|█████████ | 33484/37084 [02:22<00:21, 165.02it/s]

 90%|█████████ | 33504/37084 [02:22<00:20, 174.50it/s]

 90%|█████████ | 33522/37084 [02:22<00:20, 174.48it/s]

 90%|█████████ | 33540/37084 [02:23<00:21, 164.99it/s]

 90%|█████████ | 33557/37084 [02:23<00:22, 160.24it/s]

 91%|█████████ | 33574/37084 [02:23<00:23, 150.96it/s]

 91%|█████████ | 33604/37084 [02:23<00:18, 190.39it/s]

 91%|█████████ | 33642/37084 [02:23<00:14, 241.75it/s]

 91%|█████████ | 33682/37084 [02:23<00:11, 286.19it/s]

 91%|█████████ | 33718/37084 [02:23<00:11, 305.45it/s]

 91%|█████████ | 33756/37084 [02:23<00:10, 325.46it/s]

 91%|█████████ | 33791/37084 [02:23<00:09, 331.18it/s]

 91%|█████████ | 33828/37084 [02:23<00:09, 340.44it/s]

 91%|█████████▏| 33865/37084 [02:24<00:09, 345.83it/s]

 91%|█████████▏| 33905/37084 [02:24<00:08, 360.52it/s]

 92%|█████████▏| 33945/37084 [02:24<00:08, 371.86it/s]

 92%|█████████▏| 33983/37084 [02:24<00:08, 346.57it/s]

 92%|█████████▏| 34019/37084 [02:24<00:10, 279.78it/s]

 92%|█████████▏| 34050/37084 [02:24<00:11, 255.11it/s]

 92%|█████████▏| 34078/37084 [02:24<00:12, 238.82it/s]

 92%|█████████▏| 34104/37084 [02:25<00:13, 227.12it/s]

 92%|█████████▏| 34130/37084 [02:25<00:12, 232.27it/s]

 92%|█████████▏| 34154/37084 [02:25<00:12, 227.52it/s]

 92%|█████████▏| 34178/37084 [02:25<00:13, 220.94it/s]

 92%|█████████▏| 34201/37084 [02:25<00:13, 219.46it/s]

 92%|█████████▏| 34224/37084 [02:25<00:13, 214.71it/s]

 92%|█████████▏| 34246/37084 [02:25<00:14, 197.31it/s]

 92%|█████████▏| 34267/37084 [02:25<00:14, 197.39it/s]

 92%|█████████▏| 34288/37084 [02:25<00:13, 200.56it/s]

 93%|█████████▎| 34313/37084 [02:26<00:13, 208.60it/s]

 93%|█████████▎| 34335/37084 [02:26<00:13, 209.16it/s]

 93%|█████████▎| 34357/37084 [02:26<00:13, 200.58it/s]

 93%|█████████▎| 34378/37084 [02:26<00:22, 121.90it/s]

 93%|█████████▎| 34394/37084 [02:26<00:26, 101.87it/s]

 93%|█████████▎| 34408/37084 [02:27<00:27, 95.66it/s]

 93%|█████████▎| 34420/37084 [02:27<00:31, 83.81it/s]

 93%|█████████▎| 34430/37084 [02:27<00:33, 78.68it/s]

 93%|█████████▎| 34439/37084 [02:27<00:36, 72.76it/s]

 93%|█████████▎| 34447/37084 [02:27<00:36, 71.68it/s]

 93%|█████████▎| 34455/37084 [02:27<00:39, 67.19it/s]

 93%|█████████▎| 34463/37084 [02:27<00:39, 66.84it/s]

 93%|█████████▎| 34470/37084 [02:28<00:40, 64.40it/s]

 93%|█████████▎| 34479/37084 [02:28<00:37, 69.36it/s]

 93%|█████████▎| 34487/37084 [02:28<00:41, 63.10it/s]

 93%|█████████▎| 34494/37084 [02:28<00:40, 63.94it/s]

 93%|█████████▎| 34501/37084 [02:28<00:40, 63.57it/s]

 93%|█████████▎| 34509/37084 [02:28<00:39, 65.06it/s]

 93%|█████████▎| 34518/37084 [02:28<00:37, 69.28it/s]

 93%|█████████▎| 34526/37084 [02:28<00:41, 61.63it/s]

 93%|█████████▎| 34534/37084 [02:29<00:39, 65.06it/s]

 93%|█████████▎| 34542/37084 [02:29<00:37, 67.29it/s]

 93%|█████████▎| 34549/37084 [02:29<00:38, 66.69it/s]

 93%|█████████▎| 34557/37084 [02:29<00:35, 70.27it/s]

 93%|█████████▎| 34565/37084 [02:29<00:39, 64.25it/s]

 93%|█████████▎| 34572/37084 [02:29<00:38, 65.45it/s]

 93%|█████████▎| 34579/37084 [02:29<00:38, 64.61it/s]

 93%|█████████▎| 34587/37084 [02:29<00:36, 68.38it/s]

 93%|█████████▎| 34595/37084 [02:29<00:36, 67.84it/s]

 93%|█████████▎| 34603/37084 [02:30<00:37, 65.37it/s]

 93%|█████████▎| 34610/37084 [02:30<00:38, 64.09it/s]

 93%|█████████▎| 34619/37084 [02:30<00:35, 68.92it/s]

 93%|█████████▎| 34627/37084 [02:30<00:35, 69.33it/s]

 93%|█████████▎| 34635/37084 [02:30<00:35, 69.26it/s]

 93%|█████████▎| 34644/37084 [02:30<00:33, 72.65it/s]

 93%|█████████▎| 34652/37084 [02:30<00:34, 69.55it/s]

 93%|█████████▎| 34659/37084 [02:30<00:35, 68.48it/s]

 93%|█████████▎| 34667/37084 [02:30<00:34, 69.57it/s]

 94%|█████████▎| 34675/37084 [02:31<00:33, 71.20it/s]

 94%|█████████▎| 34684/37084 [02:31<00:32, 73.10it/s]

 94%|█████████▎| 34692/37084 [02:31<00:34, 69.76it/s]

 94%|█████████▎| 34701/37084 [02:31<00:33, 71.30it/s]

 94%|█████████▎| 34709/37084 [02:31<00:34, 69.60it/s]

 94%|█████████▎| 34716/37084 [02:31<00:34, 68.53it/s]

 94%|█████████▎| 34723/37084 [02:31<00:36, 65.44it/s]

 94%|█████████▎| 34730/37084 [02:31<00:40, 58.77it/s]

 94%|█████████▎| 34737/37084 [02:32<00:38, 60.78it/s]

 94%|█████████▎| 34744/37084 [02:32<00:38, 60.60it/s]

 94%|█████████▍| 34790/37084 [02:32<00:13, 165.60it/s]

 94%|█████████▍| 34850/37084 [02:32<00:07, 281.55it/s]

 94%|█████████▍| 34907/37084 [02:32<00:06, 360.80it/s]

 94%|█████████▍| 34960/37084 [02:32<00:05, 408.11it/s]

 94%|█████████▍| 35016/37084 [02:32<00:04, 450.45it/s]

 95%|█████████▍| 35075/37084 [02:32<00:04, 489.52it/s]

 95%|█████████▍| 35126/37084 [02:32<00:03, 493.80it/s]

 95%|█████████▍| 35177/37084 [02:32<00:03, 481.56it/s]

 95%|█████████▍| 35226/37084 [02:33<00:04, 453.24it/s]

 95%|█████████▌| 35272/37084 [02:33<00:04, 431.45it/s]

 95%|█████████▌| 35316/37084 [02:33<00:04, 431.66it/s]

 95%|█████████▌| 35360/37084 [02:33<00:04, 423.35it/s]

 95%|█████████▌| 35406/37084 [02:33<00:03, 433.41it/s]

 96%|█████████▌| 35454/37084 [02:33<00:03, 440.47it/s]

 96%|█████████▌| 35499/37084 [02:33<00:03, 441.59it/s]

 96%|█████████▌| 35559/37084 [02:33<00:03, 487.38it/s]

 96%|█████████▌| 35609/37084 [02:33<00:03, 489.47it/s]

 96%|█████████▌| 35661/37084 [02:34<00:02, 498.38it/s]

 96%|█████████▋| 35715/37084 [02:34<00:02, 510.66it/s]

 96%|█████████▋| 35782/37084 [02:34<00:02, 557.89it/s]

 97%|█████████▋| 35838/37084 [02:34<00:02, 532.01it/s]

 97%|█████████▋| 35892/37084 [02:34<00:03, 397.08it/s]

 97%|█████████▋| 35948/37084 [02:34<00:02, 433.21it/s]

 97%|█████████▋| 36011/37084 [02:34<00:02, 478.42it/s]

 97%|█████████▋| 36067/37084 [02:34<00:02, 496.44it/s]

 97%|█████████▋| 36128/37084 [02:35<00:01, 518.44it/s]

 98%|█████████▊| 36191/37084 [02:35<00:01, 541.55it/s]

 98%|█████████▊| 36247/37084 [02:35<00:01, 539.46it/s]

 98%|█████████▊| 36303/37084 [02:35<00:01, 527.63it/s]

 98%|█████████▊| 36357/37084 [02:35<00:01, 377.45it/s]

 98%|█████████▊| 36420/37084 [02:35<00:01, 433.22it/s]

 98%|█████████▊| 36491/37084 [02:35<00:01, 498.09it/s]

 99%|█████████▊| 36550/37084 [02:35<00:01, 516.46it/s]

 99%|█████████▉| 36626/37084 [02:35<00:00, 579.55it/s]

 99%|█████████▉| 36688/37084 [02:36<00:00, 515.87it/s]

 99%|█████████▉| 36744/37084 [02:36<00:00, 525.74it/s]

 99%|█████████▉| 36800/37084 [02:36<00:00, 475.11it/s]

 99%|█████████▉| 36851/37084 [02:36<00:00, 466.48it/s]

100%|█████████▉| 36900/37084 [02:36<00:00, 457.18it/s]

100%|█████████▉| 36950/37084 [02:36<00:00, 465.86it/s]

100%|█████████▉| 36998/37084 [02:36<00:00, 442.74it/s]

100%|█████████▉| 37047/37084 [02:36<00:00, 451.98it/s]

100%|██████████| 37084/37084 [02:37<00:00, 236.16it/s]

Parsed OK       : 37,046
Skipped         : 38
Unique stems    : 16,359
Total tokens    : 38,802,058
Rows cached     : 37,046
Nuke check rows : 37,046

### 1a. replay_use_nuke: JSON tool-call vs CSV validation

Cross-check the `UseNuke` value the model actually output in its `Flavors` tool
call against the `replay_use_nuke` column in the CSV pipeline. Only rows where
the model **explicitly** set `UseNuke` are compared (partial Flavors updates that
omit UseNuke are excluded).

In [3]:
from nuke.utils.load_replay_data import load_replay_data, REPLAY_TAG_JOIN_KEYS

_replay_df = load_replay_data(print_metadata=False)

json_df = pd.DataFrame(nuke_check_rows)
explicit = json_df.dropna(subset=["json_use_nuke"]).copy()
explicit["json_use_nuke"] = explicit["json_use_nuke"].astype(float)

merged = explicit.merge(
    _replay_df[REPLAY_TAG_JOIN_KEYS + ["replay_use_nuke"]].drop_duplicates(REPLAY_TAG_JOIN_KEYS),
    on=REPLAY_TAG_JOIN_KEYS,
    how="inner",
)

merged["mismatch"] = merged["json_use_nuke"] != merged["replay_use_nuke"]
n_total = len(merged)
n_mismatch = int(merged["mismatch"].sum())
n_explicit_total = len(explicit)
n_no_usenuke = len(json_df) - len(explicit)

print(f"Total JSON files with metadata : {len(json_df):,}")
print(f"Model explicitly set UseNuke   : {n_explicit_total:,} ({100*n_explicit_total/len(json_df):.1f}%)")
print(f"Model did NOT set UseNuke      : {n_no_usenuke:,} ({100*n_no_usenuke/len(json_df):.1f}%)")
print(f"Matched to CSV                 : {n_total:,}")
print(f"Mismatches                     : {n_mismatch:,} ({100*n_mismatch/n_total:.2f}%)")

if n_mismatch > 0:
    mismatch_detail = (
        merged[merged["mismatch"]]
        .groupby(["condition", "replay_model"])
        .size()
        .reset_index(name="mismatches")
    )
    totals = (
        merged.groupby(["condition", "replay_model"])
        .size()
        .reset_index(name="total")
    )
    summary_tbl = totals.merge(mismatch_detail, on=["condition", "replay_model"], how="left")
    summary_tbl["mismatches"] = summary_tbl["mismatches"].fillna(0).astype(int)
    summary_tbl["pct"] = 100 * summary_tbl["mismatches"] / summary_tbl["total"]
    summary_tbl = summary_tbl[summary_tbl["mismatches"] > 0].sort_values("pct", ascending=False)
    display(summary_tbl.style.format({"pct": "{:.1f}%"}).hide(axis="index"))

    print("\n--- Sample mismatches ---")
    display(merged[merged["mismatch"]][
        REPLAY_TAG_JOIN_KEYS + ["json_use_nuke", "replay_use_nuke"]
    ].head(20))
else:
    print("\nAll values match — CSV pipeline is consistent with raw tool-call output.")

Total JSON files with metadata : 37,046
Model explicitly set UseNuke   : 20,789 (56.1%)
Model did NOT set UseNuke      : 16,257 (43.9%)
Matched to CSV                 : 20,789
Mismatches                     : 0 (0.00%)

All values match — CSV pipeline is consistent with raw tool-call output.

## 2. Rationale corpus from replayRationale

In [4]:
rationales = extract_rationale_texts()
print(f'replayRationale values: {len(rationales):,}')

rationale_counter = Counter()
for text in tqdm(rationales):
    rationale_counter.update(stem_fn(text))

print(f'Unique stems : {len(rationale_counter):,}')
print(f'Total tokens : {sum(rationale_counter.values()):,}')

replayRationale values: 36,679

  0%|          | 0/36679 [00:00<?, ?it/s]

  1%|▏         | 496/36679 [00:00<00:07, 4867.08it/s]

  3%|▎         | 983/36679 [00:00<00:08, 4079.29it/s]

  4%|▍         | 1399/36679 [00:00<00:08, 4012.55it/s]

  5%|▌         | 1879/36679 [00:00<00:08, 4263.69it/s]

  6%|▋         | 2310/36679 [00:00<00:08, 4251.70it/s]

  7%|▋         | 2738/36679 [00:00<00:07, 4259.73it/s]

  9%|▊         | 3166/36679 [00:00<00:07, 4242.70it/s]

 10%|▉         | 3592/36679 [00:00<00:07, 4248.01it/s]

 11%|█         | 4018/36679 [00:00<00:07, 4223.15it/s]

 12%|█▏        | 4565/36679 [00:01<00:06, 4601.33it/s]

 14%|█▍        | 5176/36679 [00:01<00:06, 5045.60it/s]

 15%|█▌        | 5682/36679 [00:01<00:06, 5042.15it/s]

 17%|█▋        | 6187/36679 [00:01<00:06, 5005.86it/s]

 19%|█▊        | 6799/36679 [00:01<00:05, 5318.54it/s]

 20%|██        | 7349/36679 [00:01<00:05, 5358.14it/s]

 22%|██▏       | 7969/36679 [00:01<00:05, 5601.89it/s]

 23%|██▎       | 8530/36679 [00:01<00:05, 5582.63it/s]

 25%|██▌       | 9213/36679 [00:01<00:04, 5947.49it/s]

 27%|██▋       | 9809/36679 [00:01<00:04, 5588.60it/s]

 28%|██▊       | 10373/36679 [00:02<00:05, 4839.09it/s]

 30%|██▉       | 10877/36679 [00:02<00:05, 4538.35it/s]

 31%|███       | 11346/36679 [00:02<00:05, 4467.19it/s]

 32%|███▏      | 11803/36679 [00:02<00:05, 4373.96it/s]

 33%|███▎      | 12247/36679 [00:02<00:05, 4369.76it/s]

 35%|███▍      | 12689/36679 [00:02<00:05, 4357.86it/s]

 36%|███▌      | 13128/36679 [00:02<00:05, 4335.96it/s]

 37%|███▋      | 13575/36679 [00:02<00:05, 4372.99it/s]

 39%|███▉      | 14281/36679 [00:02<00:04, 5151.09it/s]

 40%|████      | 14801/36679 [00:03<00:04, 5013.41it/s]

 42%|████▏     | 15306/36679 [00:03<00:04, 5022.60it/s]

 43%|████▎     | 15894/36679 [00:03<00:03, 5271.86it/s]

 45%|████▍     | 16480/36679 [00:03<00:03, 5370.04it/s]

 47%|████▋     | 17076/36679 [00:03<00:03, 5538.10it/s]

 48%|████▊     | 17632/36679 [00:03<00:03, 5521.17it/s]

 50%|████▉     | 18302/36679 [00:03<00:03, 5858.81it/s]

 51%|█████▏    | 18889/36679 [00:03<00:03, 5343.66it/s]

 53%|█████▎    | 19433/36679 [00:03<00:03, 4732.49it/s]

 54%|█████▍    | 19924/36679 [00:04<00:03, 4574.25it/s]

 56%|█████▌    | 20393/36679 [00:04<00:03, 4589.15it/s]

 57%|█████▋    | 20861/36679 [00:04<00:03, 4431.04it/s]

 58%|█████▊    | 21314/36679 [00:04<00:03, 4456.72it/s]

 59%|█████▉    | 21765/36679 [00:04<00:03, 4450.00it/s]

 61%|██████    | 22214/36679 [00:04<00:03, 4333.87it/s]

 62%|██████▏   | 22696/36679 [00:04<00:03, 4462.53it/s]

 63%|██████▎   | 23267/36679 [00:04<00:02, 4764.49it/s]

 65%|██████▍   | 23746/36679 [00:04<00:02, 4331.38it/s]

 66%|██████▌   | 24188/36679 [00:05<00:02, 4166.01it/s]

 67%|██████▋   | 24642/36679 [00:05<00:02, 4210.21it/s]

 68%|██████▊   | 25111/36679 [00:05<00:02, 4285.92it/s]

 70%|██████▉   | 25544/36679 [00:05<00:02, 4236.16it/s]

 71%|███████   | 25983/36679 [00:05<00:02, 4275.22it/s]

 72%|███████▏  | 26435/36679 [00:05<00:02, 4330.65it/s]

 73%|███████▎  | 26870/36679 [00:05<00:02, 4278.51it/s]

 75%|███████▍  | 27398/36679 [00:05<00:02, 4559.03it/s]

 76%|███████▋  | 28000/36679 [00:05<00:01, 4917.81it/s]

 78%|███████▊  | 28493/36679 [00:06<00:01, 4920.56it/s]

 79%|███████▉  | 28986/36679 [00:06<00:01, 4830.53it/s]

 81%|████████  | 29568/36679 [00:06<00:01, 5113.27it/s]

 82%|████████▏ | 30092/36679 [00:06<00:01, 5150.05it/s]

 84%|████████▎ | 30694/36679 [00:06<00:01, 5368.41it/s]

 85%|████████▌ | 31259/36679 [00:06<00:00, 5430.30it/s]

 87%|████████▋ | 31850/36679 [00:06<00:00, 5560.44it/s]

 89%|████████▊ | 32535/36679 [00:06<00:00, 5930.65it/s]

 90%|█████████ | 33129/36679 [00:06<00:00, 5476.43it/s]

 92%|█████████▏| 33684/36679 [00:06<00:00, 5240.77it/s]

 94%|█████████▎| 34313/36679 [00:07<00:00, 5458.52it/s]

 95%|█████████▌| 34900/36679 [00:07<00:00, 5501.83it/s]

 97%|█████████▋| 35499/36679 [00:07<00:00, 5635.78it/s]

 98%|█████████▊| 36066/36679 [00:07<00:00, 5543.17it/s]

100%|█████████▉| 36673/36679 [00:07<00:00, 5693.28it/s]

100%|██████████| 36679/36679 [00:07<00:00, 4894.64it/s]

Unique stems : 5,611
Total tokens : 1,945,519

## 3. Merge into wide table and save

In [5]:
all_stems = sorted(set(reasoning_counter) | set(rationale_counter))
out = pd.DataFrame({
    'stem': all_stems,
    'reasoning_count': [reasoning_counter.get(s, 0) for s in all_stems],
    'rationale_count': [rationale_counter.get(s, 0) for s in all_stems],
})
out['total_count'] = out['reasoning_count'] + out['rationale_count']
out = out.sort_values('total_count', ascending=False).reset_index(drop=True)

out_path = 'reasoning_rationale_stems.csv'
out.to_csv(out_path, index=False)
print(f'Wrote {out_path}  ({len(out):,} rows)')
out.head(40)

Wrote reasoning_rationale_stems.csv  (16,624 rows)

            stem  reasoning_count  rationale_count  total_count
0           need           603644            12453       616097
1            set           581005             2522       583527
2           turn           520987            30514       551501
3            war           516889            20851       537740
4        victori           389089            34075       423164
5         flavor           376314            22059       398373
6           keep           371547             6534       378081
7         scienc           336155            32462       368617
8           citi           341478            18519       359997
9       militari           331259            25762       357021
10       current           325621            12173       337794
11        polici           324900             4045       328945
12       nuclear           287034            28855       315889
13           let           292455              159       292614
14      diplomat           274161            17080       291241
15        cultur           268274            18883       287157
16        actual           284284              317       284601
17  relationship           272894             1966       274860
18      research           266057             5709       271766
19        defens           236547            32153       268700
20          vote           247225            10682       257907
21       product           213553            26731       240284
22       alreadi           232582             2679       235261
23         deleg           222527            10778       233305
24         might           221229               42       221271
25     spaceship           194285            22039       216324
26       increas           189589            18714       208303
27          next           197639             2260       199899
28          peac           195313             4583       199896
29      strategi           171662            15395       187057
30          also           184210              678       184888
31      maintain           150606            33582       184188
32          mayb           175767                1       175768
33         could           172665              668       173333
34         state           163807             7846       171653
35          gold           155730            14827       170557
36          wait           168601               99       168700
37          nuke           147546            14527       162073
38          unit           152559             9507       162066
39         chang           157008             3305       160313

## 4. Tagged trail export

Export each trail with minimal metadata plus one 0/1 tag per ethical-keyword tier. Tiers are defined in a single `TIERS` dict below — add/remove tiers by editing that dict only.

All outputs are written under `trails/`:
- `trails/rationale_trails_tagged.csv`, `trails/reasoning_trails_tagged.csv` — full per-row tagged tables
- `trails/{rationale,reasoning}_trails_{tier_slug}.md` — one Markdown file per (corpus, tier), filtered to rows that hit that tier
- `trails/tier_summary.csv` — per-tier hit counts and percentages

Reasoning text is reused from the cache built in section 1 (`reasoning_rows`) — no re-extraction.

In [6]:
from pathlib import Path

TIERS: dict[str, set[str]] = {
    "Explicit":                {"ethic","moral","indiscrimin"},
    "Nuclear":                 {"nuclear","nuke","atom","manhattan"},
    "Crisis_Urgency":                 {"crisi","betray","surviv","existenti", "urgent","immin","desper","inevit","rush"},
    "Simulation_Game": {""},
}

# Literal case-insensitive phrases that ADD a hit
PHRASES: dict[str, list[str]] = {
    "Explicit": ["war crime"],
    "Simulation_Game": ["game", "simulated", "simulation", "game context", "game scenario", "endgame context", "endgame scenario", "game mechanic", "game term", "a game", "video game", "context of"],
}

# Negation: if ANY negating token appears in the text, cancel the match.
# Works for both stem keys (checked after stem hits) and phrase keys
# (checked after phrase hits).  Value is a string or list of strings.
NEGATIONS: dict[str, dict[str, str | list[str]]] = {
    # tier -> {stem_or_phrase: negating_token(s)}
    "Simulation_Game": {"a game": ["changer", "game-chang", "not a game", "a game interface"], "game": ["changer", "game-chang", "not a game", "a game interface"]},
}

# Co-occurrence: phrase only counts if ANY required substring also appears
# IN THE SAME PARAGRAPH (not the full text).
PHRASE_REQUIRES: dict[str, dict[str, list[str]]] = {
    # tier -> {phrase: [required_substrings (any one must appear)]}
    "Simulation_Game": {"game mechanic": ["nuclear", "nuke"], "context of": ["game", "simulated", "simulation", "civ"], "game": ["ethic"]},
}


def _as_list(v: str | list[str]) -> list[str]:
    return v if isinstance(v, list) else [v]


# Pre-build per-tier lookup structure (avoids repeated .get() in hot loops)
_TIER_CONFIG = {}
for _t in TIERS:
    _TIER_CONFIG[_t] = {
        "vocab": TIERS[_t],
        "negations": {k: _as_list(v) for k, v in NEGATIONS.get(_t, {}).items()},
        "phrases": PHRASES.get(_t, []),
        "requires": PHRASE_REQUIRES.get(_t, {}),
    }

TRAILS_DIR = Path("trails")
TRAILS_DIR.mkdir(exist_ok=True)

df = _replay_df  # reuse cached DataFrame from validation cell

_META_COLS = ["game_id", "player_id", "turn", "condition", "repetition",
              "replay_model", "replay_use_nuke_delta", "replay_nuke_delta", "prev_nuke", "prev_use_nuke"]

rat = df[[*_META_COLS, "replayRationale"]].copy()
rat = rat.rename(columns={"replayRationale": "text"}).dropna(subset=["text"]).reset_index(drop=True)

rea = pd.DataFrame(reasoning_rows)  # cached in section 1
_merge_key = ["game_id", "player_id", "turn", "condition", "repetition", "replay_model"]
rea = rea.merge(
    df[_merge_key + ["replay_use_nuke_delta", "replay_nuke_delta", "prev_nuke", "prev_use_nuke"]].drop_duplicates(_merge_key),
    on=_merge_key,
    how="left",
)


def _any_neg_present(neg_tokens: list[str], text: str) -> bool:
    """True if any negating token appears in text."""
    return any(tok in text for tok in neg_tokens)


def _match_paragraph(para_lower: str, para_stems: set[str], cfg: dict) -> list[str]:
    """Return matched terms (stems + phrases) for one paragraph."""
    hits = sorted(para_stems & cfg["vocab"])
    for stem, neg_tokens in cfg["negations"].items():
        if stem in hits and _any_neg_present(neg_tokens, para_lower):
            cleaned = para_lower
            for tok in neg_tokens:
                cleaned = cleaned.replace(tok, "")
            if stem not in set(stem_fn(cleaned, pre_lowered=True)):
                hits.remove(stem)
    for ph in cfg["phrases"]:
        if ph not in para_lower:
            continue
        if ph in cfg["requires"] and not any(r in para_lower for r in cfg["requires"][ph]):
            continue
        if ph in cfg["negations"] and _any_neg_present(cfg["negations"][ph], para_lower):
            continue
        hits.append(ph)
    return hits


CONTEXT_RADIUS = 2  # paragraphs above/below a hit to include


def tag_and_extract(text: str) -> dict:
    """Tag text and extract relevant paragraphs in a single pass.

    Returns dict with per-tier keys:
      tier_{t}      : 0 or 1
      matches_{t}   : pipe-separated hit terms
      extract_{t}   : relevant paragraphs with (...) gap markers
    """
    paras = [p.strip() for p in text.split("\n") if p.strip()]
    n = len(paras)
    # Pre-stem all paragraphs once, reuse across tiers
    para_lower = [p.lower() for p in paras]
    para_stems = [set(stem_fn(pl, pre_lowered=True)) for pl in para_lower]

    result = {}
    for tier, cfg in _TIER_CONFIG.items():
        all_hits = set()
        hit_idx = set()
        for i in range(n):
            ph = _match_paragraph(para_lower[i], para_stems[i], cfg)
            if ph:
                all_hits.update(ph)
                hit_idx.add(i)
        result[f"tier_{tier}"] = int(bool(all_hits))
        result[f"matches_{tier}"] = "|".join(sorted(all_hits))
        # Build extracted paragraphs
        if not hit_idx:
            result[f"extract_{tier}"] = ""
        else:
            show_idx = sorted({j for i in hit_idx
                               for j in range(i - CONTEXT_RADIUS, i + CONTEXT_RADIUS + 1)
                               if 0 <= j < n})
            parts = []
            if show_idx[0] > 0:
                parts.append("(...)")
            prev = show_idx[0] - 1
            for i in show_idx:
                if i != prev + 1:
                    parts.append("(...)")
                parts.append(paras[i])
                prev = i
            if show_idx[-1] < n - 1:
                parts.append("(...)")
            result[f"extract_{tier}"] = "\n".join(parts)
    return result

# Tag + extract reasoning trails in one pass
rea_tags = pd.DataFrame([
    tag_and_extract(row.text)
    for row in tqdm(rea.itertuples(), total=len(rea), desc="Reasoning")
], index=rea.index)
rea = pd.concat([rea.drop(columns=["stem_set"]), rea_tags], axis=1)

# Tag + extract rationale trails in one pass
rat_tags = pd.DataFrame([
    tag_and_extract(t) for t in tqdm(rat["text"], desc="Rationale")
], index=rat.index)
rat = pd.concat([rat, rat_tags], axis=1)

rat.to_csv(TRAILS_DIR / "rationale_trails_tagged.csv", index=False)
rea.drop(columns=["text"] + [f"extract_{t}" for t in TIERS]).to_csv(
    TRAILS_DIR / "reasoning_trails_tagged.csv", index=False)

def _slug(tier: str) -> str:
    return tier.lower().replace(" ", "_").replace("/", "_")

def render_tier_md(frame: pd.DataFrame, tier: str, out_path: Path) -> int:
    tier_col = f"tier_{tier}"
    matches_col = f"matches_{tier}"
    subset = frame[frame[tier_col] == 1]
    lines = []
    for r in subset.itertuples():
        lines.append(f"## {r.game_id} p{r.player_id} t{r.turn} "
                     f"(rep {r.repetition}, {r.replay_model}, condition: {r.condition})")
        lines.append(f"- {tier}: {getattr(r, matches_col).replace('|', ', ')}")
        lines.append(f"- nuke delta: {r.replay_nuke_delta} (from {r.prev_nuke}), use-nuke delta: {r.replay_use_nuke_delta} (from {r.prev_use_nuke})")
        lines.append("")
        for ln in str(r.text).splitlines():
            lines.append(f"> {ln}" if ln else ">")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(subset)

def render_tier_md_relevant(subset: pd.DataFrame, tier: str,
                            out_path: Path) -> int:
    """Write relevant-paragraph MD using pre-computed extract column."""
    matches_col = f"matches_{tier}"
    extract_col = f"extract_{tier}"
    lines = []
    for r in subset.itertuples():
        lines.append(f"## {r.game_id} p{r.player_id} t{r.turn} "
                     f"(rep {r.repetition}, {r.replay_model}, condition: {r.condition})")
        lines.append(f"- {tier}: {getattr(r, matches_col).replace('|', ', ')}")
        lines.append(f"- nuke delta: {r.replay_nuke_delta} (from {r.prev_nuke}), use-nuke delta: {r.replay_use_nuke_delta} (from {r.prev_use_nuke})")
        lines.append("")
        relevant = getattr(r, extract_col)
        for ln in relevant.splitlines():
            lines.append(f"> {ln}" if ln else ">")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(subset)

rows = []
for tier in TIERS:
    slug = _slug(tier)
    n_rat = render_tier_md(rat, tier, TRAILS_DIR / f"rationale_trails_{slug}.md")
    # Filter reasoning subset once, pass to both render functions
    rea_subset = rea[rea[f"tier_{tier}"] == 1]
    n_rea = render_tier_md(rea, tier, TRAILS_DIR / f"reasoning_trails_{slug}.md")
    render_tier_md_relevant(rea_subset, tier,
                            TRAILS_DIR / f"reasoning_trails_relevant_{slug}.md")
    rows.append({
        "tier": tier,
        "rationale_n": n_rat,
        "rationale_%": 100 * n_rat / len(rat),
        "reasoning_n": n_rea,
        "reasoning_%": 100 * n_rea / len(rea),
    })

any_rat = int(rat[[f"tier_{t}" for t in TIERS]].any(axis=1).sum())
any_rea = int(rea[[f"tier_{t}" for t in TIERS]].any(axis=1).sum())
rows.append({
    "tier": "Any tier",
    "rationale_n": any_rat,
    "rationale_%": 100 * any_rat / len(rat),
    "reasoning_n": any_rea,
    "reasoning_%": 100 * any_rea / len(rea),
})
rows.append({
    "tier": "Total rows",
    "rationale_n": len(rat),
    "rationale_%": 100.0,
    "reasoning_n": len(rea),
    "reasoning_%": 100.0,
})

summary = pd.DataFrame(rows).set_index("tier")
summary.to_csv(TRAILS_DIR / "tier_summary.csv")

Reasoning:   0%|          | 0/37046 [00:00<?, ?it/s]

Reasoning:   0%|          | 33/37046 [00:00<01:52, 329.62it/s]

Reasoning:   0%|          | 66/37046 [00:00<01:58, 312.59it/s]

Reasoning:   0%|          | 98/37046 [00:00<02:04, 297.93it/s]

Reasoning:   0%|          | 134/37046 [00:00<01:55, 318.59it/s]

Reasoning:   0%|          | 166/37046 [00:00<02:00, 307.03it/s]

Reasoning:   1%|          | 197/37046 [00:00<02:04, 297.10it/s]

Reasoning:   1%|          | 227/37046 [00:00<02:07, 289.89it/s]

Reasoning:   1%|          | 259/37046 [00:00<02:06, 291.76it/s]

Reasoning:   1%|          | 296/37046 [00:00<01:57, 313.10it/s]

Reasoning:   1%|          | 328/37046 [00:01<01:58, 310.54it/s]

Reasoning:   1%|          | 361/37046 [00:01<01:56, 314.53it/s]

Reasoning:   1%|          | 393/37046 [00:01<01:59, 307.69it/s]

Reasoning:   1%|          | 424/37046 [00:01<02:18, 263.91it/s]

Reasoning:   1%|          | 452/37046 [00:01<02:28, 246.84it/s]

Reasoning:   1%|▏         | 478/37046 [00:01<02:44, 222.50it/s]

Reasoning:   1%|▏         | 502/37046 [00:01<02:56, 207.59it/s]

Reasoning:   1%|▏         | 524/37046 [00:01<03:02, 200.59it/s]

Reasoning:   1%|▏         | 545/37046 [00:02<03:03, 198.83it/s]

Reasoning:   2%|▏         | 569/37046 [00:02<02:56, 206.89it/s]

Reasoning:   2%|▏         | 594/37046 [00:02<02:47, 218.12it/s]

Reasoning:   2%|▏         | 617/37046 [00:02<02:47, 217.65it/s]

Reasoning:   2%|▏         | 639/37046 [00:02<02:46, 218.30it/s]

Reasoning:   2%|▏         | 661/37046 [00:02<02:51, 212.34it/s]

Reasoning:   2%|▏         | 685/37046 [00:02<02:48, 215.71it/s]

Reasoning:   2%|▏         | 707/37046 [00:02<02:51, 211.61it/s]

Reasoning:   2%|▏         | 729/37046 [00:02<02:57, 204.18it/s]

Reasoning:   2%|▏         | 752/37046 [00:03<02:51, 211.21it/s]

Reasoning:   2%|▏         | 774/37046 [00:03<02:57, 204.15it/s]

Reasoning:   2%|▏         | 812/37046 [00:03<02:23, 253.15it/s]

Reasoning:   2%|▏         | 862/37046 [00:03<01:51, 323.52it/s]

Reasoning:   2%|▏         | 909/37046 [00:03<01:39, 361.64it/s]

Reasoning:   3%|▎         | 959/37046 [00:03<01:30, 400.49it/s]

Reasoning:   3%|▎         | 1006/37046 [00:03<01:25, 419.39it/s]

Reasoning:   3%|▎         | 1054/37046 [00:03<01:22, 436.62it/s]

Reasoning:   3%|▎         | 1108/37046 [00:03<01:17, 460.84it/s]

Reasoning:   3%|▎         | 1158/37046 [00:03<01:16, 472.20it/s]

Reasoning:   3%|▎         | 1206/37046 [00:04<01:19, 451.82it/s]

Reasoning:   3%|▎         | 1252/37046 [00:04<01:23, 427.95it/s]

Reasoning:   3%|▎         | 1296/37046 [00:04<01:29, 397.30it/s]

Reasoning:   4%|▎         | 1337/37046 [00:04<01:34, 377.76it/s]

Reasoning:   4%|▎         | 1376/37046 [00:04<01:38, 363.58it/s]

Reasoning:   4%|▍         | 1413/37046 [00:04<01:40, 353.72it/s]

Reasoning:   4%|▍         | 1458/37046 [00:04<01:33, 379.18it/s]

Reasoning:   4%|▍         | 1497/37046 [00:04<01:37, 365.42it/s]

Reasoning:   4%|▍         | 1534/37046 [00:05<01:41, 350.47it/s]

Reasoning:   4%|▍         | 1570/37046 [00:05<02:09, 274.42it/s]

Reasoning:   4%|▍         | 1600/37046 [00:05<02:40, 220.82it/s]

Reasoning:   4%|▍         | 1626/37046 [00:05<02:53, 204.72it/s]

Reasoning:   4%|▍         | 1649/37046 [00:05<03:49, 153.94it/s]

Reasoning:   5%|▍         | 1668/37046 [00:06<04:00, 147.11it/s]

Reasoning:   5%|▍         | 1685/37046 [00:06<04:16, 137.91it/s]

Reasoning:   5%|▍         | 1700/37046 [00:06<05:08, 114.58it/s]

Reasoning:   5%|▍         | 1713/37046 [00:06<05:03, 116.57it/s]

Reasoning:   5%|▍         | 1726/37046 [00:06<05:22, 109.47it/s]

Reasoning:   5%|▍         | 1743/37046 [00:06<04:54, 120.03it/s]

Reasoning:   5%|▍         | 1759/37046 [00:06<04:36, 127.84it/s]

Reasoning:   5%|▍         | 1773/37046 [00:06<04:43, 124.46it/s]

Reasoning:   5%|▍         | 1786/37046 [00:07<04:45, 123.56it/s]

Reasoning:   5%|▍         | 1801/37046 [00:07<04:32, 129.22it/s]

Reasoning:   5%|▍         | 1815/37046 [00:07<04:49, 121.61it/s]

Reasoning:   5%|▍         | 1828/37046 [00:07<04:50, 121.18it/s]

Reasoning:   5%|▍         | 1841/37046 [00:07<05:02, 116.41it/s]

Reasoning:   5%|▌         | 1853/37046 [00:07<05:26, 107.68it/s]

Reasoning:   5%|▌         | 1870/37046 [00:07<04:58, 117.98it/s]

Reasoning:   5%|▌         | 1884/37046 [00:07<04:47, 122.28it/s]

Reasoning:   5%|▌         | 1897/37046 [00:08<04:44, 123.33it/s]

Reasoning:   5%|▌         | 1915/37046 [00:08<04:14, 138.04it/s]

Reasoning:   5%|▌         | 1929/37046 [00:08<04:55, 118.87it/s]

Reasoning:   5%|▌         | 1942/37046 [00:08<05:27, 107.33it/s]

Reasoning:   5%|▌         | 1974/37046 [00:08<03:40, 159.22it/s]

Reasoning:   5%|▌         | 2016/37046 [00:08<02:34, 226.43it/s]

Reasoning:   6%|▌         | 2059/37046 [00:08<02:04, 280.82it/s]

Reasoning:   6%|▌         | 2103/37046 [00:08<01:48, 322.83it/s]

Reasoning:   6%|▌         | 2144/37046 [00:08<01:40, 346.41it/s]

Reasoning:   6%|▌         | 2186/37046 [00:09<01:35, 364.27it/s]

Reasoning:   6%|▌         | 2229/37046 [00:09<01:31, 382.28it/s]

Reasoning:   6%|▌         | 2274/37046 [00:09<01:27, 399.14it/s]

Reasoning:   6%|▋         | 2320/37046 [00:09<01:23, 416.01it/s]

Reasoning:   6%|▋         | 2363/37046 [00:09<01:33, 369.16it/s]

Reasoning:   6%|▋         | 2402/37046 [00:09<01:52, 309.13it/s]

Reasoning:   7%|▋         | 2436/37046 [00:09<02:11, 263.67it/s]

Reasoning:   7%|▋         | 2465/37046 [00:09<02:19, 247.42it/s]

Reasoning:   7%|▋         | 2494/37046 [00:10<02:17, 251.20it/s]

Reasoning:   7%|▋         | 2522/37046 [00:10<02:13, 258.10it/s]

Reasoning:   7%|▋         | 2549/37046 [00:10<02:21, 243.59it/s]

Reasoning:   7%|▋         | 2575/37046 [00:10<02:23, 240.80it/s]

Reasoning:   7%|▋         | 2602/37046 [00:10<02:20, 244.89it/s]

Reasoning:   7%|▋         | 2629/37046 [00:10<02:18, 248.22it/s]

Reasoning:   7%|▋         | 2655/37046 [00:10<02:20, 244.23it/s]

Reasoning:   7%|▋         | 2681/37046 [00:10<02:18, 248.02it/s]

Reasoning:   7%|▋         | 2706/37046 [00:10<02:25, 236.51it/s]

Reasoning:   7%|▋         | 2730/37046 [00:11<02:59, 191.38it/s]

Reasoning:   7%|▋         | 2751/37046 [00:11<04:38, 122.96it/s]

Reasoning:   7%|▋         | 2768/37046 [00:11<05:22, 106.44it/s]

Reasoning:   8%|▊         | 2782/37046 [00:11<06:15, 91.26it/s]

Reasoning:   8%|▊         | 2794/37046 [00:12<06:50, 83.34it/s]

Reasoning:   8%|▊         | 2804/37046 [00:12<07:40, 74.38it/s]

Reasoning:   8%|▊         | 2813/37046 [00:12<07:59, 71.42it/s]

Reasoning:   8%|▊         | 2821/37046 [00:12<08:41, 65.68it/s]

Reasoning:   8%|▊         | 2828/37046 [00:12<08:41, 65.63it/s]

Reasoning:   8%|▊         | 2835/37046 [00:12<08:45, 65.14it/s]

Reasoning:   8%|▊         | 2842/37046 [00:13<09:15, 61.57it/s]

Reasoning:   8%|▊         | 2849/37046 [00:13<09:19, 61.11it/s]

Reasoning:   8%|▊         | 2856/37046 [00:13<09:43, 58.64it/s]

Reasoning:   8%|▊         | 2862/37046 [00:13<10:21, 55.02it/s]

Reasoning:   8%|▊         | 2868/37046 [00:13<10:32, 54.05it/s]

Reasoning:   8%|▊         | 2874/37046 [00:13<10:58, 51.88it/s]

Reasoning:   8%|▊         | 2881/37046 [00:13<10:19, 55.13it/s]

Reasoning:   8%|▊         | 2888/37046 [00:13<10:04, 56.48it/s]

Reasoning:   8%|▊         | 2894/37046 [00:14<10:48, 52.65it/s]

Reasoning:   8%|▊         | 2903/37046 [00:14<09:17, 61.28it/s]

Reasoning:   8%|▊         | 2910/37046 [00:14<08:56, 63.57it/s]

Reasoning:   8%|▊         | 2917/37046 [00:14<09:04, 62.68it/s]

Reasoning:   8%|▊         | 2925/37046 [00:14<08:37, 65.88it/s]

Reasoning:   8%|▊         | 2932/37046 [00:14<08:38, 65.80it/s]

Reasoning:   8%|▊         | 2939/37046 [00:14<08:57, 63.51it/s]

Reasoning:   8%|▊         | 2946/37046 [00:14<08:57, 63.39it/s]

Reasoning:   8%|▊         | 2954/37046 [00:14<08:21, 67.96it/s]

Reasoning:   8%|▊         | 2961/37046 [00:14<08:17, 68.53it/s]

Reasoning:   8%|▊         | 2968/37046 [00:15<09:16, 61.24it/s]

Reasoning:   8%|▊         | 2975/37046 [00:15<09:31, 59.67it/s]

Reasoning:   8%|▊         | 2982/37046 [00:15<09:10, 61.86it/s]

Reasoning:   8%|▊         | 2989/37046 [00:15<09:46, 58.08it/s]

Reasoning:   8%|▊         | 2996/37046 [00:15<09:18, 60.92it/s]

Reasoning:   8%|▊         | 3005/37046 [00:15<08:35, 66.09it/s]

Reasoning:   8%|▊         | 3012/37046 [00:15<08:36, 65.93it/s]

Reasoning:   8%|▊         | 3020/37046 [00:15<08:16, 68.58it/s]

Reasoning:   8%|▊         | 3027/37046 [00:16<08:30, 66.69it/s]

Reasoning:   8%|▊         | 3034/37046 [00:16<08:36, 65.91it/s]

Reasoning:   8%|▊         | 3041/37046 [00:16<08:39, 65.45it/s]

Reasoning:   8%|▊         | 3048/37046 [00:16<08:31, 66.41it/s]

Reasoning:   8%|▊         | 3056/37046 [00:16<08:13, 68.94it/s]

Reasoning:   8%|▊         | 3063/37046 [00:16<08:27, 66.99it/s]

Reasoning:   8%|▊         | 3070/37046 [00:16<08:44, 64.81it/s]

Reasoning:   8%|▊         | 3077/37046 [00:16<08:48, 64.33it/s]

Reasoning:   8%|▊         | 3084/37046 [00:16<09:52, 57.35it/s]

Reasoning:   8%|▊         | 3090/37046 [00:17<10:13, 55.32it/s]

Reasoning:   8%|▊         | 3096/37046 [00:17<10:17, 55.02it/s]

Reasoning:   8%|▊         | 3102/37046 [00:17<10:12, 55.39it/s]

Reasoning:   8%|▊         | 3108/37046 [00:17<11:04, 51.05it/s]

Reasoning:   8%|▊         | 3128/37046 [00:17<06:21, 88.91it/s]

Reasoning:   9%|▊         | 3183/37046 [00:17<02:39, 212.58it/s]

Reasoning:   9%|▊         | 3239/37046 [00:17<01:49, 308.22it/s]

Reasoning:   9%|▉         | 3297/37046 [00:17<01:28, 380.51it/s]

Reasoning:   9%|▉         | 3361/37046 [00:17<01:14, 454.27it/s]

Reasoning:   9%|▉         | 3423/37046 [00:18<01:07, 500.66it/s]

Reasoning:   9%|▉         | 3481/37046 [00:18<01:04, 523.65it/s]

Reasoning:  10%|▉         | 3535/37046 [00:18<01:04, 515.94it/s]

Reasoning:  10%|▉         | 3588/37046 [00:18<01:04, 516.75it/s]

Reasoning:  10%|▉         | 3643/37046 [00:18<01:03, 526.43it/s]

Reasoning:  10%|▉         | 3696/37046 [00:18<01:05, 510.31it/s]

Reasoning:  10%|█         | 3751/37046 [00:18<01:03, 521.65it/s]

Reasoning:  10%|█         | 3814/37046 [00:18<01:00, 552.78it/s]

Reasoning:  10%|█         | 3871/37046 [00:18<01:00, 549.91it/s]

Reasoning:  11%|█         | 3927/37046 [00:19<01:10, 467.92it/s]

Reasoning:  11%|█         | 3976/37046 [00:19<01:23, 397.88it/s]

Reasoning:  11%|█         | 4019/37046 [00:19<01:34, 349.04it/s]

Reasoning:  11%|█         | 4057/37046 [00:19<01:38, 336.33it/s]

Reasoning:  11%|█         | 4093/37046 [00:19<01:44, 316.75it/s]

Reasoning:  11%|█         | 4126/37046 [00:19<01:52, 291.46it/s]

Reasoning:  11%|█         | 4157/37046 [00:19<01:54, 286.66it/s]

Reasoning:  11%|█▏        | 4187/37046 [00:19<01:56, 281.49it/s]

Reasoning:  11%|█▏        | 4216/37046 [00:20<01:58, 277.76it/s]

Reasoning:  11%|█▏        | 4246/37046 [00:20<01:56, 281.49it/s]

Reasoning:  12%|█▏        | 4275/37046 [00:20<01:58, 275.82it/s]

Reasoning:  12%|█▏        | 4303/37046 [00:20<02:08, 254.08it/s]

Reasoning:  12%|█▏        | 4331/37046 [00:20<02:05, 260.81it/s]

Reasoning:  12%|█▏        | 4358/37046 [00:20<02:11, 247.65it/s]

Reasoning:  12%|█▏        | 4384/37046 [00:20<02:17, 237.12it/s]

Reasoning:  12%|█▏        | 4408/37046 [00:20<02:19, 233.95it/s]

Reasoning:  12%|█▏        | 4432/37046 [00:20<02:22, 229.05it/s]

Reasoning:  12%|█▏        | 4455/37046 [00:21<02:24, 225.96it/s]

Reasoning:  12%|█▏        | 4481/37046 [00:21<02:20, 232.35it/s]

Reasoning:  12%|█▏        | 4505/37046 [00:21<02:21, 229.86it/s]

Reasoning:  12%|█▏        | 4529/37046 [00:21<02:20, 231.74it/s]

Reasoning:  12%|█▏        | 4553/37046 [00:21<02:20, 231.82it/s]

Reasoning:  12%|█▏        | 4579/37046 [00:21<02:17, 235.67it/s]

Reasoning:  12%|█▏        | 4603/37046 [00:21<02:16, 236.89it/s]

Reasoning:  12%|█▏        | 4627/37046 [00:21<02:20, 230.82it/s]

Reasoning:  13%|█▎        | 4651/37046 [00:21<02:30, 215.79it/s]

Reasoning:  13%|█▎        | 4680/37046 [00:22<02:18, 232.99it/s]

Reasoning:  13%|█▎        | 4725/37046 [00:22<01:50, 293.61it/s]

Reasoning:  13%|█▎        | 4768/37046 [00:22<01:37, 332.45it/s]

Reasoning:  13%|█▎        | 4818/37046 [00:22<01:24, 379.68it/s]

Reasoning:  13%|█▎        | 4867/37046 [00:22<01:18, 411.22it/s]

Reasoning:  13%|█▎        | 4917/37046 [00:22<01:14, 433.02it/s]

Reasoning:  13%|█▎        | 4963/37046 [00:22<01:12, 440.87it/s]

Reasoning:  14%|█▎        | 5009/37046 [00:22<01:11, 445.86it/s]

Reasoning:  14%|█▎        | 5060/37046 [00:22<01:08, 463.75it/s]

Reasoning:  14%|█▍        | 5107/37046 [00:23<01:14, 429.54it/s]

Reasoning:  14%|█▍        | 5151/37046 [00:23<01:19, 402.00it/s]

Reasoning:  14%|█▍        | 5192/37046 [00:23<01:26, 370.20it/s]

Reasoning:  14%|█▍        | 5230/37046 [00:23<01:30, 350.54it/s]

Reasoning:  14%|█▍        | 5267/37046 [00:23<01:30, 352.07it/s]

Reasoning:  14%|█▍        | 5303/37046 [00:23<01:36, 329.81it/s]

Reasoning:  14%|█▍        | 5337/37046 [00:23<01:39, 320.20it/s]

Reasoning:  15%|█▍        | 5375/37046 [00:23<01:34, 335.47it/s]

Reasoning:  15%|█▍        | 5409/37046 [00:23<01:35, 329.95it/s]

Reasoning:  15%|█▍        | 5443/37046 [00:24<01:34, 332.70it/s]

Reasoning:  15%|█▍        | 5477/37046 [00:24<01:54, 276.59it/s]

Reasoning:  15%|█▍        | 5507/37046 [00:24<02:11, 240.37it/s]

Reasoning:  15%|█▍        | 5533/37046 [00:24<02:27, 214.09it/s]

Reasoning:  15%|█▍        | 5556/37046 [00:24<02:47, 187.64it/s]

Reasoning:  15%|█▌        | 5577/37046 [00:24<03:05, 169.36it/s]

Reasoning:  15%|█▌        | 5595/37046 [00:25<03:09, 165.68it/s]

Reasoning:  15%|█▌        | 5613/37046 [00:25<03:06, 168.93it/s]

Reasoning:  15%|█▌        | 5631/37046 [00:25<03:14, 161.43it/s]

Reasoning:  15%|█▌        | 5648/37046 [00:25<03:18, 158.54it/s]

Reasoning:  15%|█▌        | 5666/37046 [00:25<03:11, 163.95it/s]

Reasoning:  15%|█▌        | 5683/37046 [00:25<03:09, 165.53it/s]

Reasoning:  15%|█▌        | 5700/37046 [00:25<03:16, 159.59it/s]

Reasoning:  15%|█▌        | 5719/37046 [00:25<03:10, 164.68it/s]

Reasoning:  15%|█▌        | 5741/37046 [00:25<03:01, 172.28it/s]

Reasoning:  16%|█▌        | 5759/37046 [00:26<03:16, 159.59it/s]

Reasoning:  16%|█▌        | 5780/37046 [00:26<03:03, 170.78it/s]

Reasoning:  16%|█▌        | 5798/37046 [00:26<03:09, 165.17it/s]

Reasoning:  16%|█▌        | 5815/37046 [00:26<03:27, 150.78it/s]

Reasoning:  16%|█▌        | 5831/37046 [00:26<03:35, 144.96it/s]

Reasoning:  16%|█▌        | 5854/37046 [00:26<03:06, 166.83it/s]

Reasoning:  16%|█▌        | 5894/37046 [00:26<02:15, 229.57it/s]

Reasoning:  16%|█▌        | 5938/37046 [00:26<01:48, 285.85it/s]

Reasoning:  16%|█▌        | 5979/37046 [00:26<01:37, 318.87it/s]

Reasoning:  16%|█▋        | 6027/37046 [00:27<01:25, 360.79it/s]

Reasoning:  16%|█▋        | 6068/37046 [00:27<01:22, 374.21it/s]

Reasoning:  16%|█▋        | 6107/37046 [00:27<01:23, 372.05it/s]

Reasoning:  17%|█▋        | 6150/37046 [00:27<01:19, 386.73it/s]

Reasoning:  17%|█▋        | 6191/37046 [00:27<01:19, 389.64it/s]

Reasoning:  17%|█▋        | 6231/37046 [00:27<01:19, 386.61it/s]

Reasoning:  17%|█▋        | 6270/37046 [00:27<01:39, 308.05it/s]

Reasoning:  17%|█▋        | 6304/37046 [00:27<01:52, 273.96it/s]

Reasoning:  17%|█▋        | 6334/37046 [00:28<02:27, 208.89it/s]

Reasoning:  17%|█▋        | 6359/37046 [00:28<02:29, 205.64it/s]

Reasoning:  17%|█▋        | 6382/37046 [00:28<02:30, 203.21it/s]

Reasoning:  17%|█▋        | 6404/37046 [00:28<02:33, 199.80it/s]

Reasoning:  17%|█▋        | 6426/37046 [00:28<02:31, 202.18it/s]

Reasoning:  17%|█▋        | 6456/37046 [00:28<02:15, 226.50it/s]

Reasoning:  17%|█▋        | 6482/37046 [00:28<02:09, 235.34it/s]

Reasoning:  18%|█▊        | 6507/37046 [00:28<02:15, 225.93it/s]

Reasoning:  18%|█▊        | 6531/37046 [00:29<02:17, 222.65it/s]

Reasoning:  18%|█▊        | 6555/37046 [00:29<02:15, 224.31it/s]

Reasoning:  18%|█▊        | 6579/37046 [00:29<02:16, 223.94it/s]

Reasoning:  18%|█▊        | 6602/37046 [00:29<02:16, 223.06it/s]

Reasoning:  18%|█▊        | 6625/37046 [00:29<02:42, 187.20it/s]

Reasoning:  18%|█▊        | 6645/37046 [00:29<03:51, 131.40it/s]

Reasoning:  18%|█▊        | 6661/37046 [00:30<04:40, 108.21it/s]

Reasoning:  18%|█▊        | 6675/37046 [00:30<05:06, 99.05it/s]

Reasoning:  18%|█▊        | 6687/37046 [00:30<05:40, 89.12it/s]

Reasoning:  18%|█▊        | 6698/37046 [00:30<06:17, 80.49it/s]

Reasoning:  18%|█▊        | 6708/37046 [00:30<06:14, 80.92it/s]

Reasoning:  18%|█▊        | 6717/37046 [00:30<06:45, 74.77it/s]

Reasoning:  18%|█▊        | 6725/37046 [00:30<07:08, 70.75it/s]

Reasoning:  18%|█▊        | 6733/37046 [00:31<07:14, 69.74it/s]

Reasoning:  18%|█▊        | 6743/37046 [00:31<06:39, 75.80it/s]

Reasoning:  18%|█▊        | 6753/37046 [00:31<06:17, 80.28it/s]

Reasoning:  18%|█▊        | 6762/37046 [00:31<07:20, 68.71it/s]

Reasoning:  18%|█▊        | 6770/37046 [00:31<07:12, 70.06it/s]

Reasoning:  18%|█▊        | 6778/37046 [00:31<07:31, 67.11it/s]

Reasoning:  18%|█▊        | 6785/37046 [00:31<08:17, 60.86it/s]

Reasoning:  18%|█▊        | 6792/37046 [00:31<08:23, 60.03it/s]

Reasoning:  18%|█▊        | 6801/37046 [00:32<07:28, 67.39it/s]

Reasoning:  18%|█▊        | 6808/37046 [00:32<07:30, 67.15it/s]

Reasoning:  18%|█▊        | 6817/37046 [00:32<07:02, 71.53it/s]

Reasoning:  18%|█▊        | 6825/37046 [00:32<07:08, 70.57it/s]

Reasoning:  18%|█▊        | 6833/37046 [00:32<07:08, 70.56it/s]

Reasoning:  18%|█▊        | 6841/37046 [00:32<07:11, 70.04it/s]

Reasoning:  18%|█▊        | 6849/37046 [00:32<07:13, 69.68it/s]

Reasoning:  19%|█▊        | 6857/37046 [00:32<07:23, 68.13it/s]

Reasoning:  19%|█▊        | 6865/37046 [00:33<07:09, 70.33it/s]

Reasoning:  19%|█▊        | 6873/37046 [00:33<07:14, 69.43it/s]

Reasoning:  19%|█▊        | 6880/37046 [00:33<07:16, 69.08it/s]

Reasoning:  19%|█▊        | 6889/37046 [00:33<06:52, 73.15it/s]

Reasoning:  19%|█▊        | 6898/37046 [00:33<06:30, 77.14it/s]

Reasoning:  19%|█▊        | 6906/37046 [00:33<06:39, 75.39it/s]

Reasoning:  19%|█▊        | 6914/37046 [00:33<06:56, 72.27it/s]

Reasoning:  19%|█▊        | 6922/37046 [00:33<07:21, 68.21it/s]

Reasoning:  19%|█▊        | 6931/37046 [00:33<07:00, 71.69it/s]

Reasoning:  19%|█▊        | 6939/37046 [00:34<06:52, 72.92it/s]

Reasoning:  19%|█▉        | 6947/37046 [00:34<07:11, 69.68it/s]

Reasoning:  19%|█▉        | 6955/37046 [00:34<07:39, 65.49it/s]

Reasoning:  19%|█▉        | 6962/37046 [00:34<07:36, 65.85it/s]

Reasoning:  19%|█▉        | 6969/37046 [00:34<07:37, 65.81it/s]

Reasoning:  19%|█▉        | 6976/37046 [00:34<07:41, 65.11it/s]

Reasoning:  19%|█▉        | 6983/37046 [00:34<07:42, 65.03it/s]

Reasoning:  19%|█▉        | 6990/37046 [00:34<07:51, 63.68it/s]

Reasoning:  19%|█▉        | 6999/37046 [00:34<07:24, 67.58it/s]

Reasoning:  19%|█▉        | 7006/37046 [00:35<07:30, 66.61it/s]

Reasoning:  19%|█▉        | 7061/37046 [00:35<02:30, 199.62it/s]

Reasoning:  19%|█▉        | 7117/37046 [00:35<01:39, 300.96it/s]

Reasoning:  19%|█▉        | 7179/37046 [00:35<01:17, 387.72it/s]

Reasoning:  20%|█▉        | 7238/37046 [00:35<01:07, 443.93it/s]

Reasoning:  20%|█▉        | 7292/37046 [00:35<01:03, 471.25it/s]

Reasoning:  20%|█▉        | 7351/37046 [00:35<00:58, 505.50it/s]

Reasoning:  20%|██        | 7412/37046 [00:35<00:56, 529.16it/s]

Reasoning:  20%|██        | 7466/37046 [00:35<00:58, 507.32it/s]

Reasoning:  20%|██        | 7518/37046 [00:36<00:59, 494.58it/s]

Reasoning:  20%|██        | 7573/37046 [00:36<00:59, 495.98it/s]

Reasoning:  21%|██        | 7623/37046 [00:36<01:00, 487.88it/s]

Reasoning:  21%|██        | 7676/37046 [00:36<00:58, 499.80it/s]

Reasoning:  21%|██        | 7727/37046 [00:36<00:59, 488.78it/s]

Reasoning:  21%|██        | 7780/37046 [00:36<00:59, 491.37it/s]

Reasoning:  21%|██        | 7845/37046 [00:36<00:54, 536.68it/s]

Reasoning:  21%|██▏       | 7899/37046 [00:36<00:55, 526.88it/s]

Reasoning:  21%|██▏       | 7958/37046 [00:36<00:53, 539.89it/s]

Reasoning:  22%|██▏       | 8013/37046 [00:36<00:56, 517.46it/s]

Reasoning:  22%|██▏       | 8069/37046 [00:37<00:55, 522.41it/s]

Reasoning:  22%|██▏       | 8128/37046 [00:37<00:54, 531.01it/s]

Reasoning:  22%|██▏       | 8182/37046 [00:37<00:54, 526.38it/s]

Reasoning:  22%|██▏       | 8250/37046 [00:37<00:50, 567.21it/s]

Reasoning:  22%|██▏       | 8312/37046 [00:37<00:49, 578.74it/s]

Reasoning:  23%|██▎       | 8378/37046 [00:37<00:47, 601.71it/s]

Reasoning:  23%|██▎       | 8441/37046 [00:37<00:47, 606.52it/s]

Reasoning:  23%|██▎       | 8504/37046 [00:37<00:46, 613.14it/s]

Reasoning:  23%|██▎       | 8566/37046 [00:37<00:47, 602.92it/s]

Reasoning:  23%|██▎       | 8636/37046 [00:37<00:45, 630.36it/s]

Reasoning:  23%|██▎       | 8700/37046 [00:38<00:59, 478.85it/s]

Reasoning:  24%|██▎       | 8765/37046 [00:38<00:54, 520.14it/s]

Reasoning:  24%|██▍       | 8827/37046 [00:38<00:52, 539.56it/s]

Reasoning:  24%|██▍       | 8885/37046 [00:38<00:57, 490.75it/s]

Reasoning:  24%|██▍       | 8946/37046 [00:38<00:53, 520.84it/s]

Reasoning:  24%|██▍       | 9010/37046 [00:38<00:50, 551.27it/s]

Reasoning:  24%|██▍       | 9068/37046 [00:38<00:52, 528.19it/s]

Reasoning:  25%|██▍       | 9123/37046 [00:38<00:54, 511.28it/s]

Reasoning:  25%|██▍       | 9196/37046 [00:39<00:48, 569.79it/s]

Reasoning:  25%|██▍       | 9260/37046 [00:39<00:47, 581.72it/s]

Reasoning:  25%|██▌       | 9320/37046 [00:39<00:47, 586.45it/s]

Reasoning:  25%|██▌       | 9380/37046 [00:39<00:56, 491.73it/s]

Reasoning:  25%|██▌       | 9433/37046 [00:39<01:01, 446.35it/s]

Reasoning:  26%|██▌       | 9481/37046 [00:39<01:06, 415.19it/s]

Reasoning:  26%|██▌       | 9525/37046 [00:40<01:30, 303.91it/s]

Reasoning:  26%|██▌       | 9561/37046 [00:40<01:27, 315.02it/s]

Reasoning:  26%|██▌       | 9601/37046 [00:40<01:23, 328.08it/s]

Reasoning:  26%|██▌       | 9638/37046 [00:40<01:24, 324.72it/s]

Reasoning:  26%|██▌       | 9673/37046 [00:40<01:23, 328.24it/s]

Reasoning:  26%|██▌       | 9708/37046 [00:40<01:21, 333.85it/s]

Reasoning:  26%|██▋       | 9743/37046 [00:40<01:26, 314.30it/s]

Reasoning:  26%|██▋       | 9776/37046 [00:40<01:40, 270.82it/s]

Reasoning:  26%|██▋       | 9805/37046 [00:40<01:49, 249.70it/s]

Reasoning:  27%|██▋       | 9832/37046 [00:41<02:08, 211.25it/s]

Reasoning:  27%|██▋       | 9855/37046 [00:41<02:12, 205.78it/s]

Reasoning:  27%|██▋       | 9877/37046 [00:41<02:20, 193.79it/s]

Reasoning:  27%|██▋       | 9898/37046 [00:41<02:17, 197.38it/s]

Reasoning:  27%|██▋       | 9922/37046 [00:41<02:12, 204.94it/s]

Reasoning:  27%|██▋       | 9945/37046 [00:41<02:10, 207.53it/s]

Reasoning:  27%|██▋       | 9968/37046 [00:41<02:07, 211.81it/s]

Reasoning:  27%|██▋       | 9992/37046 [00:41<02:06, 213.62it/s]

Reasoning:  27%|██▋       | 10014/37046 [00:42<02:07, 211.53it/s]

Reasoning:  27%|██▋       | 10036/37046 [00:42<02:06, 213.67it/s]

Reasoning:  27%|██▋       | 10058/37046 [00:42<02:08, 210.01it/s]

Reasoning:  27%|██▋       | 10080/37046 [00:42<02:09, 207.57it/s]

Reasoning:  27%|██▋       | 10102/37046 [00:42<02:10, 206.49it/s]

Reasoning:  27%|██▋       | 10124/37046 [00:42<02:08, 210.15it/s]

Reasoning:  27%|██▋       | 10177/37046 [00:42<01:30, 298.19it/s]

Reasoning:  28%|██▊       | 10221/37046 [00:42<01:19, 336.92it/s]

Reasoning:  28%|██▊       | 10271/37046 [00:42<01:10, 378.65it/s]

Reasoning:  28%|██▊       | 10323/37046 [00:42<01:03, 418.96it/s]

Reasoning:  28%|██▊       | 10374/37046 [00:43<01:00, 439.68it/s]

Reasoning:  28%|██▊       | 10422/37046 [00:43<00:59, 450.50it/s]

Reasoning:  28%|██▊       | 10470/37046 [00:43<00:58, 451.52it/s]

Reasoning:  28%|██▊       | 10516/37046 [00:43<00:58, 453.98it/s]

Reasoning:  29%|██▊       | 10562/37046 [00:43<01:05, 404.09it/s]

Reasoning:  29%|██▊       | 10604/37046 [00:43<01:05, 401.11it/s]

Reasoning:  29%|██▊       | 10645/37046 [00:43<01:12, 364.46it/s]

Reasoning:  29%|██▉       | 10683/37046 [00:43<01:13, 357.65it/s]

Reasoning:  29%|██▉       | 10721/37046 [00:44<01:13, 358.70it/s]

Reasoning:  29%|██▉       | 10759/37046 [00:44<01:13, 359.73it/s]

Reasoning:  29%|██▉       | 10796/37046 [00:44<01:16, 341.72it/s]

Reasoning:  29%|██▉       | 10839/37046 [00:44<01:11, 364.41it/s]

Reasoning:  29%|██▉       | 10881/37046 [00:44<01:09, 374.75it/s]

Reasoning:  29%|██▉       | 10919/37046 [00:44<01:25, 304.23it/s]

Reasoning:  30%|██▉       | 10952/37046 [00:44<01:51, 233.91it/s]

Reasoning:  30%|██▉       | 10980/37046 [00:45<02:14, 194.12it/s]

Reasoning:  30%|██▉       | 11003/37046 [00:45<02:40, 162.40it/s]

Reasoning:  30%|██▉       | 11023/37046 [00:45<02:55, 148.34it/s]

Reasoning:  30%|██▉       | 11040/37046 [00:45<03:11, 135.61it/s]

Reasoning:  30%|██▉       | 11055/37046 [00:45<03:13, 134.06it/s]

Reasoning:  30%|██▉       | 11070/37046 [00:45<03:19, 129.90it/s]

Reasoning:  30%|██▉       | 11084/37046 [00:46<03:22, 128.50it/s]

Reasoning:  30%|██▉       | 11101/37046 [00:46<03:09, 136.89it/s]

Reasoning:  30%|███       | 11116/37046 [00:46<03:07, 138.33it/s]

Reasoning:  30%|███       | 11131/37046 [00:46<03:06, 138.66it/s]

Reasoning:  30%|███       | 11147/37046 [00:46<03:03, 140.92it/s]

Reasoning:  30%|███       | 11162/37046 [00:46<03:21, 128.31it/s]

Reasoning:  30%|███       | 11176/37046 [00:46<03:34, 120.48it/s]

Reasoning:  30%|███       | 11191/37046 [00:46<03:22, 127.81it/s]

Reasoning:  30%|███       | 11205/37046 [00:46<03:32, 121.69it/s]

Reasoning:  30%|███       | 11219/37046 [00:47<03:26, 125.06it/s]

Reasoning:  30%|███       | 11237/37046 [00:47<03:06, 138.05it/s]

Reasoning:  30%|███       | 11255/37046 [00:47<02:52, 149.26it/s]

Reasoning:  30%|███       | 11271/37046 [00:47<03:06, 138.10it/s]

Reasoning:  30%|███       | 11286/37046 [00:47<03:06, 138.21it/s]

Reasoning:  31%|███       | 11313/37046 [00:47<02:29, 171.82it/s]

Reasoning:  31%|███       | 11362/37046 [00:47<01:40, 254.80it/s]

Reasoning:  31%|███       | 11410/37046 [00:47<01:21, 313.95it/s]

Reasoning:  31%|███       | 11456/37046 [00:47<01:12, 354.74it/s]

Reasoning:  31%|███       | 11501/37046 [00:48<01:07, 376.99it/s]

Reasoning:  31%|███       | 11545/37046 [00:48<01:05, 387.93it/s]

Reasoning:  31%|███▏      | 11594/37046 [00:48<01:01, 415.36it/s]

Reasoning:  31%|███▏      | 11637/37046 [00:48<01:01, 416.29it/s]

Reasoning:  32%|███▏      | 11679/37046 [00:48<01:00, 416.14it/s]

Reasoning:  32%|███▏      | 11721/37046 [00:48<01:20, 315.40it/s]

Reasoning:  32%|███▏      | 11757/37046 [00:48<01:35, 265.82it/s]

Reasoning:  32%|███▏      | 11788/37046 [00:48<01:44, 242.38it/s]

Reasoning:  32%|███▏      | 11815/37046 [00:49<01:51, 226.36it/s]

Reasoning:  32%|███▏      | 11840/37046 [00:49<01:51, 226.06it/s]

Reasoning:  32%|███▏      | 11867/37046 [00:49<01:48, 232.71it/s]

Reasoning:  32%|███▏      | 11892/37046 [00:49<01:53, 222.52it/s]

Reasoning:  32%|███▏      | 11915/37046 [00:49<01:58, 212.29it/s]

Reasoning:  32%|███▏      | 11937/37046 [00:49<02:00, 208.40it/s]

Reasoning:  32%|███▏      | 11960/37046 [00:49<01:58, 210.83it/s]

Reasoning:  32%|███▏      | 11982/37046 [00:49<02:02, 204.11it/s]

Reasoning:  32%|███▏      | 12003/37046 [00:50<02:03, 203.46it/s]

Reasoning:  32%|███▏      | 12026/37046 [00:50<02:00, 207.37it/s]

Reasoning:  33%|███▎      | 12047/37046 [00:50<02:04, 201.59it/s]

Reasoning:  33%|███▎      | 12068/37046 [00:50<02:06, 196.72it/s]

Reasoning:  33%|███▎      | 12088/37046 [00:50<03:27, 120.15it/s]

Reasoning:  33%|███▎      | 12104/37046 [00:50<04:07, 100.88it/s]

Reasoning:  33%|███▎      | 12117/37046 [00:51<04:27, 93.05it/s]

Reasoning:  33%|███▎      | 12129/37046 [00:51<04:57, 83.64it/s]

Reasoning:  33%|███▎      | 12139/37046 [00:51<05:13, 79.45it/s]

Reasoning:  33%|███▎      | 12148/37046 [00:51<05:36, 73.92it/s]

Reasoning:  33%|███▎      | 12156/37046 [00:51<06:18, 65.79it/s]

Reasoning:  33%|███▎      | 12163/37046 [00:51<06:33, 63.17it/s]

Reasoning:  33%|███▎      | 12170/37046 [00:52<07:01, 59.02it/s]

Reasoning:  33%|███▎      | 12177/37046 [00:52<06:53, 60.11it/s]

Reasoning:  33%|███▎      | 12184/37046 [00:52<07:02, 58.88it/s]

Reasoning:  33%|███▎      | 12191/37046 [00:52<06:57, 59.47it/s]

Reasoning:  33%|███▎      | 12198/37046 [00:52<06:56, 59.62it/s]

Reasoning:  33%|███▎      | 12205/37046 [00:52<07:23, 55.96it/s]

Reasoning:  33%|███▎      | 12211/37046 [00:52<07:40, 53.91it/s]

Reasoning:  33%|███▎      | 12218/37046 [00:52<07:08, 57.93it/s]

Reasoning:  33%|███▎      | 12224/37046 [00:53<07:23, 56.00it/s]

Reasoning:  33%|███▎      | 12232/37046 [00:53<06:55, 59.73it/s]

Reasoning:  33%|███▎      | 12239/37046 [00:53<07:24, 55.82it/s]

Reasoning:  33%|███▎      | 12246/37046 [00:53<06:57, 59.37it/s]

Reasoning:  33%|███▎      | 12255/37046 [00:53<06:23, 64.62it/s]

Reasoning:  33%|███▎      | 12262/37046 [00:53<06:20, 65.18it/s]

Reasoning:  33%|███▎      | 12270/37046 [00:53<06:02, 68.29it/s]

Reasoning:  33%|███▎      | 12277/37046 [00:53<06:56, 59.44it/s]

Reasoning:  33%|███▎      | 12285/37046 [00:53<06:25, 64.29it/s]

Reasoning:  33%|███▎      | 12292/37046 [00:54<06:47, 60.79it/s]

Reasoning:  33%|███▎      | 12300/37046 [00:54<06:21, 64.87it/s]

Reasoning:  33%|███▎      | 12307/37046 [00:54<06:30, 63.39it/s]

Reasoning:  33%|███▎      | 12314/37046 [00:54<06:31, 63.19it/s]

Reasoning:  33%|███▎      | 12322/37046 [00:54<06:14, 65.99it/s]

Reasoning:  33%|███▎      | 12329/37046 [00:54<06:15, 65.89it/s]

Reasoning:  33%|███▎      | 12337/37046 [00:54<06:03, 68.05it/s]

Reasoning:  33%|███▎      | 12345/37046 [00:54<06:00, 68.57it/s]

Reasoning:  33%|███▎      | 12354/37046 [00:54<05:45, 71.57it/s]

Reasoning:  33%|███▎      | 12362/37046 [00:55<05:51, 70.29it/s]

Reasoning:  33%|███▎      | 12370/37046 [00:55<06:21, 64.72it/s]

Reasoning:  33%|███▎      | 12377/37046 [00:55<06:23, 64.30it/s]

Reasoning:  33%|███▎      | 12385/37046 [00:55<06:11, 66.42it/s]

Reasoning:  33%|███▎      | 12394/37046 [00:55<05:41, 72.13it/s]

Reasoning:  33%|███▎      | 12402/37046 [00:55<05:40, 72.40it/s]

Reasoning:  33%|███▎      | 12410/37046 [00:55<06:44, 60.86it/s]

Reasoning:  34%|███▎      | 12417/37046 [00:56<07:13, 56.84it/s]

Reasoning:  34%|███▎      | 12423/37046 [00:56<07:36, 53.92it/s]

Reasoning:  34%|███▎      | 12429/37046 [00:56<08:08, 50.43it/s]

Reasoning:  34%|███▎      | 12435/37046 [00:56<08:53, 46.10it/s]

Reasoning:  34%|███▎      | 12440/37046 [00:56<09:12, 44.55it/s]

Reasoning:  34%|███▎      | 12445/37046 [00:56<09:08, 44.86it/s]

Reasoning:  34%|███▎      | 12450/37046 [00:56<10:53, 37.64it/s]

Reasoning:  34%|███▎      | 12456/37046 [00:56<09:50, 41.67it/s]

Reasoning:  34%|███▎      | 12497/37046 [00:57<03:09, 129.71it/s]

Reasoning:  34%|███▍      | 12552/37046 [00:57<01:45, 232.87it/s]

Reasoning:  34%|███▍      | 12604/37046 [00:57<01:20, 304.38it/s]

Reasoning:  34%|███▍      | 12652/37046 [00:57<01:10, 347.43it/s]

Reasoning:  34%|███▍      | 12698/37046 [00:57<01:05, 373.35it/s]

Reasoning:  34%|███▍      | 12740/37046 [00:57<01:03, 385.76it/s]

Reasoning:  35%|███▍      | 12782/37046 [00:57<01:01, 395.47it/s]

Reasoning:  35%|███▍      | 12830/37046 [00:58<01:47, 224.32it/s]

Reasoning:  35%|███▍      | 12874/37046 [00:58<01:31, 263.33it/s]

Reasoning:  35%|███▍      | 12910/37046 [00:58<01:27, 277.14it/s]

Reasoning:  35%|███▍      | 12945/37046 [00:58<01:26, 279.87it/s]

Reasoning:  35%|███▌      | 12987/37046 [00:58<01:17, 311.54it/s]

Reasoning:  35%|███▌      | 13023/37046 [00:58<01:19, 303.30it/s]

Reasoning:  35%|███▌      | 13057/37046 [00:58<01:22, 290.69it/s]

Reasoning:  35%|███▌      | 13089/37046 [00:58<01:24, 283.65it/s]

Reasoning:  35%|███▌      | 13120/37046 [00:59<01:23, 285.75it/s]

Reasoning:  36%|███▌      | 13154/37046 [00:59<01:19, 299.73it/s]

Reasoning:  36%|███▌      | 13185/37046 [00:59<01:21, 294.49it/s]

Reasoning:  36%|███▌      | 13221/37046 [00:59<01:16, 312.25it/s]

Reasoning:  36%|███▌      | 13256/37046 [00:59<01:13, 322.80it/s]

Reasoning:  36%|███▌      | 13289/37046 [00:59<01:19, 300.71it/s]

Reasoning:  36%|███▌      | 13325/37046 [00:59<01:14, 316.83it/s]

Reasoning:  36%|███▌      | 13367/37046 [00:59<01:08, 344.98it/s]

Reasoning:  36%|███▌      | 13414/37046 [00:59<01:02, 379.16it/s]

Reasoning:  36%|███▋      | 13453/37046 [00:59<01:05, 361.79it/s]

Reasoning:  36%|███▋      | 13500/37046 [01:00<01:01, 385.59it/s]

Reasoning:  37%|███▋      | 13547/37046 [01:00<00:57, 409.40it/s]

Reasoning:  37%|███▋      | 13589/37046 [01:00<00:58, 400.06it/s]

Reasoning:  37%|███▋      | 13638/37046 [01:00<00:55, 425.51it/s]

Reasoning:  37%|███▋      | 13681/37046 [01:00<00:55, 424.44it/s]

Reasoning:  37%|███▋      | 13724/37046 [01:00<01:07, 345.40it/s]

Reasoning:  37%|███▋      | 13762/37046 [01:00<01:09, 334.79it/s]

Reasoning:  37%|███▋      | 13799/37046 [01:00<01:07, 342.85it/s]

Reasoning:  37%|███▋      | 13841/37046 [01:00<01:03, 363.28it/s]

Reasoning:  37%|███▋      | 13880/37046 [01:01<01:02, 370.56it/s]

Reasoning:  38%|███▊      | 13918/37046 [01:01<01:03, 362.44it/s]

Reasoning:  38%|███▊      | 13959/37046 [01:01<01:01, 375.34it/s]

Reasoning:  38%|███▊      | 13998/37046 [01:01<01:01, 373.38it/s]

Reasoning:  38%|███▊      | 14036/37046 [01:01<01:08, 337.67it/s]

Reasoning:  38%|███▊      | 14071/37046 [01:01<01:14, 309.25it/s]

Reasoning:  38%|███▊      | 14103/37046 [01:01<01:21, 282.54it/s]

Reasoning:  38%|███▊      | 14133/37046 [01:01<01:25, 267.82it/s]

Reasoning:  38%|███▊      | 14161/37046 [01:02<01:26, 264.38it/s]

Reasoning:  38%|███▊      | 14188/37046 [01:02<01:31, 248.70it/s]

Reasoning:  38%|███▊      | 14214/37046 [01:02<01:48, 210.88it/s]

Reasoning:  38%|███▊      | 14237/37046 [01:02<01:52, 202.63it/s]

Reasoning:  38%|███▊      | 14261/37046 [01:02<01:47, 211.40it/s]

Reasoning:  39%|███▊      | 14284/37046 [01:02<01:45, 215.87it/s]

Reasoning:  39%|███▊      | 14308/37046 [01:02<01:43, 219.66it/s]

Reasoning:  39%|███▊      | 14331/37046 [01:02<01:43, 218.75it/s]

Reasoning:  39%|███▊      | 14355/37046 [01:03<01:42, 221.22it/s]

Reasoning:  39%|███▉      | 14378/37046 [01:03<01:45, 214.37it/s]

Reasoning:  39%|███▉      | 14400/37046 [01:03<01:49, 205.95it/s]

Reasoning:  39%|███▉      | 14421/37046 [01:03<01:56, 194.52it/s]

Reasoning:  39%|███▉      | 14441/37046 [01:03<02:01, 185.70it/s]

Reasoning:  39%|███▉      | 14460/37046 [01:03<02:04, 181.24it/s]

Reasoning:  39%|███▉      | 14479/37046 [01:03<02:10, 173.18it/s]

Reasoning:  39%|███▉      | 14497/37046 [01:03<02:20, 160.70it/s]

Reasoning:  39%|███▉      | 14514/37046 [01:03<02:26, 153.60it/s]

Reasoning:  39%|███▉      | 14530/37046 [01:04<02:26, 153.77it/s]

Reasoning:  39%|███▉      | 14549/37046 [01:04<02:17, 163.30it/s]

Reasoning:  39%|███▉      | 14569/37046 [01:04<02:11, 171.03it/s]

Reasoning:  39%|███▉      | 14589/37046 [01:04<02:05, 179.15it/s]

Reasoning:  39%|███▉      | 14611/37046 [01:04<01:59, 187.51it/s]

Reasoning:  39%|███▉      | 14630/37046 [01:04<02:02, 182.80it/s]

Reasoning:  40%|███▉      | 14649/37046 [01:04<02:03, 180.80it/s]

Reasoning:  40%|███▉      | 14668/37046 [01:04<02:05, 178.92it/s]

Reasoning:  40%|███▉      | 14688/37046 [01:04<02:01, 184.72it/s]

Reasoning:  40%|███▉      | 14711/37046 [01:05<01:52, 197.67it/s]

Reasoning:  40%|███▉      | 14733/37046 [01:05<01:52, 197.55it/s]

Reasoning:  40%|███▉      | 14753/37046 [01:05<01:57, 189.41it/s]

Reasoning:  40%|███▉      | 14773/37046 [01:05<01:57, 189.47it/s]

Reasoning:  40%|███▉      | 14794/37046 [01:05<01:55, 192.59it/s]

Reasoning:  40%|████      | 14839/37046 [01:05<01:23, 265.75it/s]

Reasoning:  40%|████      | 14881/37046 [01:05<01:11, 309.48it/s]

Reasoning:  40%|████      | 14919/37046 [01:05<01:07, 329.23it/s]

Reasoning:  40%|████      | 14969/37046 [01:05<00:58, 374.23it/s]

Reasoning:  41%|████      | 15012/37046 [01:05<00:56, 390.26it/s]

Reasoning:  41%|████      | 15052/37046 [01:06<00:57, 380.68it/s]

Reasoning:  41%|████      | 15091/37046 [01:06<01:00, 365.71it/s]

Reasoning:  41%|████      | 15132/37046 [01:06<00:57, 378.21it/s]

Reasoning:  41%|████      | 15171/37046 [01:06<00:59, 370.06it/s]

Reasoning:  41%|████      | 15209/37046 [01:06<01:04, 336.47it/s]

Reasoning:  41%|████      | 15244/37046 [01:06<01:10, 310.77it/s]

Reasoning:  41%|████      | 15276/37046 [01:06<01:13, 296.45it/s]

Reasoning:  41%|████▏     | 15307/37046 [01:06<01:14, 291.37it/s]

Reasoning:  41%|████▏     | 15337/37046 [01:07<01:15, 286.49it/s]

Reasoning:  41%|████▏     | 15366/37046 [01:07<01:15, 286.69it/s]

Reasoning:  42%|████▏     | 15395/37046 [01:07<01:19, 273.87it/s]

Reasoning:  42%|████▏     | 15423/37046 [01:07<01:21, 264.06it/s]

Reasoning:  42%|████▏     | 15450/37046 [01:07<01:23, 257.75it/s]

Reasoning:  42%|████▏     | 15477/37046 [01:07<01:23, 257.59it/s]

Reasoning:  42%|████▏     | 15503/37046 [01:07<01:23, 257.20it/s]

Reasoning:  42%|████▏     | 15529/37046 [01:07<01:25, 250.83it/s]

Reasoning:  42%|████▏     | 15555/37046 [01:07<01:24, 253.42it/s]

Reasoning:  42%|████▏     | 15581/37046 [01:08<01:33, 229.66it/s]

Reasoning:  42%|████▏     | 15605/37046 [01:08<01:46, 201.57it/s]

Reasoning:  42%|████▏     | 15626/37046 [01:08<01:50, 193.29it/s]

Reasoning:  42%|████▏     | 15646/37046 [01:08<02:01, 175.51it/s]

Reasoning:  42%|████▏     | 15665/37046 [01:08<02:14, 159.05it/s]

Reasoning:  42%|████▏     | 15682/37046 [01:08<02:31, 141.15it/s]

Reasoning:  42%|████▏     | 15698/37046 [01:08<02:30, 141.83it/s]

Reasoning:  42%|████▏     | 15713/37046 [01:08<02:34, 138.22it/s]

Reasoning:  42%|████▏     | 15728/37046 [01:09<02:31, 141.14it/s]

Reasoning:  42%|████▏     | 15743/37046 [01:09<02:39, 133.67it/s]

Reasoning:  43%|████▎     | 15757/37046 [01:09<02:41, 131.84it/s]

Reasoning:  43%|████▎     | 15773/37046 [01:09<02:32, 139.28it/s]

Reasoning:  43%|████▎     | 15789/37046 [01:09<02:26, 144.87it/s]

Reasoning:  43%|████▎     | 15809/37046 [01:09<02:12, 160.19it/s]

Reasoning:  43%|████▎     | 15826/37046 [01:09<02:23, 148.16it/s]

Reasoning:  43%|████▎     | 15842/37046 [01:09<02:39, 133.26it/s]

Reasoning:  43%|████▎     | 15856/37046 [01:10<02:42, 130.03it/s]

Reasoning:  43%|████▎     | 15870/37046 [01:10<02:44, 128.83it/s]

Reasoning:  43%|████▎     | 15885/37046 [01:10<02:39, 132.65it/s]

Reasoning:  43%|████▎     | 15900/37046 [01:10<02:37, 134.26it/s]

Reasoning:  43%|████▎     | 15914/37046 [01:10<02:56, 119.95it/s]

Reasoning:  43%|████▎     | 15927/37046 [01:10<03:07, 112.83it/s]

Reasoning:  43%|████▎     | 15939/37046 [01:10<03:22, 104.31it/s]

Reasoning:  43%|████▎     | 15951/37046 [01:10<03:17, 107.03it/s]

Reasoning:  43%|████▎     | 15975/37046 [01:10<02:29, 140.82it/s]

Reasoning:  43%|████▎     | 16003/37046 [01:11<01:59, 176.03it/s]

Reasoning:  43%|████▎     | 16033/37046 [01:11<01:40, 210.10it/s]

Reasoning:  43%|████▎     | 16063/37046 [01:11<01:29, 235.44it/s]

Reasoning:  43%|████▎     | 16093/37046 [01:11<01:22, 253.98it/s]

Reasoning:  44%|████▎     | 16121/37046 [01:11<01:20, 260.61it/s]

Reasoning:  44%|████▎     | 16155/37046 [01:11<01:14, 280.31it/s]

Reasoning:  44%|████▎     | 16191/37046 [01:11<01:08, 303.43it/s]

Reasoning:  44%|████▍     | 16225/37046 [01:11<01:07, 310.55it/s]

Reasoning:  44%|████▍     | 16262/37046 [01:11<01:03, 327.29it/s]

Reasoning:  44%|████▍     | 16303/37046 [01:11<00:59, 346.58it/s]

Reasoning:  44%|████▍     | 16344/37046 [01:12<00:57, 361.61it/s]

Reasoning:  44%|████▍     | 16381/37046 [01:12<01:13, 281.31it/s]

Reasoning:  44%|████▍     | 16412/37046 [01:12<01:22, 250.02it/s]

Reasoning:  44%|████▍     | 16440/37046 [01:12<01:28, 232.39it/s]

Reasoning:  44%|████▍     | 16465/37046 [01:12<01:39, 206.83it/s]

Reasoning:  45%|████▍     | 16488/37046 [01:12<01:47, 190.63it/s]

Reasoning:  45%|████▍     | 16510/37046 [01:13<01:44, 197.11it/s]

Reasoning:  45%|████▍     | 16533/37046 [01:13<01:42, 200.38it/s]

Reasoning:  45%|████▍     | 16556/37046 [01:13<01:39, 205.74it/s]

Reasoning:  45%|████▍     | 16578/37046 [01:13<01:38, 207.51it/s]

Reasoning:  45%|████▍     | 16600/37046 [01:13<01:42, 199.30it/s]

Reasoning:  45%|████▍     | 16622/37046 [01:13<01:41, 201.61it/s]

Reasoning:  45%|████▍     | 16643/37046 [01:13<01:42, 198.28it/s]

Reasoning:  45%|████▍     | 16663/37046 [01:13<01:47, 190.09it/s]

Reasoning:  45%|████▌     | 16683/37046 [01:13<01:46, 191.13it/s]

Reasoning:  45%|████▌     | 16703/37046 [01:14<01:49, 186.40it/s]

Reasoning:  45%|████▌     | 16722/37046 [01:14<01:53, 178.87it/s]

Reasoning:  45%|████▌     | 16740/37046 [01:14<02:40, 126.59it/s]

Reasoning:  45%|████▌     | 16755/37046 [01:14<03:55, 85.99it/s]

Reasoning:  45%|████▌     | 16767/37046 [01:14<04:29, 75.17it/s]

Reasoning:  45%|████▌     | 16777/37046 [01:15<04:53, 69.07it/s]

Reasoning:  45%|████▌     | 16786/37046 [01:15<05:18, 63.56it/s]

Reasoning:  45%|████▌     | 16794/37046 [01:15<05:25, 62.16it/s]

Reasoning:  45%|████▌     | 16801/37046 [01:15<05:31, 61.13it/s]

Reasoning:  45%|████▌     | 16808/37046 [01:15<05:36, 60.18it/s]

Reasoning:  45%|████▌     | 16815/37046 [01:15<05:59, 56.23it/s]

Reasoning:  45%|████▌     | 16822/37046 [01:15<05:50, 57.73it/s]

Reasoning:  45%|████▌     | 16829/37046 [01:16<05:55, 56.86it/s]

Reasoning:  45%|████▌     | 16836/37046 [01:16<05:45, 58.55it/s]

Reasoning:  45%|████▌     | 16842/37046 [01:16<05:59, 56.22it/s]

Reasoning:  45%|████▌     | 16848/37046 [01:16<06:01, 55.90it/s]

Reasoning:  46%|████▌     | 16856/37046 [01:16<05:43, 58.86it/s]

Reasoning:  46%|████▌     | 16862/37046 [01:16<05:51, 57.37it/s]

Reasoning:  46%|████▌     | 16868/37046 [01:16<06:02, 55.61it/s]

Reasoning:  46%|████▌     | 16874/37046 [01:16<05:55, 56.75it/s]

Reasoning:  46%|████▌     | 16880/37046 [01:17<06:21, 52.80it/s]

Reasoning:  46%|████▌     | 16887/37046 [01:17<06:02, 55.67it/s]

Reasoning:  46%|████▌     | 16893/37046 [01:17<05:58, 56.19it/s]

Reasoning:  46%|████▌     | 16899/37046 [01:17<06:25, 52.20it/s]

Reasoning:  46%|████▌     | 16905/37046 [01:17<07:10, 46.75it/s]

Reasoning:  46%|████▌     | 16911/37046 [01:17<06:52, 48.78it/s]

Reasoning:  46%|████▌     | 16918/37046 [01:17<06:17, 53.31it/s]

Reasoning:  46%|████▌     | 16924/37046 [01:17<06:22, 52.66it/s]

Reasoning:  46%|████▌     | 16930/37046 [01:17<06:24, 52.28it/s]

Reasoning:  46%|████▌     | 16936/37046 [01:18<06:14, 53.65it/s]

Reasoning:  46%|████▌     | 16942/37046 [01:18<06:48, 49.16it/s]

Reasoning:  46%|████▌     | 16948/37046 [01:18<07:14, 46.30it/s]

Reasoning:  46%|████▌     | 16954/37046 [01:18<06:55, 48.33it/s]

Reasoning:  46%|████▌     | 16959/37046 [01:18<06:58, 47.97it/s]

Reasoning:  46%|████▌     | 16965/37046 [01:18<06:33, 50.97it/s]

Reasoning:  46%|████▌     | 16971/37046 [01:18<06:31, 51.28it/s]

Reasoning:  46%|████▌     | 16977/37046 [01:18<06:32, 51.12it/s]

Reasoning:  46%|████▌     | 16983/37046 [01:19<06:52, 48.60it/s]

Reasoning:  46%|████▌     | 16988/37046 [01:19<07:04, 47.21it/s]

Reasoning:  46%|████▌     | 16995/37046 [01:19<06:19, 52.86it/s]

Reasoning:  46%|████▌     | 17001/37046 [01:19<06:22, 52.44it/s]

Reasoning:  46%|████▌     | 17007/37046 [01:19<06:19, 52.80it/s]

Reasoning:  46%|████▌     | 17015/37046 [01:19<05:41, 58.58it/s]

Reasoning:  46%|████▌     | 17021/37046 [01:19<05:44, 58.21it/s]

Reasoning:  46%|████▌     | 17028/37046 [01:19<05:36, 59.56it/s]

Reasoning:  46%|████▌     | 17035/37046 [01:19<05:31, 60.45it/s]

Reasoning:  46%|████▌     | 17044/37046 [01:20<04:55, 67.70it/s]

Reasoning:  46%|████▌     | 17053/37046 [01:20<04:38, 71.73it/s]

Reasoning:  46%|████▌     | 17061/37046 [01:20<04:54, 67.80it/s]

Reasoning:  46%|████▌     | 17068/37046 [01:20<05:22, 61.89it/s]

Reasoning:  46%|████▌     | 17075/37046 [01:20<05:17, 62.90it/s]

Reasoning:  46%|████▌     | 17083/37046 [01:20<05:13, 63.73it/s]

Reasoning:  46%|████▌     | 17090/37046 [01:20<05:23, 61.67it/s]

Reasoning:  46%|████▌     | 17097/37046 [01:20<05:48, 57.27it/s]

Reasoning:  46%|████▌     | 17104/37046 [01:21<05:39, 58.77it/s]

Reasoning:  46%|████▌     | 17111/37046 [01:21<05:37, 59.12it/s]

Reasoning:  46%|████▌     | 17117/37046 [01:21<06:19, 52.46it/s]

Reasoning:  46%|████▌     | 17123/37046 [01:21<06:16, 52.96it/s]

Reasoning:  46%|████▋     | 17167/37046 [01:21<02:12, 150.59it/s]

Reasoning:  46%|████▋     | 17208/37046 [01:21<01:30, 218.53it/s]

Reasoning:  47%|████▋     | 17249/37046 [01:21<01:13, 270.31it/s]

Reasoning:  47%|████▋     | 17289/37046 [01:21<01:04, 306.53it/s]

Reasoning:  47%|████▋     | 17334/37046 [01:21<00:57, 344.08it/s]

Reasoning:  47%|████▋     | 17374/37046 [01:22<00:54, 360.07it/s]

Reasoning:  47%|████▋     | 17416/37046 [01:22<00:52, 377.45it/s]

Reasoning:  47%|████▋     | 17459/37046 [01:22<00:49, 391.92it/s]

Reasoning:  47%|████▋     | 17499/37046 [01:23<02:31, 128.66it/s]

Reasoning:  47%|████▋     | 17547/37046 [01:23<01:53, 171.08it/s]

Reasoning:  47%|████▋     | 17594/37046 [01:23<01:30, 215.04it/s]

Reasoning:  48%|████▊     | 17648/37046 [01:23<01:12, 269.19it/s]

Reasoning:  48%|████▊     | 17702/37046 [01:23<01:00, 322.22it/s]

Reasoning:  48%|████▊     | 17762/37046 [01:23<00:50, 381.38it/s]

Reasoning:  48%|████▊     | 17812/37046 [01:23<00:47, 401.31it/s]

Reasoning:  48%|████▊     | 17861/37046 [01:23<00:48, 395.67it/s]

Reasoning:  48%|████▊     | 17918/37046 [01:23<00:43, 439.17it/s]

Reasoning:  48%|████▊     | 17967/37046 [01:24<00:52, 362.91it/s]

Reasoning:  49%|████▊     | 18016/37046 [01:24<00:49, 387.80it/s]

Reasoning:  49%|████▉     | 18060/37046 [01:24<00:56, 335.16it/s]

Reasoning:  49%|████▉     | 18098/37046 [01:24<00:56, 337.22it/s]

Reasoning:  49%|████▉     | 18148/37046 [01:24<00:50, 376.39it/s]

Reasoning:  49%|████▉     | 18196/37046 [01:24<00:46, 402.83it/s]

Reasoning:  49%|████▉     | 18240/37046 [01:24<00:55, 337.23it/s]

Reasoning:  49%|████▉     | 18298/37046 [01:24<00:47, 390.70it/s]

Reasoning:  50%|████▉     | 18357/37046 [01:25<00:43, 433.71it/s]

Reasoning:  50%|████▉     | 18404/37046 [01:25<00:42, 437.36it/s]

Reasoning:  50%|████▉     | 18450/37046 [01:25<00:43, 429.40it/s]

Reasoning:  50%|████▉     | 18501/37046 [01:25<00:41, 445.48it/s]

Reasoning:  50%|█████     | 18550/37046 [01:25<00:40, 451.61it/s]

Reasoning:  50%|█████     | 18599/37046 [01:25<00:39, 462.33it/s]

Reasoning:  50%|█████     | 18646/37046 [01:25<00:40, 457.57it/s]

Reasoning:  50%|█████     | 18693/37046 [01:25<00:41, 439.97it/s]

Reasoning:  51%|█████     | 18738/37046 [01:26<00:51, 357.56it/s]

Reasoning:  51%|█████     | 18777/37046 [01:26<01:02, 290.78it/s]

Reasoning:  51%|█████     | 18810/37046 [01:26<01:07, 271.56it/s]

Reasoning:  51%|█████     | 18840/37046 [01:26<01:08, 266.00it/s]

Reasoning:  51%|█████     | 18869/37046 [01:26<01:08, 264.55it/s]

Reasoning:  51%|█████     | 18897/37046 [01:26<01:10, 256.75it/s]

Reasoning:  51%|█████     | 18924/37046 [01:26<01:12, 251.45it/s]

Reasoning:  51%|█████     | 18956/37046 [01:26<01:07, 268.07it/s]

Reasoning:  51%|█████▏    | 18991/37046 [01:27<01:02, 289.71it/s]

Reasoning:  51%|█████▏    | 19021/37046 [01:27<01:02, 287.71it/s]

Reasoning:  51%|█████▏    | 19051/37046 [01:27<01:03, 284.66it/s]

Reasoning:  52%|█████▏    | 19080/37046 [01:27<01:04, 276.61it/s]

Reasoning:  52%|█████▏    | 19108/37046 [01:27<01:12, 246.44it/s]

Reasoning:  52%|█████▏    | 19134/37046 [01:27<01:14, 239.35it/s]

Reasoning:  52%|█████▏    | 19159/37046 [01:27<01:23, 213.58it/s]

Reasoning:  52%|█████▏    | 19182/37046 [01:27<01:30, 196.58it/s]

Reasoning:  52%|█████▏    | 19203/37046 [01:28<01:42, 173.95it/s]

Reasoning:  52%|█████▏    | 19222/37046 [01:28<01:48, 164.77it/s]

Reasoning:  52%|█████▏    | 19242/37046 [01:28<01:42, 173.00it/s]

Reasoning:  52%|█████▏    | 19266/37046 [01:28<01:34, 187.48it/s]

Reasoning:  52%|█████▏    | 19286/37046 [01:28<01:33, 190.21it/s]

Reasoning:  52%|█████▏    | 19309/37046 [01:28<01:28, 200.97it/s]

Reasoning:  52%|█████▏    | 19330/37046 [01:28<01:35, 185.58it/s]

Reasoning:  52%|█████▏    | 19350/37046 [01:28<01:42, 172.18it/s]

Reasoning:  52%|█████▏    | 19368/37046 [01:28<01:45, 167.08it/s]

Reasoning:  52%|█████▏    | 19386/37046 [01:29<01:45, 168.07it/s]

Reasoning:  52%|█████▏    | 19404/37046 [01:29<01:53, 155.86it/s]

Reasoning:  52%|█████▏    | 19420/37046 [01:29<01:52, 156.33it/s]

Reasoning:  52%|█████▏    | 19436/37046 [01:29<01:53, 154.56it/s]

Reasoning:  53%|█████▎    | 19452/37046 [01:29<01:55, 151.88it/s]

Reasoning:  53%|█████▎    | 19474/37046 [01:29<01:43, 169.81it/s]

Reasoning:  53%|█████▎    | 19509/37046 [01:29<01:19, 220.29it/s]

Reasoning:  53%|█████▎    | 19542/37046 [01:29<01:10, 248.71it/s]

Reasoning:  53%|█████▎    | 19574/37046 [01:29<01:05, 267.23it/s]

Reasoning:  53%|█████▎    | 19610/37046 [01:30<00:59, 292.11it/s]

Reasoning:  53%|█████▎    | 19646/37046 [01:30<00:55, 311.55it/s]

Reasoning:  53%|█████▎    | 19684/37046 [01:30<00:53, 325.55it/s]

Reasoning:  53%|█████▎    | 19719/37046 [01:30<00:52, 332.66it/s]

Reasoning:  53%|█████▎    | 19766/37046 [01:30<00:46, 372.98it/s]

Reasoning:  53%|█████▎    | 19810/37046 [01:30<00:43, 392.61it/s]

Reasoning:  54%|█████▎    | 19855/37046 [01:30<00:42, 403.20it/s]

Reasoning:  54%|█████▎    | 19896/37046 [01:30<00:48, 353.21it/s]

Reasoning:  54%|█████▍    | 19933/37046 [01:30<00:50, 341.55it/s]

Reasoning:  54%|█████▍    | 19968/37046 [01:31<00:51, 330.03it/s]

Reasoning:  54%|█████▍    | 20002/37046 [01:31<00:51, 328.02it/s]

Reasoning:  54%|█████▍    | 20036/37046 [01:31<00:53, 316.95it/s]

Reasoning:  54%|█████▍    | 20072/37046 [01:31<00:51, 326.60it/s]

Reasoning:  54%|█████▍    | 20105/37046 [01:31<00:52, 324.62it/s]

Reasoning:  54%|█████▍    | 20138/37046 [01:31<00:53, 315.86it/s]

Reasoning:  54%|█████▍    | 20170/37046 [01:31<00:55, 306.30it/s]

Reasoning:  55%|█████▍    | 20201/37046 [01:31<00:55, 304.84it/s]

Reasoning:  55%|█████▍    | 20232/37046 [01:31<00:54, 306.30it/s]

Reasoning:  55%|█████▍    | 20263/37046 [01:32<01:19, 211.14it/s]

Reasoning:  55%|█████▍    | 20289/37046 [01:32<01:34, 178.20it/s]

Reasoning:  55%|█████▍    | 20311/37046 [01:32<01:56, 143.37it/s]

Reasoning:  55%|█████▍    | 20329/37046 [01:32<02:33, 109.07it/s]

Reasoning:  55%|█████▍    | 20344/37046 [01:33<02:43, 102.06it/s]

Reasoning:  55%|█████▍    | 20357/37046 [01:33<02:50, 97.81it/s]

Reasoning:  55%|█████▍    | 20369/37046 [01:33<02:57, 94.15it/s]

Reasoning:  55%|█████▌    | 20380/37046 [01:33<03:29, 79.45it/s]

Reasoning:  55%|█████▌    | 20389/37046 [01:33<03:37, 76.70it/s]

Reasoning:  55%|█████▌    | 20399/37046 [01:33<03:24, 81.29it/s]

Reasoning:  55%|█████▌    | 20408/37046 [01:34<03:53, 71.20it/s]

Reasoning:  55%|█████▌    | 20422/37046 [01:34<03:13, 85.70it/s]

Reasoning:  55%|█████▌    | 20435/37046 [01:34<02:54, 95.38it/s]

Reasoning:  55%|█████▌    | 20446/37046 [01:34<02:51, 96.53it/s]

Reasoning:  55%|█████▌    | 20457/37046 [01:34<02:54, 95.09it/s]

Reasoning:  55%|█████▌    | 20474/37046 [01:34<02:26, 112.81it/s]

Reasoning:  55%|█████▌    | 20486/37046 [01:34<02:40, 103.30it/s]

Reasoning:  55%|█████▌    | 20497/37046 [01:34<02:43, 101.09it/s]

Reasoning:  55%|█████▌    | 20508/37046 [01:34<02:45, 99.86it/s]

Reasoning:  55%|█████▌    | 20522/37046 [01:35<02:30, 109.53it/s]

Reasoning:  55%|█████▌    | 20534/37046 [01:35<02:44, 100.24it/s]

Reasoning:  55%|█████▌    | 20546/37046 [01:35<02:40, 102.66it/s]

Reasoning:  55%|█████▌    | 20557/37046 [01:35<02:37, 104.46it/s]

Reasoning:  56%|█████▌    | 20569/37046 [01:35<02:36, 105.34it/s]

Reasoning:  56%|█████▌    | 20580/37046 [01:35<02:34, 106.61it/s]

Reasoning:  56%|█████▌    | 20595/37046 [01:35<02:18, 118.55it/s]

Reasoning:  56%|█████▌    | 20607/37046 [01:35<02:44, 100.16it/s]

Reasoning:  56%|█████▌    | 20618/37046 [01:36<02:51, 95.91it/s]

Reasoning:  56%|█████▌    | 20639/37046 [01:36<02:11, 124.60it/s]

Reasoning:  56%|█████▌    | 20672/37046 [01:36<01:31, 178.31it/s]

Reasoning:  56%|█████▌    | 20707/37046 [01:36<01:13, 223.73it/s]

Reasoning:  56%|█████▌    | 20743/37046 [01:36<01:03, 258.32it/s]

Reasoning:  56%|█████▌    | 20774/37046 [01:36<00:59, 272.64it/s]

Reasoning:  56%|█████▌    | 20809/37046 [01:36<00:56, 289.35it/s]

Reasoning:  56%|█████▋    | 20839/37046 [01:36<00:56, 289.33it/s]

Reasoning:  56%|█████▋    | 20874/37046 [01:36<00:52, 305.74it/s]

Reasoning:  56%|█████▋    | 20905/37046 [01:36<00:52, 306.90it/s]

Reasoning:  57%|█████▋    | 20939/37046 [01:37<00:51, 311.83it/s]

Reasoning:  57%|█████▋    | 20975/37046 [01:37<00:50, 319.72it/s]

Reasoning:  57%|█████▋    | 21008/37046 [01:37<00:50, 317.88it/s]

Reasoning:  57%|█████▋    | 21040/37046 [01:37<01:03, 253.36it/s]

Reasoning:  57%|█████▋    | 21068/37046 [01:37<01:10, 228.20it/s]

Reasoning:  57%|█████▋    | 21093/37046 [01:37<01:15, 212.49it/s]

Reasoning:  57%|█████▋    | 21116/37046 [01:37<01:21, 194.87it/s]

Reasoning:  57%|█████▋    | 21138/37046 [01:38<01:19, 199.88it/s]

Reasoning:  57%|█████▋    | 21159/37046 [01:38<01:21, 194.24it/s]

Reasoning:  57%|█████▋    | 21179/37046 [01:38<01:26, 183.36it/s]

Reasoning:  57%|█████▋    | 21198/37046 [01:38<01:26, 182.67it/s]

Reasoning:  57%|█████▋    | 21218/37046 [01:38<01:25, 184.61it/s]

Reasoning:  57%|█████▋    | 21241/37046 [01:38<01:21, 193.77it/s]

Reasoning:  57%|█████▋    | 21264/37046 [01:38<01:17, 203.71it/s]

Reasoning:  57%|█████▋    | 21285/37046 [01:38<01:23, 188.03it/s]

Reasoning:  58%|█████▊    | 21309/37046 [01:38<01:18, 201.75it/s]

Reasoning:  58%|█████▊    | 21334/37046 [01:38<01:13, 215.12it/s]

Reasoning:  58%|█████▊    | 21357/37046 [01:39<01:12, 215.98it/s]

Reasoning:  58%|█████▊    | 21380/37046 [01:39<01:11, 219.93it/s]

Reasoning:  58%|█████▊    | 21403/37046 [01:39<01:22, 189.02it/s]

Reasoning:  58%|█████▊    | 21423/37046 [01:39<02:02, 127.74it/s]

Reasoning:  58%|█████▊    | 21439/37046 [01:39<02:36, 99.86it/s]

Reasoning:  58%|█████▊    | 21452/37046 [01:40<03:08, 82.71it/s]

Reasoning:  58%|█████▊    | 21463/37046 [01:40<03:46, 68.93it/s]

Reasoning:  58%|█████▊    | 21472/37046 [01:40<04:14, 61.12it/s]

Reasoning:  58%|█████▊    | 21480/37046 [01:40<04:41, 55.30it/s]

Reasoning:  58%|█████▊    | 21487/37046 [01:41<05:06, 50.77it/s]

Reasoning:  58%|█████▊    | 21493/37046 [01:41<05:35, 46.30it/s]

Reasoning:  58%|█████▊    | 21498/37046 [01:41<06:10, 41.99it/s]

Reasoning:  58%|█████▊    | 21503/37046 [01:41<06:11, 41.82it/s]

Reasoning:  58%|█████▊    | 21508/37046 [01:41<06:15, 41.33it/s]

Reasoning:  58%|█████▊    | 21515/37046 [01:41<05:52, 44.00it/s]

Reasoning:  58%|█████▊    | 21520/37046 [01:41<05:47, 44.69it/s]

Reasoning:  58%|█████▊    | 21526/37046 [01:42<05:34, 46.40it/s]

Reasoning:  58%|█████▊    | 21532/37046 [01:42<05:14, 49.27it/s]

Reasoning:  58%|█████▊    | 21538/37046 [01:42<05:02, 51.29it/s]

Reasoning:  58%|█████▊    | 21544/37046 [01:42<05:32, 46.60it/s]

Reasoning:  58%|█████▊    | 21550/37046 [01:42<05:11, 49.82it/s]

Reasoning:  58%|█████▊    | 21557/37046 [01:42<04:52, 52.96it/s]

Reasoning:  58%|█████▊    | 21564/37046 [01:42<04:30, 57.33it/s]

Reasoning:  58%|█████▊    | 21570/37046 [01:42<05:22, 48.04it/s]

Reasoning:  58%|█████▊    | 21576/37046 [01:43<05:36, 45.94it/s]

Reasoning:  58%|█████▊    | 21584/37046 [01:43<04:53, 52.72it/s]

Reasoning:  58%|█████▊    | 21591/37046 [01:43<04:34, 56.21it/s]

Reasoning:  58%|█████▊    | 21597/37046 [01:43<04:30, 57.16it/s]

Reasoning:  58%|█████▊    | 21603/37046 [01:43<04:26, 57.87it/s]

Reasoning:  58%|█████▊    | 21609/37046 [01:43<04:44, 54.25it/s]

Reasoning:  58%|█████▊    | 21615/37046 [01:43<05:09, 49.88it/s]

Reasoning:  58%|█████▊    | 21621/37046 [01:43<05:36, 45.87it/s]

Reasoning:  58%|█████▊    | 21626/37046 [01:43<05:42, 45.01it/s]

Reasoning:  58%|█████▊    | 21631/37046 [01:44<05:37, 45.71it/s]

Reasoning:  58%|█████▊    | 21637/37046 [01:44<05:34, 46.04it/s]

Reasoning:  58%|█████▊    | 21642/37046 [01:44<05:55, 43.33it/s]

Reasoning:  58%|█████▊    | 21647/37046 [01:44<05:42, 45.01it/s]

Reasoning:  58%|█████▊    | 21652/37046 [01:44<05:51, 43.78it/s]

Reasoning:  58%|█████▊    | 21659/37046 [01:44<05:26, 47.09it/s]

Reasoning:  58%|█████▊    | 21664/37046 [01:44<05:35, 45.91it/s]

Reasoning:  58%|█████▊    | 21669/37046 [01:44<05:47, 44.30it/s]

Reasoning:  59%|█████▊    | 21675/37046 [01:45<05:26, 47.14it/s]

Reasoning:  59%|█████▊    | 21680/37046 [01:45<05:24, 47.29it/s]

Reasoning:  59%|█████▊    | 21685/37046 [01:45<05:21, 47.84it/s]

Reasoning:  59%|█████▊    | 21692/37046 [01:45<04:44, 54.03it/s]

Reasoning:  59%|█████▊    | 21698/37046 [01:45<04:43, 54.15it/s]

Reasoning:  59%|█████▊    | 21705/37046 [01:45<04:29, 56.97it/s]

Reasoning:  59%|█████▊    | 21713/37046 [01:45<04:13, 60.54it/s]

Reasoning:  59%|█████▊    | 21720/37046 [01:45<04:21, 58.62it/s]

Reasoning:  59%|█████▊    | 21727/37046 [01:45<04:11, 60.84it/s]

Reasoning:  59%|█████▊    | 21734/37046 [01:46<04:12, 60.59it/s]

Reasoning:  59%|█████▊    | 21741/37046 [01:46<04:17, 59.43it/s]

Reasoning:  59%|█████▊    | 21747/37046 [01:46<04:17, 59.51it/s]

Reasoning:  59%|█████▊    | 21754/37046 [01:46<04:17, 59.36it/s]

Reasoning:  59%|█████▊    | 21760/37046 [01:46<04:26, 57.44it/s]

Reasoning:  59%|█████▉    | 21766/37046 [01:46<04:51, 52.44it/s]

Reasoning:  59%|█████▉    | 21772/37046 [01:46<04:42, 54.16it/s]

Reasoning:  59%|█████▉    | 21778/37046 [01:46<05:01, 50.72it/s]

Reasoning:  59%|█████▉    | 21784/37046 [01:46<05:12, 48.88it/s]

Reasoning:  59%|█████▉    | 21790/37046 [01:47<05:16, 48.23it/s]

Reasoning:  59%|█████▉    | 21838/37046 [01:47<01:36, 157.62it/s]

Reasoning:  59%|█████▉    | 21880/37046 [01:47<01:06, 227.33it/s]

Reasoning:  59%|█████▉    | 21919/37046 [01:47<00:56, 268.06it/s]

Reasoning:  59%|█████▉    | 21958/37046 [01:47<00:49, 302.09it/s]

Reasoning:  59%|█████▉    | 21999/37046 [01:47<00:46, 327.05it/s]

Reasoning:  59%|█████▉    | 22035/37046 [01:47<00:44, 336.39it/s]

Reasoning:  60%|█████▉    | 22074/37046 [01:47<00:42, 351.42it/s]

Reasoning:  60%|█████▉    | 22120/37046 [01:47<00:39, 378.71it/s]

Reasoning:  60%|█████▉    | 22166/37046 [01:48<00:37, 401.72it/s]

Reasoning:  60%|█████▉    | 22212/37046 [01:48<00:35, 418.42it/s]

Reasoning:  60%|██████    | 22255/37046 [01:48<00:37, 389.32it/s]

Reasoning:  60%|██████    | 22298/37046 [01:48<00:37, 398.40it/s]

Reasoning:  60%|██████    | 22340/37046 [01:48<00:36, 401.25it/s]

Reasoning:  60%|██████    | 22381/37046 [01:48<00:36, 397.72it/s]

Reasoning:  61%|██████    | 22422/37046 [01:48<00:37, 394.29it/s]

Reasoning:  61%|██████    | 22462/37046 [01:48<00:37, 390.41it/s]

Reasoning:  61%|██████    | 22503/37046 [01:48<00:36, 394.93it/s]

Reasoning:  61%|██████    | 22544/37046 [01:48<00:36, 394.27it/s]

Reasoning:  61%|██████    | 22586/37046 [01:49<00:40, 359.85it/s]

Reasoning:  61%|██████    | 22641/37046 [01:49<00:35, 410.96it/s]

Reasoning:  61%|██████▏   | 22693/37046 [01:49<00:32, 440.10it/s]

Reasoning:  61%|██████▏   | 22738/37046 [01:49<00:36, 389.13it/s]

Reasoning:  62%|██████▏   | 22794/37046 [01:49<00:33, 422.96it/s]

Reasoning:  62%|██████▏   | 22858/37046 [01:49<00:29, 474.55it/s]

Reasoning:  62%|██████▏   | 22907/37046 [01:49<00:29, 477.08it/s]

Reasoning:  62%|██████▏   | 22956/37046 [01:49<00:29, 480.51it/s]

Reasoning:  62%|██████▏   | 23013/37046 [01:50<00:27, 505.59it/s]

Reasoning:  62%|██████▏   | 23065/37046 [01:50<00:28, 486.72it/s]

Reasoning:  62%|██████▏   | 23120/37046 [01:50<00:27, 504.65it/s]

Reasoning:  63%|██████▎   | 23185/37046 [01:50<00:25, 546.35it/s]

Reasoning:  63%|██████▎   | 23249/37046 [01:50<00:24, 565.44it/s]

Reasoning:  63%|██████▎   | 23306/37046 [01:50<00:24, 558.17it/s]

Reasoning:  63%|██████▎   | 23363/37046 [01:50<00:28, 476.17it/s]

Reasoning:  63%|██████▎   | 23413/37046 [01:50<00:33, 403.42it/s]

Reasoning:  63%|██████▎   | 23457/37046 [01:51<00:39, 343.21it/s]

Reasoning:  63%|██████▎   | 23495/37046 [01:51<00:43, 311.65it/s]

Reasoning:  64%|██████▎   | 23529/37046 [01:51<00:47, 284.33it/s]

Reasoning:  64%|██████▎   | 23560/37046 [01:51<00:49, 274.67it/s]

Reasoning:  64%|██████▎   | 23589/37046 [01:51<00:50, 268.67it/s]

Reasoning:  64%|██████▍   | 23617/37046 [01:51<00:50, 266.59it/s]

Reasoning:  64%|██████▍   | 23647/37046 [01:51<00:49, 273.20it/s]

Reasoning:  64%|██████▍   | 23675/37046 [01:51<00:50, 265.04it/s]

Reasoning:  64%|██████▍   | 23702/37046 [01:52<00:50, 262.85it/s]

Reasoning:  64%|██████▍   | 23729/37046 [01:52<00:52, 254.30it/s]

Reasoning:  64%|██████▍   | 23755/37046 [01:52<00:59, 222.95it/s]

Reasoning:  64%|██████▍   | 23778/37046 [01:52<01:07, 197.29it/s]

Reasoning:  64%|██████▍   | 23799/37046 [01:52<01:12, 183.73it/s]

Reasoning:  64%|██████▍   | 23818/37046 [01:52<01:11, 184.71it/s]

Reasoning:  64%|██████▍   | 23837/37046 [01:52<01:22, 159.97it/s]

Reasoning:  64%|██████▍   | 23856/37046 [01:52<01:19, 164.96it/s]

Reasoning:  64%|██████▍   | 23874/37046 [01:53<01:20, 164.40it/s]

Reasoning:  64%|██████▍   | 23891/37046 [01:53<01:21, 161.68it/s]

Reasoning:  65%|██████▍   | 23909/37046 [01:53<01:19, 165.87it/s]

Reasoning:  65%|██████▍   | 23934/37046 [01:53<01:10, 187.04it/s]

Reasoning:  65%|██████▍   | 23955/37046 [01:53<01:07, 192.90it/s]

Reasoning:  65%|██████▍   | 23975/37046 [01:53<01:08, 191.36it/s]

Reasoning:  65%|██████▍   | 23995/37046 [01:53<01:16, 170.47it/s]

Reasoning:  65%|██████▍   | 24013/37046 [01:53<01:27, 148.37it/s]

Reasoning:  65%|██████▍   | 24029/37046 [01:54<01:35, 136.81it/s]

Reasoning:  65%|██████▍   | 24045/37046 [01:54<01:32, 140.55it/s]

Reasoning:  65%|██████▍   | 24063/37046 [01:54<01:27, 148.83it/s]

Reasoning:  65%|██████▌   | 24080/37046 [01:54<01:24, 153.79it/s]

Reasoning:  65%|██████▌   | 24100/37046 [01:54<01:18, 165.04it/s]

Reasoning:  65%|██████▌   | 24119/37046 [01:54<01:15, 170.31it/s]

Reasoning:  65%|██████▌   | 24145/37046 [01:54<01:06, 195.06it/s]

Reasoning:  65%|██████▌   | 24180/37046 [01:54<00:53, 239.47it/s]

Reasoning:  65%|██████▌   | 24212/37046 [01:54<00:48, 262.00it/s]

Reasoning:  65%|██████▌   | 24244/37046 [01:54<00:46, 278.07it/s]

Reasoning:  66%|██████▌   | 24275/37046 [01:55<00:44, 286.19it/s]

Reasoning:  66%|██████▌   | 24310/37046 [01:55<00:41, 304.56it/s]

Reasoning:  66%|██████▌   | 24345/37046 [01:55<00:39, 317.54it/s]

Reasoning:  66%|██████▌   | 24378/37046 [01:55<00:39, 319.33it/s]

Reasoning:  66%|██████▌   | 24412/37046 [01:55<00:38, 324.96it/s]

Reasoning:  66%|██████▌   | 24446/37046 [01:55<00:38, 327.96it/s]

Reasoning:  66%|██████▌   | 24479/37046 [01:55<00:38, 326.13it/s]

Reasoning:  66%|██████▌   | 24517/37046 [01:55<00:36, 340.58it/s]

Reasoning:  66%|██████▋   | 24552/37046 [01:55<00:40, 310.87it/s]

Reasoning:  66%|██████▋   | 24584/37046 [01:56<00:40, 308.01it/s]

Reasoning:  66%|██████▋   | 24616/37046 [01:56<00:42, 295.59it/s]

Reasoning:  67%|██████▋   | 24646/37046 [01:56<00:45, 275.18it/s]

Reasoning:  67%|██████▋   | 24674/37046 [01:56<00:45, 273.09it/s]

Reasoning:  67%|██████▋   | 24702/37046 [01:56<00:45, 269.77it/s]

Reasoning:  67%|██████▋   | 24738/37046 [01:56<00:41, 293.55it/s]

Reasoning:  67%|██████▋   | 24769/37046 [01:56<00:41, 297.72it/s]

Reasoning:  67%|██████▋   | 24799/37046 [01:56<00:41, 294.03it/s]

Reasoning:  67%|██████▋   | 24835/37046 [01:56<00:39, 312.23it/s]

Reasoning:  67%|██████▋   | 24867/37046 [01:57<00:39, 307.77it/s]

Reasoning:  67%|██████▋   | 24899/37046 [01:57<00:39, 311.21it/s]

Reasoning:  67%|██████▋   | 24931/37046 [01:57<00:58, 206.01it/s]

Reasoning:  67%|██████▋   | 24957/37046 [01:57<01:05, 183.86it/s]

Reasoning:  67%|██████▋   | 24979/37046 [01:57<01:09, 173.92it/s]

Reasoning:  67%|██████▋   | 24999/37046 [01:57<01:28, 135.83it/s]

Reasoning:  68%|██████▊   | 25016/37046 [01:58<01:37, 122.84it/s]

Reasoning:  68%|██████▊   | 25031/37046 [01:58<01:42, 116.74it/s]

Reasoning:  68%|██████▊   | 25044/37046 [01:58<01:49, 109.65it/s]

Reasoning:  68%|██████▊   | 25056/37046 [01:58<01:59, 100.59it/s]

Reasoning:  68%|██████▊   | 25068/37046 [01:58<01:54, 104.22it/s]

Reasoning:  68%|██████▊   | 25079/37046 [01:58<02:15, 88.54it/s]

Reasoning:  68%|██████▊   | 25091/37046 [01:58<02:06, 94.24it/s]

Reasoning:  68%|██████▊   | 25102/37046 [01:59<02:07, 93.55it/s]

Reasoning:  68%|██████▊   | 25112/37046 [01:59<02:07, 93.53it/s]

Reasoning:  68%|██████▊   | 25122/37046 [01:59<02:07, 93.24it/s]

Reasoning:  68%|██████▊   | 25132/37046 [01:59<02:21, 84.17it/s]

Reasoning:  68%|██████▊   | 25147/37046 [01:59<02:02, 96.98it/s]

Reasoning:  68%|██████▊   | 25157/37046 [01:59<02:12, 89.71it/s]

Reasoning:  68%|██████▊   | 25167/37046 [01:59<02:15, 87.78it/s]

Reasoning:  68%|██████▊   | 25176/37046 [01:59<02:22, 83.06it/s]

Reasoning:  68%|██████▊   | 25186/37046 [02:00<02:16, 87.10it/s]

Reasoning:  68%|██████▊   | 25195/37046 [02:00<02:20, 84.22it/s]

Reasoning:  68%|██████▊   | 25204/37046 [02:00<02:18, 85.59it/s]

Reasoning:  68%|██████▊   | 25218/37046 [02:00<01:58, 100.19it/s]

Reasoning:  68%|██████▊   | 25233/37046 [02:00<01:45, 112.07it/s]

Reasoning:  68%|██████▊   | 25245/37046 [02:00<01:58, 99.58it/s]

Reasoning:  68%|██████▊   | 25256/37046 [02:00<02:05, 93.97it/s]

Reasoning:  68%|██████▊   | 25269/37046 [02:00<01:57, 100.56it/s]

Reasoning:  68%|██████▊   | 25280/37046 [02:01<02:01, 97.13it/s]

Reasoning:  68%|██████▊   | 25293/37046 [02:01<01:52, 104.60it/s]

Reasoning:  68%|██████▊   | 25324/37046 [02:01<01:13, 159.11it/s]

Reasoning:  68%|██████▊   | 25367/37046 [02:01<00:50, 230.35it/s]

Reasoning:  69%|██████▊   | 25411/37046 [02:01<00:40, 287.79it/s]

Reasoning:  69%|██████▊   | 25452/37046 [02:01<00:36, 321.80it/s]

Reasoning:  69%|██████▉   | 25488/37046 [02:01<00:34, 330.97it/s]

Reasoning:  69%|██████▉   | 25526/37046 [02:01<00:33, 343.82it/s]

Reasoning:  69%|██████▉   | 25563/37046 [02:01<00:32, 351.35it/s]

Reasoning:  69%|██████▉   | 25609/37046 [02:01<00:30, 380.89it/s]

Reasoning:  69%|██████▉   | 25649/37046 [02:02<00:29, 385.24it/s]

Reasoning:  69%|██████▉   | 25688/37046 [02:02<00:29, 378.94it/s]

Reasoning:  69%|██████▉   | 25727/37046 [02:02<00:40, 276.69it/s]

Reasoning:  70%|██████▉   | 25759/37046 [02:02<00:52, 216.43it/s]

Reasoning:  70%|██████▉   | 25786/37046 [02:02<01:01, 183.40it/s]

Reasoning:  70%|██████▉   | 25809/37046 [02:03<01:09, 162.50it/s]

Reasoning:  70%|██████▉   | 25828/37046 [02:03<01:09, 160.29it/s]

Reasoning:  70%|██████▉   | 25848/37046 [02:03<01:07, 166.46it/s]

Reasoning:  70%|██████▉   | 25867/37046 [02:03<01:07, 165.05it/s]

Reasoning:  70%|██████▉   | 25885/37046 [02:03<01:06, 166.88it/s]

Reasoning:  70%|██████▉   | 25904/37046 [02:03<01:04, 172.14it/s]

Reasoning:  70%|██████▉   | 25922/37046 [02:03<01:04, 172.39it/s]

Reasoning:  70%|███████   | 25940/37046 [02:03<01:06, 165.84it/s]

Reasoning:  70%|███████   | 25957/37046 [02:03<01:15, 146.91it/s]

Reasoning:  70%|███████   | 25973/37046 [02:04<01:14, 148.83it/s]

Reasoning:  70%|███████   | 25992/37046 [02:04<01:10, 157.49it/s]

Reasoning:  70%|███████   | 26009/37046 [02:04<01:09, 159.90it/s]

Reasoning:  70%|███████   | 26029/37046 [02:04<01:04, 169.96it/s]

Reasoning:  70%|███████   | 26048/37046 [02:04<01:02, 175.46it/s]

Reasoning:  70%|███████   | 26068/37046 [02:04<01:00, 180.40it/s]

Reasoning:  70%|███████   | 26087/37046 [02:04<01:32, 118.66it/s]

Reasoning:  70%|███████   | 26102/37046 [02:05<01:59, 91.45it/s]

Reasoning:  70%|███████   | 26114/37046 [02:05<02:14, 81.31it/s]

Reasoning:  71%|███████   | 26125/37046 [02:05<02:27, 74.17it/s]

Reasoning:  71%|███████   | 26134/37046 [02:05<02:41, 67.48it/s]

Reasoning:  71%|███████   | 26142/37046 [02:05<02:54, 62.47it/s]

Reasoning:  71%|███████   | 26149/37046 [02:06<03:05, 58.75it/s]

Reasoning:  71%|███████   | 26156/37046 [02:06<03:28, 52.25it/s]

Reasoning:  71%|███████   | 26162/37046 [02:06<03:38, 49.86it/s]

Reasoning:  71%|███████   | 26168/37046 [02:06<04:00, 45.32it/s]

Reasoning:  71%|███████   | 26173/37046 [02:06<04:13, 42.84it/s]

Reasoning:  71%|███████   | 26178/37046 [02:06<04:30, 40.22it/s]

Reasoning:  71%|███████   | 26183/37046 [02:06<04:30, 40.22it/s]

Reasoning:  71%|███████   | 26188/37046 [02:07<04:43, 38.36it/s]

Reasoning:  71%|███████   | 26193/37046 [02:07<04:25, 40.89it/s]

Reasoning:  71%|███████   | 26198/37046 [02:07<04:31, 39.92it/s]

Reasoning:  71%|███████   | 26203/37046 [02:07<04:29, 40.24it/s]

Reasoning:  71%|███████   | 26208/37046 [02:07<04:37, 39.05it/s]

Reasoning:  71%|███████   | 26212/37046 [02:07<04:50, 37.26it/s]

Reasoning:  71%|███████   | 26216/37046 [02:07<04:56, 36.53it/s]

Reasoning:  71%|███████   | 26223/37046 [02:07<04:11, 43.07it/s]

Reasoning:  71%|███████   | 26230/37046 [02:08<03:52, 46.59it/s]

Reasoning:  71%|███████   | 26237/37046 [02:08<03:30, 51.39it/s]

Reasoning:  71%|███████   | 26243/37046 [02:08<03:38, 49.48it/s]

Reasoning:  71%|███████   | 26250/37046 [02:08<03:18, 54.44it/s]

Reasoning:  71%|███████   | 26258/37046 [02:08<02:59, 60.21it/s]

Reasoning:  71%|███████   | 26265/37046 [02:08<03:09, 56.80it/s]

Reasoning:  71%|███████   | 26271/37046 [02:08<03:11, 56.14it/s]

Reasoning:  71%|███████   | 26277/37046 [02:08<03:18, 54.16it/s]

Reasoning:  71%|███████   | 26283/37046 [02:09<03:46, 47.45it/s]

Reasoning:  71%|███████   | 26289/37046 [02:09<03:44, 47.99it/s]

Reasoning:  71%|███████   | 26294/37046 [02:09<03:43, 48.15it/s]

Reasoning:  71%|███████   | 26299/37046 [02:09<03:56, 45.51it/s]

Reasoning:  71%|███████   | 26306/37046 [02:09<03:27, 51.72it/s]

Reasoning:  71%|███████   | 26313/37046 [02:09<03:26, 52.07it/s]

Reasoning:  71%|███████   | 26319/37046 [02:09<03:24, 52.58it/s]

Reasoning:  71%|███████   | 26325/37046 [02:09<03:31, 50.75it/s]

Reasoning:  71%|███████   | 26331/37046 [02:09<03:29, 51.08it/s]

Reasoning:  71%|███████   | 26337/37046 [02:10<03:48, 46.81it/s]

Reasoning:  71%|███████   | 26342/37046 [02:10<04:13, 42.26it/s]

Reasoning:  71%|███████   | 26347/37046 [02:10<04:10, 42.64it/s]

Reasoning:  71%|███████   | 26352/37046 [02:10<04:09, 42.90it/s]

Reasoning:  71%|███████   | 26358/37046 [02:10<04:08, 43.03it/s]

Reasoning:  71%|███████   | 26364/37046 [02:10<03:56, 45.21it/s]

Reasoning:  71%|███████   | 26369/37046 [02:10<04:06, 43.34it/s]

Reasoning:  71%|███████   | 26374/37046 [02:11<04:01, 44.22it/s]

Reasoning:  71%|███████   | 26379/37046 [02:11<04:01, 44.21it/s]

Reasoning:  71%|███████   | 26384/37046 [02:11<04:01, 44.22it/s]

Reasoning:  71%|███████   | 26389/37046 [02:11<04:16, 41.50it/s]

Reasoning:  71%|███████   | 26395/37046 [02:11<03:53, 45.57it/s]

Reasoning:  71%|███████▏  | 26401/37046 [02:11<03:42, 47.81it/s]

Reasoning:  71%|███████▏  | 26406/37046 [02:11<03:48, 46.62it/s]

Reasoning:  71%|███████▏  | 26411/37046 [02:11<03:47, 46.77it/s]

Reasoning:  71%|███████▏  | 26418/37046 [02:11<03:25, 51.69it/s]

Reasoning:  71%|███████▏  | 26424/37046 [02:12<03:20, 53.08it/s]

Reasoning:  71%|███████▏  | 26430/37046 [02:12<03:17, 53.89it/s]

Reasoning:  71%|███████▏  | 26436/37046 [02:12<03:31, 50.19it/s]

Reasoning:  71%|███████▏  | 26442/37046 [02:12<03:31, 50.12it/s]

Reasoning:  71%|███████▏  | 26448/37046 [02:12<03:23, 51.98it/s]

Reasoning:  71%|███████▏  | 26454/37046 [02:12<03:18, 53.30it/s]

Reasoning:  71%|███████▏  | 26460/37046 [02:12<03:13, 54.58it/s]

Reasoning:  72%|███████▏  | 26490/37046 [02:12<01:25, 123.28it/s]

Reasoning:  72%|███████▏  | 26546/37046 [02:12<00:42, 247.56it/s]

Reasoning:  72%|███████▏  | 26595/37046 [02:13<00:32, 316.98it/s]

Reasoning:  72%|███████▏  | 26648/37046 [02:13<00:27, 377.14it/s]

Reasoning:  72%|███████▏  | 26708/37046 [02:13<00:23, 437.84it/s]

Reasoning:  72%|███████▏  | 26762/37046 [02:13<00:22, 467.36it/s]

Reasoning:  72%|███████▏  | 26817/37046 [02:13<00:20, 491.14it/s]

Reasoning:  73%|███████▎  | 26867/37046 [02:13<00:23, 435.86it/s]

Reasoning:  73%|███████▎  | 26912/37046 [02:13<00:26, 389.75it/s]

Reasoning:  73%|███████▎  | 26953/37046 [02:13<00:29, 339.38it/s]

Reasoning:  73%|███████▎  | 26989/37046 [02:13<00:30, 329.65it/s]

Reasoning:  73%|███████▎  | 27026/37046 [02:14<00:29, 339.58it/s]

Reasoning:  73%|███████▎  | 27062/37046 [02:14<00:30, 322.99it/s]

Reasoning:  73%|███████▎  | 27100/37046 [02:14<00:29, 336.77it/s]

Reasoning:  73%|███████▎  | 27135/37046 [02:14<00:31, 315.44it/s]

Reasoning:  73%|███████▎  | 27168/37046 [02:14<00:36, 270.30it/s]

Reasoning:  73%|███████▎  | 27198/37046 [02:14<00:35, 277.06it/s]

Reasoning:  74%|███████▎  | 27233/37046 [02:14<00:33, 295.51it/s]

Reasoning:  74%|███████▎  | 27264/37046 [02:14<00:35, 272.40it/s]

Reasoning:  74%|███████▎  | 27293/37046 [02:15<00:41, 236.06it/s]

Reasoning:  74%|███████▎  | 27321/37046 [02:15<00:39, 245.99it/s]

Reasoning:  74%|███████▍  | 27350/37046 [02:15<00:37, 255.91it/s]

Reasoning:  74%|███████▍  | 27377/37046 [02:15<00:40, 236.73it/s]

Reasoning:  74%|███████▍  | 27405/37046 [02:15<00:39, 246.53it/s]

Reasoning:  74%|███████▍  | 27431/37046 [02:15<00:39, 243.67it/s]

Reasoning:  74%|███████▍  | 27456/37046 [02:15<00:39, 243.37it/s]

Reasoning:  74%|███████▍  | 27484/37046 [02:15<00:37, 252.66it/s]

Reasoning:  74%|███████▍  | 27515/37046 [02:15<00:35, 266.70it/s]

Reasoning:  74%|███████▍  | 27551/37046 [02:16<00:32, 291.02it/s]

Reasoning:  74%|███████▍  | 27581/37046 [02:16<00:32, 286.97it/s]

Reasoning:  75%|███████▍  | 27610/37046 [02:16<00:35, 262.24it/s]

Reasoning:  75%|███████▍  | 27637/37046 [02:16<00:37, 250.94it/s]

Reasoning:  75%|███████▍  | 27663/37046 [02:16<00:41, 227.51it/s]

Reasoning:  75%|███████▍  | 27687/37046 [02:16<00:41, 223.88it/s]

Reasoning:  75%|███████▍  | 27710/37046 [02:16<00:43, 215.87it/s]

Reasoning:  75%|███████▍  | 27732/37046 [02:16<00:46, 202.28it/s]

Reasoning:  75%|███████▍  | 27753/37046 [02:17<00:46, 198.48it/s]

Reasoning:  75%|███████▍  | 27773/37046 [02:17<00:51, 180.96it/s]

Reasoning:  75%|███████▌  | 27792/37046 [02:17<00:53, 174.24it/s]

Reasoning:  75%|███████▌  | 27810/37046 [02:17<00:55, 166.37it/s]

Reasoning:  75%|███████▌  | 27828/37046 [02:17<00:55, 167.58it/s]

Reasoning:  75%|███████▌  | 27845/37046 [02:17<00:57, 160.35it/s]

Reasoning:  75%|███████▌  | 27862/37046 [02:17<00:57, 159.80it/s]

Reasoning:  75%|███████▌  | 27879/37046 [02:17<00:56, 160.97it/s]

Reasoning:  75%|███████▌  | 27896/37046 [02:17<00:57, 157.98it/s]

Reasoning:  75%|███████▌  | 27913/37046 [02:18<00:57, 159.13it/s]

Reasoning:  75%|███████▌  | 27930/37046 [02:18<00:57, 159.39it/s]

Reasoning:  75%|███████▌  | 27949/37046 [02:18<00:54, 166.20it/s]

Reasoning:  75%|███████▌  | 27966/37046 [02:18<00:57, 158.84it/s]

Reasoning:  76%|███████▌  | 27982/37046 [02:18<00:57, 156.28it/s]

Reasoning:  76%|███████▌  | 27998/37046 [02:18<00:58, 155.61it/s]

Reasoning:  76%|███████▌  | 28014/37046 [02:18<01:01, 146.39it/s]

Reasoning:  76%|███████▌  | 28032/37046 [02:18<00:58, 153.69it/s]

Reasoning:  76%|███████▌  | 28056/37046 [02:18<00:51, 176.07it/s]

Reasoning:  76%|███████▌  | 28081/37046 [02:19<00:45, 195.80it/s]

Reasoning:  76%|███████▌  | 28107/37046 [02:19<00:42, 211.91it/s]

Reasoning:  76%|███████▌  | 28133/37046 [02:19<00:40, 221.65it/s]

Reasoning:  76%|███████▌  | 28160/37046 [02:19<00:37, 235.53it/s]

Reasoning:  76%|███████▌  | 28185/37046 [02:19<00:37, 237.99it/s]

Reasoning:  76%|███████▌  | 28212/37046 [02:19<00:35, 246.77it/s]

Reasoning:  76%|███████▌  | 28240/37046 [02:19<00:34, 255.16it/s]

Reasoning:  76%|███████▋  | 28271/37046 [02:19<00:32, 266.71it/s]

Reasoning:  76%|███████▋  | 28301/37046 [02:19<00:31, 274.52it/s]

Reasoning:  76%|███████▋  | 28332/37046 [02:19<00:30, 283.74it/s]

Reasoning:  77%|███████▋  | 28361/37046 [02:20<00:30, 284.84it/s]

Reasoning:  77%|███████▋  | 28390/37046 [02:20<00:31, 272.53it/s]

Reasoning:  77%|███████▋  | 28418/37046 [02:20<00:32, 264.89it/s]

Reasoning:  77%|███████▋  | 28445/37046 [02:20<00:36, 233.23it/s]

Reasoning:  77%|███████▋  | 28470/37046 [02:20<00:38, 224.29it/s]

Reasoning:  77%|███████▋  | 28493/37046 [02:20<00:40, 212.94it/s]

Reasoning:  77%|███████▋  | 28515/37046 [02:20<00:41, 206.17it/s]

Reasoning:  77%|███████▋  | 28536/37046 [02:20<00:43, 193.64it/s]

Reasoning:  77%|███████▋  | 28556/37046 [02:21<00:47, 179.75it/s]

Reasoning:  77%|███████▋  | 28575/37046 [02:21<00:49, 170.53it/s]

Reasoning:  77%|███████▋  | 28593/37046 [02:21<00:51, 164.15it/s]

Reasoning:  77%|███████▋  | 28610/37046 [02:21<00:51, 163.78it/s]

Reasoning:  77%|███████▋  | 28627/37046 [02:21<00:53, 157.48it/s]

Reasoning:  77%|███████▋  | 28644/37046 [02:21<00:52, 160.32it/s]

Reasoning:  77%|███████▋  | 28662/37046 [02:21<00:50, 164.84it/s]

Reasoning:  77%|███████▋  | 28679/37046 [02:21<00:51, 163.24it/s]

Reasoning:  77%|███████▋  | 28696/37046 [02:21<00:52, 159.87it/s]

Reasoning:  78%|███████▊  | 28714/37046 [02:22<00:51, 161.01it/s]

Reasoning:  78%|███████▊  | 28731/37046 [02:22<00:51, 162.52it/s]

Reasoning:  78%|███████▊  | 28748/37046 [02:22<00:53, 156.38it/s]

Reasoning:  78%|███████▊  | 28765/37046 [02:22<00:51, 159.83it/s]

Reasoning:  78%|███████▊  | 28782/37046 [02:22<00:53, 155.10it/s]

Reasoning:  78%|███████▊  | 28798/37046 [02:22<00:55, 148.98it/s]

Reasoning:  78%|███████▊  | 28836/37046 [02:22<00:38, 212.34it/s]

Reasoning:  78%|███████▊  | 28877/37046 [02:22<00:30, 267.88it/s]

Reasoning:  78%|███████▊  | 28919/37046 [02:22<00:26, 311.52it/s]

Reasoning:  78%|███████▊  | 28959/37046 [02:23<00:23, 337.15it/s]

Reasoning:  78%|███████▊  | 28999/37046 [02:23<00:22, 355.53it/s]

Reasoning:  78%|███████▊  | 29038/37046 [02:23<00:21, 364.85it/s]

Reasoning:  78%|███████▊  | 29078/37046 [02:23<00:21, 373.63it/s]

Reasoning:  79%|███████▊  | 29122/37046 [02:23<00:20, 391.46it/s]

Reasoning:  79%|███████▊  | 29165/37046 [02:23<00:19, 401.30it/s]

Reasoning:  79%|███████▉  | 29206/37046 [02:23<00:20, 374.97it/s]

Reasoning:  79%|███████▉  | 29244/37046 [02:23<00:21, 362.06it/s]

Reasoning:  79%|███████▉  | 29281/37046 [02:23<00:23, 337.45it/s]

Reasoning:  79%|███████▉  | 29316/37046 [02:24<00:23, 322.52it/s]

Reasoning:  79%|███████▉  | 29349/37046 [02:24<00:24, 317.84it/s]

Reasoning:  79%|███████▉  | 29384/37046 [02:24<00:23, 326.18it/s]

Reasoning:  79%|███████▉  | 29417/37046 [02:24<00:24, 314.79it/s]

Reasoning:  79%|███████▉  | 29450/37046 [02:24<00:23, 318.09it/s]

Reasoning:  80%|███████▉  | 29483/37046 [02:24<00:23, 319.78it/s]

Reasoning:  80%|███████▉  | 29518/37046 [02:24<00:22, 327.67it/s]

Reasoning:  80%|███████▉  | 29551/37046 [02:24<00:24, 301.08it/s]

Reasoning:  80%|███████▉  | 29582/37046 [02:24<00:29, 252.63it/s]

Reasoning:  80%|███████▉  | 29609/37046 [02:25<00:39, 187.98it/s]

Reasoning:  80%|███████▉  | 29631/37046 [02:25<00:43, 170.00it/s]

Reasoning:  80%|████████  | 29651/37046 [02:25<00:48, 153.49it/s]

Reasoning:  80%|████████  | 29668/37046 [02:25<00:54, 134.97it/s]

Reasoning:  80%|████████  | 29683/37046 [02:25<01:00, 121.34it/s]

Reasoning:  80%|████████  | 29696/37046 [02:26<01:06, 111.17it/s]

Reasoning:  80%|████████  | 29708/37046 [02:26<01:07, 108.30it/s]

Reasoning:  80%|████████  | 29720/37046 [02:26<01:12, 101.61it/s]

Reasoning:  80%|████████  | 29733/37046 [02:26<01:08, 106.73it/s]

Reasoning:  80%|████████  | 29745/37046 [02:26<01:07, 107.72it/s]

Reasoning:  80%|████████  | 29764/37046 [02:26<00:56, 127.92it/s]

Reasoning:  80%|████████  | 29780/37046 [02:26<00:54, 134.55it/s]

Reasoning:  80%|████████  | 29794/37046 [02:26<00:54, 133.46it/s]

Reasoning:  80%|████████  | 29810/37046 [02:26<00:51, 140.36it/s]

Reasoning:  81%|████████  | 29825/37046 [02:27<00:51, 141.47it/s]

Reasoning:  81%|████████  | 29840/37046 [02:27<00:50, 141.53it/s]

Reasoning:  81%|████████  | 29857/37046 [02:27<00:48, 149.40it/s]

Reasoning:  81%|████████  | 29873/37046 [02:27<00:49, 145.92it/s]

Reasoning:  81%|████████  | 29890/37046 [02:27<00:47, 150.33it/s]

Reasoning:  81%|████████  | 29907/37046 [02:27<00:46, 152.51it/s]

Reasoning:  81%|████████  | 29923/37046 [02:27<00:47, 148.73it/s]

Reasoning:  81%|████████  | 29938/37046 [02:27<00:51, 138.90it/s]

Reasoning:  81%|████████  | 29953/37046 [02:27<00:54, 130.40it/s]

Reasoning:  81%|████████  | 29967/37046 [02:28<00:56, 125.14it/s]

Reasoning:  81%|████████  | 30000/37046 [02:28<00:39, 177.84it/s]

Reasoning:  81%|████████  | 30036/37046 [02:28<00:30, 226.59it/s]

Reasoning:  81%|████████  | 30071/37046 [02:28<00:26, 259.97it/s]

Reasoning:  81%|████████▏ | 30106/37046 [02:28<00:24, 284.06it/s]

Reasoning:  81%|████████▏ | 30139/37046 [02:28<00:23, 293.94it/s]

Reasoning:  81%|████████▏ | 30169/37046 [02:28<00:24, 284.46it/s]

Reasoning:  82%|████████▏ | 30198/37046 [02:28<00:25, 271.87it/s]

Reasoning:  82%|████████▏ | 30226/37046 [02:28<00:25, 272.48it/s]

Reasoning:  82%|████████▏ | 30254/37046 [02:29<00:25, 267.17it/s]

Reasoning:  82%|████████▏ | 30283/37046 [02:29<00:24, 272.01it/s]

Reasoning:  82%|████████▏ | 30312/37046 [02:29<00:24, 274.85it/s]

Reasoning:  82%|████████▏ | 30340/37046 [02:29<00:24, 276.26it/s]

Reasoning:  82%|████████▏ | 30368/37046 [02:29<00:27, 245.07it/s]

Reasoning:  82%|████████▏ | 30394/37046 [02:29<00:32, 204.02it/s]

Reasoning:  82%|████████▏ | 30416/37046 [02:29<00:34, 189.89it/s]

Reasoning:  82%|████████▏ | 30437/37046 [02:29<00:38, 170.33it/s]

Reasoning:  82%|████████▏ | 30455/37046 [02:30<00:41, 160.71it/s]

Reasoning:  82%|████████▏ | 30472/37046 [02:30<00:43, 150.00it/s]

Reasoning:  82%|████████▏ | 30490/37046 [02:30<00:42, 155.94it/s]

Reasoning:  82%|████████▏ | 30510/37046 [02:30<00:39, 164.28it/s]

Reasoning:  82%|████████▏ | 30529/37046 [02:30<00:38, 170.93it/s]

Reasoning:  82%|████████▏ | 30549/37046 [02:30<00:36, 177.82it/s]

Reasoning:  83%|████████▎ | 30568/37046 [02:30<00:38, 166.77it/s]

Reasoning:  83%|████████▎ | 30586/37046 [02:30<00:38, 169.85it/s]

Reasoning:  83%|████████▎ | 30604/37046 [02:31<00:38, 166.70it/s]

Reasoning:  83%|████████▎ | 30624/37046 [02:31<00:36, 174.27it/s]

Reasoning:  83%|████████▎ | 30642/37046 [02:31<00:36, 174.89it/s]

Reasoning:  83%|████████▎ | 30661/37046 [02:31<00:35, 178.19it/s]

Reasoning:  83%|████████▎ | 30687/37046 [02:31<00:32, 196.91it/s]

Reasoning:  83%|████████▎ | 30707/37046 [02:31<00:32, 194.97it/s]

Reasoning:  83%|████████▎ | 30727/37046 [02:31<00:32, 195.97it/s]

Reasoning:  83%|████████▎ | 30747/37046 [02:31<00:37, 169.17it/s]

Reasoning:  83%|████████▎ | 30765/37046 [02:32<00:57, 109.24it/s]

Reasoning:  83%|████████▎ | 30779/37046 [02:32<01:06, 93.96it/s]

Reasoning:  83%|████████▎ | 30791/37046 [02:32<01:19, 78.72it/s]

Reasoning:  83%|████████▎ | 30801/37046 [02:32<01:30, 69.23it/s]

Reasoning:  83%|████████▎ | 30810/37046 [02:32<01:38, 63.09it/s]

Reasoning:  83%|████████▎ | 30818/37046 [02:33<01:40, 62.10it/s]

Reasoning:  83%|████████▎ | 30825/37046 [02:33<01:52, 55.20it/s]

Reasoning:  83%|████████▎ | 30831/37046 [02:33<02:02, 50.74it/s]

Reasoning:  83%|████████▎ | 30837/37046 [02:33<02:09, 48.04it/s]

Reasoning:  83%|████████▎ | 30842/37046 [02:33<02:13, 46.42it/s]

Reasoning:  83%|████████▎ | 30847/37046 [02:33<02:15, 45.73it/s]

Reasoning:  83%|████████▎ | 30852/37046 [02:33<02:21, 43.84it/s]

Reasoning:  83%|████████▎ | 30857/37046 [02:34<02:22, 43.47it/s]

Reasoning:  83%|████████▎ | 30865/37046 [02:34<02:00, 51.33it/s]

Reasoning:  83%|████████▎ | 30871/37046 [02:34<01:55, 53.40it/s]

Reasoning:  83%|████████▎ | 30877/37046 [02:34<01:52, 54.71it/s]

Reasoning:  83%|████████▎ | 30884/37046 [02:34<01:49, 56.48it/s]

Reasoning:  83%|████████▎ | 30890/37046 [02:34<02:02, 50.38it/s]

Reasoning:  83%|████████▎ | 30897/37046 [02:34<01:52, 54.49it/s]

Reasoning:  83%|████████▎ | 30904/37046 [02:34<01:49, 56.07it/s]

Reasoning:  83%|████████▎ | 30910/37046 [02:35<01:57, 52.36it/s]

Reasoning:  83%|████████▎ | 30916/37046 [02:35<01:58, 51.76it/s]

Reasoning:  83%|████████▎ | 30924/37046 [02:35<01:43, 58.94it/s]

Reasoning:  83%|████████▎ | 30931/37046 [02:35<01:47, 56.87it/s]

Reasoning:  84%|████████▎ | 30938/37046 [02:35<01:41, 60.27it/s]

Reasoning:  84%|████████▎ | 30946/37046 [02:35<01:35, 64.18it/s]

Reasoning:  84%|████████▎ | 30953/37046 [02:35<01:41, 60.20it/s]

Reasoning:  84%|████████▎ | 30960/37046 [02:35<01:37, 62.48it/s]

Reasoning:  84%|████████▎ | 30967/37046 [02:35<01:36, 62.82it/s]

Reasoning:  84%|████████▎ | 30975/37046 [02:36<01:32, 65.55it/s]

Reasoning:  84%|████████▎ | 30982/37046 [02:36<01:37, 62.46it/s]

Reasoning:  84%|████████▎ | 30989/37046 [02:36<01:35, 63.56it/s]

Reasoning:  84%|████████▎ | 30996/37046 [02:36<01:42, 59.00it/s]

Reasoning:  84%|████████▎ | 31002/37046 [02:36<01:43, 58.32it/s]

Reasoning:  84%|████████▎ | 31008/37046 [02:36<01:45, 57.10it/s]

Reasoning:  84%|████████▎ | 31014/37046 [02:36<01:53, 53.25it/s]

Reasoning:  84%|████████▎ | 31020/37046 [02:36<01:53, 53.19it/s]

Reasoning:  84%|████████▍ | 31027/37046 [02:36<01:47, 56.03it/s]

Reasoning:  84%|████████▍ | 31033/37046 [02:37<01:48, 55.57it/s]

Reasoning:  84%|████████▍ | 31039/37046 [02:37<01:58, 50.90it/s]

Reasoning:  84%|████████▍ | 31045/37046 [02:37<01:59, 50.25it/s]

Reasoning:  84%|████████▍ | 31052/37046 [02:37<01:50, 54.32it/s]

Reasoning:  84%|████████▍ | 31059/37046 [02:37<01:46, 56.11it/s]

Reasoning:  84%|████████▍ | 31065/37046 [02:37<01:46, 56.06it/s]

Reasoning:  84%|████████▍ | 31071/37046 [02:37<01:58, 50.58it/s]

Reasoning:  84%|████████▍ | 31077/37046 [02:37<01:53, 52.41it/s]

Reasoning:  84%|████████▍ | 31085/37046 [02:38<01:43, 57.42it/s]

Reasoning:  84%|████████▍ | 31092/37046 [02:38<01:39, 59.99it/s]

Reasoning:  84%|████████▍ | 31099/37046 [02:38<01:35, 61.99it/s]

Reasoning:  84%|████████▍ | 31106/37046 [02:38<01:37, 60.90it/s]

Reasoning:  84%|████████▍ | 31113/37046 [02:38<01:49, 54.31it/s]

Reasoning:  84%|████████▍ | 31121/37046 [02:38<01:42, 57.94it/s]

Reasoning:  84%|████████▍ | 31127/37046 [02:38<01:46, 55.56it/s]

Reasoning:  84%|████████▍ | 31153/37046 [02:38<00:54, 108.13it/s]

Reasoning:  84%|████████▍ | 31207/37046 [02:38<00:26, 222.93it/s]

Reasoning:  84%|████████▍ | 31262/37046 [02:39<00:18, 311.61it/s]

Reasoning:  85%|████████▍ | 31309/37046 [02:39<00:16, 355.33it/s]

Reasoning:  85%|████████▍ | 31353/37046 [02:39<00:15, 378.55it/s]

Reasoning:  85%|████████▍ | 31396/37046 [02:39<00:14, 391.37it/s]

Reasoning:  85%|████████▍ | 31447/37046 [02:39<00:13, 424.91it/s]

Reasoning:  85%|████████▌ | 31504/37046 [02:39<00:11, 466.34it/s]

Reasoning:  85%|████████▌ | 31552/37046 [02:39<00:11, 470.36it/s]

Reasoning:  85%|████████▌ | 31600/37046 [02:39<00:12, 425.34it/s]

Reasoning:  85%|████████▌ | 31644/37046 [02:39<00:13, 389.35it/s]

Reasoning:  86%|████████▌ | 31685/37046 [02:40<00:14, 362.15it/s]

Reasoning:  86%|████████▌ | 31723/37046 [02:40<00:15, 346.93it/s]

Reasoning:  86%|████████▌ | 31759/37046 [02:40<00:16, 319.57it/s]

Reasoning:  86%|████████▌ | 31792/37046 [02:40<00:16, 311.94it/s]

Reasoning:  86%|████████▌ | 31824/37046 [02:40<00:17, 299.32it/s]

Reasoning:  86%|████████▌ | 31855/37046 [02:40<00:17, 292.99it/s]

Reasoning:  86%|████████▌ | 31889/37046 [02:40<00:17, 298.17it/s]

Reasoning:  86%|████████▌ | 31928/37046 [02:40<00:15, 321.04it/s]

Reasoning:  86%|████████▋ | 31969/37046 [02:41<00:14, 343.94it/s]

Reasoning:  86%|████████▋ | 32010/37046 [02:41<00:13, 361.46it/s]

Reasoning:  87%|████████▋ | 32047/37046 [02:41<00:13, 362.81it/s]

Reasoning:  87%|████████▋ | 32084/37046 [02:41<00:15, 311.15it/s]

Reasoning:  87%|████████▋ | 32121/37046 [02:41<00:15, 325.75it/s]

Reasoning:  87%|████████▋ | 32157/37046 [02:41<00:14, 331.92it/s]

Reasoning:  87%|████████▋ | 32192/37046 [02:41<00:14, 331.29it/s]

Reasoning:  87%|████████▋ | 32227/37046 [02:41<00:16, 296.69it/s]

Reasoning:  87%|████████▋ | 32277/37046 [02:41<00:13, 348.87it/s]

Reasoning:  87%|████████▋ | 32330/37046 [02:42<00:11, 397.83it/s]

Reasoning:  87%|████████▋ | 32383/37046 [02:42<00:10, 433.73it/s]

Reasoning:  88%|████████▊ | 32433/37046 [02:42<00:10, 452.33it/s]

Reasoning:  88%|████████▊ | 32482/37046 [02:42<00:09, 462.01it/s]

Reasoning:  88%|████████▊ | 32529/37046 [02:42<00:09, 463.74it/s]

Reasoning:  88%|████████▊ | 32584/37046 [02:42<00:09, 484.41it/s]

Reasoning:  88%|████████▊ | 32636/37046 [02:42<00:09, 488.18it/s]

Reasoning:  88%|████████▊ | 32687/37046 [02:42<00:08, 491.85it/s]

Reasoning:  88%|████████▊ | 32737/37046 [02:42<00:09, 465.13it/s]

Reasoning:  88%|████████▊ | 32784/37046 [02:42<00:10, 422.00it/s]

Reasoning:  89%|████████▊ | 32828/37046 [02:43<00:10, 406.13it/s]

Reasoning:  89%|████████▊ | 32871/37046 [02:43<00:10, 412.30it/s]

Reasoning:  89%|████████▉ | 32914/37046 [02:43<00:09, 415.82it/s]

Reasoning:  89%|████████▉ | 32957/37046 [02:43<00:09, 417.90it/s]

Reasoning:  89%|████████▉ | 33002/37046 [02:43<00:09, 424.99it/s]

Reasoning:  89%|████████▉ | 33046/37046 [02:43<00:09, 426.92it/s]

Reasoning:  89%|████████▉ | 33089/37046 [02:43<00:10, 377.19it/s]

Reasoning:  89%|████████▉ | 33128/37046 [02:43<00:11, 336.08it/s]

Reasoning:  90%|████████▉ | 33164/37046 [02:44<00:12, 301.22it/s]

Reasoning:  90%|████████▉ | 33196/37046 [02:44<00:15, 249.52it/s]

Reasoning:  90%|████████▉ | 33224/37046 [02:44<00:20, 187.38it/s]

Reasoning:  90%|████████▉ | 33247/37046 [02:44<00:21, 174.06it/s]

Reasoning:  90%|████████▉ | 33267/37046 [02:44<00:24, 151.56it/s]

Reasoning:  90%|████████▉ | 33284/37046 [02:45<00:27, 134.62it/s]

Reasoning:  90%|████████▉ | 33299/37046 [02:45<00:29, 126.07it/s]

Reasoning:  90%|████████▉ | 33313/37046 [02:45<00:30, 121.41it/s]

Reasoning:  90%|████████▉ | 33326/37046 [02:45<00:31, 117.88it/s]

Reasoning:  90%|█████████ | 33344/37046 [02:45<00:28, 130.10it/s]

Reasoning:  90%|█████████ | 33358/37046 [02:45<00:28, 130.29it/s]

Reasoning:  90%|█████████ | 33372/37046 [02:45<00:27, 132.18it/s]

Reasoning:  90%|█████████ | 33389/37046 [02:45<00:26, 139.20it/s]

Reasoning:  90%|█████████ | 33404/37046 [02:46<00:27, 132.28it/s]

Reasoning:  90%|█████████ | 33421/37046 [02:46<00:25, 140.73it/s]

Reasoning:  90%|█████████ | 33436/37046 [02:46<00:26, 135.54it/s]

Reasoning:  90%|█████████ | 33451/37046 [02:46<00:26, 137.34it/s]

Reasoning:  90%|█████████ | 33468/37046 [02:46<00:24, 145.75it/s]

Reasoning:  90%|█████████ | 33483/37046 [02:46<00:24, 144.91it/s]

Reasoning:  90%|█████████ | 33503/37046 [02:46<00:22, 158.00it/s]

Reasoning:  90%|█████████ | 33519/37046 [02:46<00:23, 150.82it/s]

Reasoning:  91%|█████████ | 33535/37046 [02:46<00:24, 144.04it/s]

Reasoning:  91%|█████████ | 33550/37046 [02:47<00:25, 135.68it/s]

Reasoning:  91%|█████████ | 33564/37046 [02:47<00:26, 132.99it/s]

Reasoning:  91%|█████████ | 33592/37046 [02:47<00:20, 171.74it/s]

Reasoning:  91%|█████████ | 33628/37046 [02:47<00:15, 223.62it/s]

Reasoning:  91%|█████████ | 33660/37046 [02:47<00:13, 249.26it/s]

Reasoning:  91%|█████████ | 33687/37046 [02:47<00:13, 253.60it/s]

Reasoning:  91%|█████████ | 33715/37046 [02:47<00:12, 260.86it/s]

Reasoning:  91%|█████████ | 33742/37046 [02:47<00:12, 262.80it/s]

Reasoning:  91%|█████████ | 33769/37046 [02:47<00:12, 264.74it/s]

Reasoning:  91%|█████████ | 33797/37046 [02:47<00:12, 268.22it/s]

Reasoning:  91%|█████████▏| 33824/37046 [02:48<00:12, 262.12it/s]

Reasoning:  91%|█████████▏| 33851/37046 [02:48<00:12, 263.70it/s]

Reasoning:  91%|█████████▏| 33882/37046 [02:48<00:11, 277.19it/s]

Reasoning:  92%|█████████▏| 33913/37046 [02:48<00:10, 285.85it/s]

Reasoning:  92%|█████████▏| 33942/37046 [02:48<00:10, 283.11it/s]

Reasoning:  92%|█████████▏| 33971/37046 [02:48<00:12, 252.32it/s]

Reasoning:  92%|█████████▏| 33997/37046 [02:48<00:15, 202.24it/s]

Reasoning:  92%|█████████▏| 34020/37046 [02:48<00:16, 181.66it/s]

Reasoning:  92%|█████████▏| 34040/37046 [02:49<00:17, 168.64it/s]

Reasoning:  92%|█████████▏| 34058/37046 [02:49<00:17, 166.13it/s]

Reasoning:  92%|█████████▏| 34078/37046 [02:49<00:17, 173.88it/s]

Reasoning:  92%|█████████▏| 34097/37046 [02:49<00:18, 163.40it/s]

Reasoning:  92%|█████████▏| 34114/37046 [02:49<00:17, 164.69it/s]

Reasoning:  92%|█████████▏| 34135/37046 [02:49<00:16, 175.74it/s]

Reasoning:  92%|█████████▏| 34156/37046 [02:49<00:15, 183.65it/s]

Reasoning:  92%|█████████▏| 34175/37046 [02:49<00:15, 182.82it/s]

Reasoning:  92%|█████████▏| 34195/37046 [02:49<00:15, 186.38it/s]

Reasoning:  92%|█████████▏| 34214/37046 [02:50<00:15, 179.73it/s]

Reasoning:  92%|█████████▏| 34233/37046 [02:50<00:16, 171.45it/s]

Reasoning:  92%|█████████▏| 34251/37046 [02:50<00:16, 171.91it/s]

Reasoning:  93%|█████████▎| 34269/37046 [02:50<00:16, 173.50it/s]

Reasoning:  93%|█████████▎| 34292/37046 [02:50<00:14, 184.50it/s]

Reasoning:  93%|█████████▎| 34313/37046 [02:50<00:14, 189.95it/s]

Reasoning:  93%|█████████▎| 34333/37046 [02:50<00:14, 185.48it/s]

Reasoning:  93%|█████████▎| 34352/37046 [02:50<00:17, 152.26it/s]

Reasoning:  93%|█████████▎| 34369/37046 [02:51<00:30, 87.63it/s]

Reasoning:  93%|█████████▎| 34382/37046 [02:51<00:36, 72.24it/s]

Reasoning:  93%|█████████▎| 34393/37046 [02:51<00:38, 69.13it/s]

Reasoning:  93%|█████████▎| 34402/37046 [02:52<00:42, 62.21it/s]

Reasoning:  93%|█████████▎| 34410/37046 [02:52<00:48, 54.79it/s]

Reasoning:  93%|█████████▎| 34417/37046 [02:52<00:51, 51.23it/s]

Reasoning:  93%|█████████▎| 34423/37046 [02:52<00:54, 48.11it/s]

Reasoning:  93%|█████████▎| 34429/37046 [02:52<00:56, 46.39it/s]

Reasoning:  93%|█████████▎| 34435/37046 [02:52<00:54, 48.04it/s]

Reasoning:  93%|█████████▎| 34441/37046 [02:52<00:52, 49.40it/s]

Reasoning:  93%|█████████▎| 34447/37046 [02:53<00:52, 49.11it/s]

Reasoning:  93%|█████████▎| 34453/37046 [02:53<00:50, 51.17it/s]

Reasoning:  93%|█████████▎| 34459/37046 [02:53<00:50, 50.73it/s]

Reasoning:  93%|█████████▎| 34467/37046 [02:53<00:44, 58.18it/s]

Reasoning:  93%|█████████▎| 34474/37046 [02:53<00:49, 52.17it/s]

Reasoning:  93%|█████████▎| 34481/37046 [02:53<00:46, 54.89it/s]

Reasoning:  93%|█████████▎| 34488/37046 [02:53<00:44, 57.28it/s]

Reasoning:  93%|█████████▎| 34494/37046 [02:53<00:44, 57.80it/s]

Reasoning:  93%|█████████▎| 34500/37046 [02:53<00:43, 57.93it/s]

Reasoning:  93%|█████████▎| 34507/37046 [02:54<00:41, 61.03it/s]

Reasoning:  93%|█████████▎| 34514/37046 [02:54<00:45, 55.95it/s]

Reasoning:  93%|█████████▎| 34520/37046 [02:54<00:45, 56.09it/s]

Reasoning:  93%|█████████▎| 34529/37046 [02:54<00:38, 64.59it/s]

Reasoning:  93%|█████████▎| 34536/37046 [02:54<00:43, 57.97it/s]

Reasoning:  93%|█████████▎| 34543/37046 [02:54<00:41, 60.29it/s]

Reasoning:  93%|█████████▎| 34550/37046 [02:54<00:44, 56.53it/s]

Reasoning:  93%|█████████▎| 34556/37046 [02:54<00:50, 49.01it/s]

Reasoning:  93%|█████████▎| 34562/37046 [02:55<00:52, 47.65it/s]

Reasoning:  93%|█████████▎| 34568/37046 [02:55<00:51, 48.49it/s]

Reasoning:  93%|█████████▎| 34573/37046 [02:55<00:51, 48.38it/s]

Reasoning:  93%|█████████▎| 34579/37046 [02:55<00:48, 51.25it/s]

Reasoning:  93%|█████████▎| 34585/37046 [02:55<00:50, 48.66it/s]

Reasoning:  93%|█████████▎| 34591/37046 [02:55<00:47, 51.39it/s]

Reasoning:  93%|█████████▎| 34597/37046 [02:55<00:55, 44.13it/s]

Reasoning:  93%|█████████▎| 34604/37046 [02:55<00:50, 48.04it/s]

Reasoning:  93%|█████████▎| 34610/37046 [02:56<00:52, 46.83it/s]

Reasoning:  93%|█████████▎| 34615/37046 [02:56<00:51, 47.50it/s]

Reasoning:  93%|█████████▎| 34620/37046 [02:56<00:50, 48.02it/s]

Reasoning:  93%|█████████▎| 34625/37046 [02:56<00:50, 48.36it/s]

Reasoning:  93%|█████████▎| 34633/37046 [02:56<00:42, 56.43it/s]

Reasoning:  94%|█████████▎| 34639/37046 [02:56<00:42, 56.76it/s]

Reasoning:  94%|█████████▎| 34645/37046 [02:56<00:43, 54.94it/s]

Reasoning:  94%|█████████▎| 34651/37046 [02:56<00:43, 54.69it/s]

Reasoning:  94%|█████████▎| 34659/37046 [02:56<00:39, 60.59it/s]

Reasoning:  94%|█████████▎| 34666/37046 [02:57<00:38, 62.15it/s]

Reasoning:  94%|█████████▎| 34675/37046 [02:57<00:34, 68.11it/s]

Reasoning:  94%|█████████▎| 34682/37046 [02:57<00:38, 62.07it/s]

Reasoning:  94%|█████████▎| 34689/37046 [02:57<00:36, 63.79it/s]

Reasoning:  94%|█████████▎| 34696/37046 [02:57<00:37, 62.06it/s]

Reasoning:  94%|█████████▎| 34703/37046 [02:57<00:38, 60.83it/s]

Reasoning:  94%|█████████▎| 34710/37046 [02:57<00:39, 58.61it/s]

Reasoning:  94%|█████████▎| 34716/37046 [02:57<00:41, 55.68it/s]

Reasoning:  94%|█████████▎| 34722/37046 [02:58<00:43, 53.83it/s]

Reasoning:  94%|█████████▎| 34728/37046 [02:58<00:42, 54.11it/s]

Reasoning:  94%|█████████▍| 34734/37046 [02:58<00:43, 53.58it/s]

Reasoning:  94%|█████████▍| 34779/37046 [02:58<00:14, 158.76it/s]

Reasoning:  94%|█████████▍| 34822/37046 [02:58<00:09, 233.21it/s]

Reasoning:  94%|█████████▍| 34865/37046 [02:58<00:07, 287.80it/s]

Reasoning:  94%|█████████▍| 34906/37046 [02:58<00:06, 321.01it/s]

Reasoning:  94%|█████████▍| 34949/37046 [02:58<00:05, 350.95it/s]

Reasoning:  94%|█████████▍| 34989/37046 [02:58<00:05, 363.57it/s]

Reasoning:  95%|█████████▍| 35033/37046 [02:58<00:05, 381.83it/s]

Reasoning:  95%|█████████▍| 35079/37046 [02:59<00:04, 402.38it/s]

Reasoning:  95%|█████████▍| 35120/37046 [02:59<00:04, 392.76it/s]

Reasoning:  95%|█████████▍| 35160/37046 [02:59<00:05, 368.96it/s]

Reasoning:  95%|█████████▌| 35198/37046 [02:59<00:05, 354.51it/s]

Reasoning:  95%|█████████▌| 35234/37046 [02:59<00:05, 319.03it/s]

Reasoning:  95%|█████████▌| 35267/37046 [02:59<00:05, 299.84it/s]

Reasoning:  95%|█████████▌| 35300/37046 [02:59<00:05, 305.48it/s]

Reasoning:  95%|█████████▌| 35332/37046 [02:59<00:05, 306.30it/s]

Reasoning:  95%|█████████▌| 35363/37046 [03:00<00:05, 295.79it/s]

Reasoning:  96%|█████████▌| 35394/37046 [03:00<00:05, 299.48it/s]

Reasoning:  96%|█████████▌| 35440/37046 [03:00<00:04, 342.94it/s]

Reasoning:  96%|█████████▌| 35478/37046 [03:00<00:04, 352.34it/s]

Reasoning:  96%|█████████▌| 35521/37046 [03:00<00:04, 374.04it/s]

Reasoning:  96%|█████████▌| 35572/37046 [03:00<00:03, 413.59it/s]

Reasoning:  96%|█████████▌| 35621/37046 [03:00<00:03, 434.91it/s]

Reasoning:  96%|█████████▋| 35688/37046 [03:00<00:02, 503.77it/s]

Reasoning:  96%|█████████▋| 35739/37046 [03:00<00:02, 488.27it/s]

Reasoning:  97%|█████████▋| 35789/37046 [03:00<00:02, 458.74it/s]

Reasoning:  97%|█████████▋| 35836/37046 [03:01<00:03, 319.51it/s]

Reasoning:  97%|█████████▋| 35881/37046 [03:01<00:03, 346.85it/s]

Reasoning:  97%|█████████▋| 35951/37046 [03:01<00:02, 429.63it/s]

Reasoning:  97%|█████████▋| 36000/37046 [03:01<00:02, 443.74it/s]

Reasoning:  97%|█████████▋| 36058/37046 [03:01<00:02, 479.48it/s]

Reasoning:  97%|█████████▋| 36114/37046 [03:01<00:01, 498.63it/s]

Reasoning:  98%|█████████▊| 36173/37046 [03:01<00:01, 523.46it/s]

Reasoning:  98%|█████████▊| 36228/37046 [03:01<00:01, 524.81it/s]

Reasoning:  98%|█████████▊| 36282/37046 [03:02<00:01, 510.06it/s]

Reasoning:  98%|█████████▊| 36335/37046 [03:02<00:02, 329.79it/s]

Reasoning:  98%|█████████▊| 36381/37046 [03:02<00:01, 351.52it/s]

Reasoning:  98%|█████████▊| 36435/37046 [03:02<00:01, 379.88it/s]

Reasoning:  98%|█████████▊| 36482/37046 [03:02<00:01, 401.00it/s]

Reasoning:  99%|█████████▊| 36527/37046 [03:02<00:01, 400.42it/s]

Reasoning:  99%|█████████▉| 36585/37046 [03:02<00:01, 446.89it/s]

Reasoning:  99%|█████████▉| 36633/37046 [03:03<00:01, 412.41it/s]

Reasoning:  99%|█████████▉| 36677/37046 [03:03<00:00, 382.19it/s]

Reasoning:  99%|█████████▉| 36718/37046 [03:03<00:00, 385.71it/s]

Reasoning:  99%|█████████▉| 36758/37046 [03:03<00:00, 330.29it/s]

Reasoning:  99%|█████████▉| 36794/37046 [03:03<00:00, 328.57it/s]

Reasoning:  99%|█████████▉| 36829/37046 [03:03<00:00, 321.08it/s]

Reasoning: 100%|█████████▉| 36869/37046 [03:03<00:00, 341.08it/s]

Reasoning: 100%|█████████▉| 36908/37046 [03:03<00:00, 350.49it/s]

Reasoning: 100%|█████████▉| 36952/37046 [03:03<00:00, 369.52it/s]

Reasoning: 100%|█████████▉| 36998/37046 [03:04<00:00, 394.21it/s]

Reasoning: 100%|█████████▉| 37039/37046 [03:04<00:00, 394.24it/s]

Reasoning: 100%|██████████| 37046/37046 [03:04<00:00, 201.12it/s]

Rationale:   0%|          | 0/36679 [00:00<?, ?it/s]

Rationale:   1%|          | 438/36679 [00:00<00:08, 4359.05it/s]

Rationale:   2%|▏         | 874/36679 [00:00<00:09, 3595.66it/s]

Rationale:   3%|▎         | 1242/36679 [00:00<00:10, 3502.07it/s]

Rationale:   4%|▍         | 1597/36679 [00:00<00:10, 3482.58it/s]

Rationale:   6%|▌         | 2039/36679 [00:00<00:09, 3787.36it/s]

Rationale:   7%|▋         | 2422/36679 [00:00<00:09, 3777.15it/s]

Rationale:   8%|▊         | 2806/36679 [00:00<00:08, 3785.52it/s]

Rationale:   9%|▊         | 3196/36679 [00:00<00:08, 3819.27it/s]

Rationale:  10%|▉         | 3592/36679 [00:00<00:08, 3852.63it/s]

Rationale:  11%|█         | 3979/36679 [00:01<00:08, 3772.38it/s]

Rationale:  12%|█▏        | 4448/36679 [00:01<00:07, 4039.53it/s]

Rationale:  14%|█▍        | 5051/36679 [00:01<00:06, 4626.69it/s]

Rationale:  15%|█▌        | 5516/36679 [00:01<00:07, 4445.90it/s]

Rationale:  16%|█▋        | 5970/36679 [00:01<00:06, 4462.58it/s]

Rationale:  18%|█▊        | 6482/36679 [00:01<00:06, 4648.70it/s]

Rationale:  19%|█▉        | 6984/36679 [00:01<00:06, 4744.56it/s]

Rationale:  20%|██        | 7460/36679 [00:01<00:06, 4667.40it/s]

Rationale:  22%|██▏       | 7928/36679 [00:01<00:06, 4562.17it/s]

Rationale:  23%|██▎       | 8386/36679 [00:02<00:06, 4362.50it/s]

Rationale:  24%|██▍       | 8825/36679 [00:02<00:06, 4175.52it/s]

Rationale:  25%|██▌       | 9325/36679 [00:02<00:06, 4398.93it/s]

Rationale:  27%|██▋       | 9769/36679 [00:02<00:06, 4015.20it/s]

Rationale:  28%|██▊       | 10179/36679 [00:02<00:07, 3397.57it/s]

Rationale:  29%|██▊       | 10538/36679 [00:02<00:08, 3145.09it/s]

Rationale:  30%|██▉       | 10867/36679 [00:02<00:08, 3030.56it/s]

Rationale:  31%|███       | 11208/36679 [00:02<00:08, 3123.51it/s]

Rationale:  31%|███▏      | 11529/36679 [00:03<00:08, 3033.04it/s]

Rationale:  32%|███▏      | 11838/36679 [00:03<00:08, 2966.31it/s]

Rationale:  33%|███▎      | 12139/36679 [00:03<00:08, 2959.09it/s]

Rationale:  34%|███▍      | 12448/36679 [00:03<00:08, 2989.36it/s]

Rationale:  35%|███▍      | 12753/36679 [00:03<00:07, 3005.20it/s]

Rationale:  36%|███▌      | 13115/36679 [00:03<00:07, 3181.40it/s]

Rationale:  37%|███▋      | 13471/36679 [00:03<00:07, 3289.82it/s]

Rationale:  38%|███▊      | 14083/36679 [00:03<00:05, 4109.01it/s]

Rationale:  40%|███▉      | 14544/36679 [00:03<00:05, 4255.12it/s]

Rationale:  41%|████      | 14975/36679 [00:03<00:05, 4261.31it/s]

Rationale:  42%|████▏     | 15508/36679 [00:04<00:04, 4570.38it/s]

Rationale:  44%|████▎     | 15985/36679 [00:04<00:04, 4626.26it/s]

Rationale:  45%|████▍     | 16481/36679 [00:04<00:04, 4723.09it/s]

Rationale:  46%|████▋     | 17017/36679 [00:04<00:04, 4908.00it/s]

Rationale:  48%|████▊     | 17519/36679 [00:04<00:03, 4929.76it/s]

Rationale:  49%|████▉     | 18090/36679 [00:04<00:03, 5147.89it/s]

Rationale:  51%|█████     | 18614/36679 [00:04<00:03, 5174.91it/s]

Rationale:  52%|█████▏    | 19132/36679 [00:04<00:04, 4369.51it/s]

Rationale:  53%|█████▎    | 19591/36679 [00:04<00:04, 4060.53it/s]

Rationale:  55%|█████▍    | 20015/36679 [00:05<00:04, 4035.27it/s]

Rationale:  56%|█████▌    | 20431/36679 [00:05<00:04, 3732.26it/s]

Rationale:  57%|█████▋    | 20816/36679 [00:05<00:04, 3681.06it/s]

Rationale:  58%|█████▊    | 21192/36679 [00:05<00:04, 3664.45it/s]

Rationale:  59%|█████▉    | 21564/36679 [00:05<00:04, 3552.19it/s]

Rationale:  60%|█████▉    | 21923/36679 [00:05<00:04, 3375.95it/s]

Rationale:  61%|██████    | 22264/36679 [00:05<00:04, 3224.67it/s]

Rationale:  62%|██████▏   | 22601/36679 [00:05<00:04, 3255.36it/s]

Rationale:  63%|██████▎   | 23032/36679 [00:05<00:03, 3539.60it/s]

Rationale:  64%|██████▍   | 23390/36679 [00:06<00:03, 3351.90it/s]

Rationale:  65%|██████▍   | 23730/36679 [00:06<00:04, 3007.62it/s]

Rationale:  66%|██████▌   | 24039/36679 [00:06<00:04, 2877.91it/s]

Rationale:  66%|██████▋   | 24333/36679 [00:06<00:04, 2798.42it/s]

Rationale:  67%|██████▋   | 24656/36679 [00:06<00:04, 2912.14it/s]

Rationale:  68%|██████▊   | 24958/36679 [00:06<00:03, 2938.83it/s]

Rationale:  69%|██████▉   | 25255/36679 [00:06<00:03, 2904.75it/s]

Rationale:  70%|██████▉   | 25548/36679 [00:06<00:03, 2846.46it/s]

Rationale:  70%|███████   | 25846/36679 [00:06<00:03, 2883.66it/s]

Rationale:  71%|███████▏  | 26173/36679 [00:07<00:03, 2987.88it/s]

Rationale:  72%|███████▏  | 26477/36679 [00:07<00:03, 2999.12it/s]

Rationale:  73%|███████▎  | 26778/36679 [00:07<00:03, 2964.84it/s]

Rationale:  74%|███████▍  | 27155/36679 [00:07<00:02, 3193.07it/s]

Rationale:  76%|███████▌  | 27706/36679 [00:07<00:02, 3870.66it/s]

Rationale:  77%|███████▋  | 28137/36679 [00:07<00:02, 3990.89it/s]

Rationale:  78%|███████▊  | 28611/36679 [00:07<00:01, 4204.74it/s]

Rationale:  79%|███████▉  | 29033/36679 [00:07<00:01, 4121.59it/s]

Rationale:  81%|████████  | 29562/36679 [00:07<00:01, 4464.43it/s]

Rationale:  82%|████████▏ | 30020/36679 [00:07<00:01, 4485.33it/s]

Rationale:  83%|████████▎ | 30528/36679 [00:08<00:01, 4650.55it/s]

Rationale:  85%|████████▍ | 31068/36679 [00:08<00:01, 4866.11it/s]

Rationale:  86%|████████▌ | 31566/36679 [00:08<00:01, 4887.78it/s]

Rationale:  88%|████████▊ | 32169/36679 [00:08<00:00, 5216.01it/s]

Rationale:  89%|████████▉ | 32692/36679 [00:08<00:00, 5104.85it/s]

Rationale:  91%|█████████ | 33204/36679 [00:08<00:00, 4796.82it/s]

Rationale:  92%|█████████▏| 33688/36679 [00:08<00:00, 4524.47it/s]

Rationale:  93%|█████████▎| 34246/36679 [00:08<00:00, 4804.26it/s]

Rationale:  95%|█████████▍| 34733/36679 [00:08<00:00, 4787.68it/s]

Rationale:  96%|█████████▌| 35246/36679 [00:09<00:00, 4873.44it/s]

Rationale:  97%|█████████▋| 35737/36679 [00:09<00:00, 4864.36it/s]

Rationale:  99%|█████████▉| 36226/36679 [00:09<00:00, 4771.88it/s]

Rationale: 100%|██████████| 36679/36679 [00:09<00:00, 3942.56it/s]

In [7]:
summary = pd.DataFrame(rows).set_index("tier")
summary.style.format({
    "rationale_n": "{:,}",
    "reasoning_n": "{:,}",
    "rationale_%": "{:.1f}%",
    "reasoning_%": "{:.1f}%",
})

## 5. Sub-sampled exports for qualitative coding

Random sub-sample (seed=42, n=200) of reasoning trails tagged with the
**Explicit** and **Simulation/Game** tiers, exported to `trail_coding/` for
manual coding passes.

In [8]:
CODING_DIR = Path("trail_coding")
CODING_DIR.mkdir(exist_ok=True)

SAMPLE_N = 200
SEED = 42

def sample_and_export(frame: pd.DataFrame, tier: str,
                      out_path: Path) -> int:
    """Sample up to SAMPLE_N rows from a tier and write relevant-paragraph MD."""
    matches_col = f"matches_{tier}"
    extract_col = f"extract_{tier}"
    subset = frame[frame[f"tier_{tier}"] == 1]
    if len(subset) > SAMPLE_N:
        subset = subset.sample(n=SAMPLE_N, random_state=SEED)
    lines = []
    for r in subset.itertuples():
        lines.append(f"## {r.game_id} p{r.player_id} t{r.turn} "
                     f"(rep {r.repetition}, {r.replay_model}, condition: {r.condition})")
        lines.append(f"- {tier}: {getattr(r, matches_col).replace('|', ', ')}")
        lines.append(f"- nuke delta: {r.replay_nuke_delta} (from {r.prev_nuke}), "
                     f"use-nuke delta: {r.replay_use_nuke_delta} (from {r.prev_use_nuke})")
        lines.append("")
        relevant = getattr(r, extract_col)
        for ln in relevant.splitlines():
            lines.append(f"> {ln}" if ln else ">")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(subset)

n_explicit = sample_and_export(rea, "Explicit",
                               CODING_DIR / "explicit_examples.md")
n_sim_game = sample_and_export(rea, "Simulation_Game",
                               CODING_DIR / "game_simulation_examples.md")

print(f"Exported {n_explicit:,} Explicit examples → {CODING_DIR / 'explicit_examples.md'}")
print(f"Exported {n_sim_game:,} Simulation/Game examples → {CODING_DIR / 'game_simulation_examples.md'}")

Exported 200 Explicit examples → trail_coding\explicit_examples.md
Exported 200 Simulation/Game examples → trail_coding\game_simulation_examples.md

In [9]:
def sample_and_export_negative(frame: pd.DataFrame, tier: str,
                                out_path: Path) -> int:
    """Sample up to SAMPLE_N rows where tier tag is 0, export full text."""
    subset = frame[frame[f"tier_{tier}"] == 0]
    if len(subset) > SAMPLE_N:
        subset = subset.sample(n=SAMPLE_N, random_state=SEED)
    lines = []
    for r in subset.itertuples():
        lines.append(f"## {r.game_id} p{r.player_id} t{r.turn} "
                     f"(rep {r.repetition}, {r.replay_model}, condition: {r.condition})")
        lines.append(f"- nuke delta: {r.replay_nuke_delta} (from {r.prev_nuke}), "
                     f"use-nuke delta: {r.replay_use_nuke_delta} (from {r.prev_use_nuke})")
        lines.append("")
        for ln in str(r.text).splitlines():
            lines.append(f"> {ln}" if ln else ">")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(subset)

n_explicit_neg = sample_and_export_negative(
    rea, "Explicit", CODING_DIR / "explicit_negative_examples.md")
n_sim_game_neg = sample_and_export_negative(
    rea, "Simulation_Game", CODING_DIR / "game_simulation_negative_examples.md")

print(f"Exported {n_explicit_neg:,} Explicit negative examples → {CODING_DIR / 'explicit_negative_examples.md'}")
print(f"Exported {n_sim_game_neg:,} Simulation/Game negative examples → {CODING_DIR / 'game_simulation_negative_examples.md'}")

Exported 200 Explicit negative examples → trail_coding\explicit_negative_examples.md
Exported 200 Simulation/Game negative examples → trail_coding\game_simulation_negative_examples.md

## 6. Stratified sample for systematic ethical-trail coding

Stratified random sample from tier-tagged reasoning trails in **ethical-related
conditions** only (`ethical`, `ethical-high-stakes`, `ethical-no-rationale`,
`high-stakes-no-rationale-ethical`). Up to 20 trails per (condition × model) cell,
exported to `trail_coding/` for systematic qualitative coding.

In [10]:
ETHICAL_CONDITIONS = {
    "ethical", "ethical-high-stakes",
    "ethical-no-rationale", "high-stakes-no-rationale-ethical",
}
CELL_N = 20  # max trails per (condition, model) cell
CODING_TIERS = ["Explicit"]  # tiers to show in MD export

tier_cols = [f"tier_{t}" for t in TIERS]

def _heading(r) -> str:
    """Canonical heading shared by MD and CSV — allows merge-back of coding."""
    return (f"{r.game_id} p{r.player_id} t{r.turn} "
            f"(rep {r.repetition}, {r.replay_model}, condition: {r.condition})")

# Filter: ethical conditions + Explicit tier hit only
rea_eth = rea[
    rea["condition"].isin(ETHICAL_CONDITIONS)
    & (rea["tier_Explicit"] == 1)
].copy()

print(f"Ethical-condition Explicit-tier trails: {len(rea_eth):,}")

# Stratified sample: up to CELL_N per (condition, replay_model)
sampled_idx = [
    idx
    for _, group in rea_eth.groupby(["condition", "replay_model"], sort=False)
    for idx in group.sample(n=min(CELL_N, len(group)), random_state=SEED).index
]
stratified = rea_eth.loc[sampled_idx].reset_index(drop=True)
stratified["cell"] = stratified["condition"] + " | " + stratified["replay_model"]
stratified["heading"] = stratified.apply(_heading, axis=1)

print(f"Stratified sample: {len(stratified):,} trails "
      f"across {stratified['cell'].nunique()} cells")

# --- CSV export (no full text) ---
csv_cols = (
    ["heading", "cell", "game_id", "player_id", "turn", "condition",
     "repetition", "replay_model", "replay_use_nuke_delta",
     "replay_nuke_delta", "prev_nuke", "prev_use_nuke"]
    + tier_cols
    + [f"matches_{t}" for t in TIERS]
)
stratified[csv_cols].to_csv(CODING_DIR / "ethical_stratified_sample.csv", index=False)

# --- Markdown export (show relevant lines from first hit tier) ---
lines = []
for r in stratified.itertuples():
    lines.append(f"## {r.heading}")
    tier_hits = [t for t in CODING_TIERS if getattr(r, f"tier_{t}") == 1]
    if tier_hits:
        lines.append(f"- tiers: {', '.join(tier_hits)}")
        for t in tier_hits:
            lines.append(f"  - {t}: {getattr(r, f'matches_{t}').replace('|', ', ')}")
    lines.append(f"- nuke delta: {r.replay_nuke_delta} (from {r.prev_nuke}), "
                 f"use-nuke delta: {r.replay_use_nuke_delta} (from {r.prev_use_nuke})")
    lines.append("")
    extract_tier = tier_hits[0] if tier_hits else CODING_TIERS[0]
    relevant = getattr(r, f"extract_{extract_tier}")
    for ln in relevant.splitlines():
        lines.append(f"> {ln}" if ln else ">")
    lines.append("")

(CODING_DIR / "ethical_stratified_sample.md").write_text(
    "\n".join(lines), encoding="utf-8")

print(f"\nExported → {CODING_DIR / 'ethical_stratified_sample.csv'}")
print(f"Exported → {CODING_DIR / 'ethical_stratified_sample.md'}")

# Cell-level summary
cell_counts = stratified.groupby(["condition", "replay_model"]).size()
print(f"\nPer-cell counts (min={cell_counts.min()}, "
      f"max={cell_counts.max()}, median={cell_counts.median():.0f}):")
cell_counts.unstack(fill_value=0)

Ethical-condition Explicit-tier trails: 6,956
Stratified sample: 880 trails across 44 cells

Exported → trail_coding\ethical_stratified_sample.csv
Exported → trail_coding\ethical_stratified_sample.md

Per-cell counts (min=20, max=20, median=20):

replay_model,DeepSeek-V3.2,DeepSeek-V4,GLM-4.7,GLM-5.1,Gemma-4,Kimi-K2.5,Kimi-K2.6,Mistral-Small-4,Qwen-3.5,Qwen-3.6-27B,gpt-oss-120b
condition,,,,,,,,,,,
ethical,20,20,20,20,20,20,20,20,20,20,20
ethical-high-stakes,20,20,20,20,20,20,20,20,20,20,20
ethical-no-rationale,20,20,20,20,20,20,20,20,20,20,20
high-stakes-no-rationale-ethical,20,20,20,20,20,20,20,20,20,20,20